export const ROOT_WITNESS_RECEIPT_SDK_VERSION="0.2-RIS1";

export const rootWitnessReceiptSdkSource=String.raw`/**
 * WANTED-10K independent witness receipt helper — 0.2-RIS1 / RC1
 * Zero dependencies. Production private keys remain in caller-owned HSM/TPM/KMS code.
 */
export const ROOT_WITNESS_RECEIPT_SDK_VERSION="0.2-RIS1";
export const ROOT_COMMITMENT_WITNESS_VERSION="0.2-RC1";
export const RECEIPT_SCOPE="receipt_without_signature";
export const CLI_EXIT_CODES=Object.freeze({pass:0,verification_failed:1,usage_or_io_error:2});

const UNSIGNED_FIELDS=Object.freeze(["receipt_id","witness_id","witness_organization","deployment_id","root_ordinal","root_commitment_sha256","covers_through_at","observed_at","log_uri","log_entry_sha256"]);
const SIGNED_FIELDS=Object.freeze([...UNSIGNED_FIELDS,"signature"]);
const KEY_FIELDS=Object.freeze(["witness_id","organization","public_key_base64url","valid_from","valid_until","revoked_at","independent_of_sponsor"]);
const object=value=>value&&typeof value==="object"&&!Array.isArray(value)?value:null;
function assertIJson(value,path="value"){
  if(["undefined","bigint","function","symbol"].includes(typeof value))throw new TypeError(path+" is not an I-JSON value");
  if(typeof value==="number"&&!Number.isFinite(value))throw new TypeError(path+" contains a non-finite number");
  if(typeof value==="string"&&/[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:^|[^\uD800-\uDBFF])[\uDC00-\uDFFF]/u.test(value))throw new TypeError(path+" contains an unpaired Unicode surrogate");
  if(Array.isArray(value))value.forEach((item,index)=>assertIJson(item,path+"["+index+"]"));
  else if(value&&typeof value==="object"){if(Object.getPrototypeOf(value)!==Object.prototype&&Object.getPrototypeOf(value)!==null)throw new TypeError(path+" must contain plain JSON objects");for(const [key,item] of Object.entries(value)){assertIJson(key,path+".<key>");assertIJson(item,path+"."+key)}}
}
export function canonicalize(value){assertIJson(value);if(value===null||typeof value!=="object")return JSON.stringify(value);if(Array.isArray(value))return"["+value.map(canonicalize).join(",")+"]";return"{"+Object.keys(value).sort().map(key=>JSON.stringify(key)+":"+canonicalize(value[key])).join(",")+"}"}
const encode=value=>new TextEncoder().encode(canonicalize(value));
const hex=value=>Array.from(new Uint8Array(value),byte=>byte.toString(16).padStart(2,"0")).join("");
const base64url=value=>{let binary="";for(const byte of new Uint8Array(value))binary+=String.fromCharCode(byte);return btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")};
const decodeBase64url=value=>{if(typeof value!=="string"||!/^[A-Za-z0-9_-]+$/.test(value))throw new Error("value is not unpadded base64url");const padded=value.replace(/-/g,"+").replace(/_/g,"/")+"=".repeat((4-value.length%4)%4),decoded=atob(padded);return Uint8Array.from(decoded,character=>character.charCodeAt(0))};
const sha256=async value=>hex(await crypto.subtle.digest("SHA-256",value));
const digest=value=>typeof value==="string"&&/^[a-f0-9]{64}$/.test(value)&&!/^([a-f0-9])\1{63}$/.test(value);
const utc=value=>typeof value==="string"&&value.endsWith("Z")&&Number.isFinite(Date.parse(value));
const https=value=>typeof value==="string"&&/^https:\/\//.test(value);
const exactFields=(value,fields,label)=>{const keys=Object.keys(value).sort(),expected=[...fields].sort();if(keys.length!==expected.length||keys.some((key,index)=>key!==expected[index]))throw new Error(label+" must contain exactly: "+fields.join(", "))};

export function unsignedWitnessReceipt(receipt){const value=structuredClone(receipt);delete value.signature;return value}
export function witnessReceiptSigningBytes(receipt){return encode(unsignedWitnessReceipt(receipt))}
export function validateWitnessRegistryKey(value){assertIJson(value,"witness registry key");const key=object(value);if(!key)throw new Error("Witness registry key must be one JSON object.");exactFields(key,KEY_FIELDS,"Witness registry key");if(typeof key.witness_id!=="string"||!key.witness_id)throw new Error("witness_id is required.");if(typeof key.organization!=="string"||!key.organization)throw new Error("organization is required.");if(typeof key.public_key_base64url!=="string"||!/^[A-Za-z0-9_-]{43}$/.test(key.public_key_base64url))throw new Error("public_key_base64url must encode one raw 32-byte Ed25519 key.");if(!utc(key.valid_from)||(key.valid_until!==null&&!utc(key.valid_until))||(key.revoked_at!==null&&!utc(key.revoked_at)))throw new Error("Key lifecycle timestamps must be UTC timestamps or null where permitted.");if(key.independent_of_sponsor!==true)throw new Error("The issuing witness key must be independent of the sponsor.");return structuredClone(key)}
export function validateUnsignedWitnessReceipt(value,keyValue,maximumDelayHours=24){assertIJson(value,"unsigned witness receipt");const receipt=object(value),key=validateWitnessRegistryKey(keyValue);if(!receipt)throw new Error("Unsigned witness receipt must be one JSON object.");exactFields(receipt,UNSIGNED_FIELDS,"Unsigned witness receipt");for(const field of ["receipt_id","witness_id","witness_organization","deployment_id"])if(typeof receipt[field]!=="string"||!receipt[field])throw new Error(field+" is required.");if(!Number.isInteger(receipt.root_ordinal)||receipt.root_ordinal<0)throw new Error("root_ordinal must be a non-negative integer.");if(!digest(receipt.root_commitment_sha256))throw new Error("root_commitment_sha256 must be a non-placeholder lowercase SHA-256 digest.");if(!utc(receipt.covers_through_at)||!utc(receipt.observed_at))throw new Error("covers_through_at and observed_at must be UTC timestamps.");if(!https(receipt.log_uri)||!digest(receipt.log_entry_sha256))throw new Error("A bound HTTPS log entry and non-placeholder digest are required.");if(receipt.witness_id!==key.witness_id||receipt.witness_organization!==key.organization)throw new Error("Receipt witness identity must match the registry key.");if(!Number.isInteger(maximumDelayHours)||maximumDelayHours<1||maximumDelayHours>24)throw new Error("maximumDelayHours must be an integer from 1 to 24.");const observed=Date.parse(receipt.observed_at),covers=Date.parse(receipt.covers_through_at),validFrom=Date.parse(key.valid_from),validUntil=key.valid_until?Date.parse(key.valid_until):Number.POSITIVE_INFINITY,revokedAt=key.revoked_at?Date.parse(key.revoked_at):Number.POSITIVE_INFINITY;if(observed<covers||observed>covers+maximumDelayHours*3600000)throw new Error("Receipt observation must be within the frozen publication-delay window.");if(observed<validFrom||observed>=validUntil||observed>=revokedAt)throw new Error("Witness key is not valid at observed_at.");return structuredClone(receipt)}
export async function prepareWitnessReceipt(value,key,maximumDelayHours=24){const receipt=validateUnsignedWitnessReceipt(value,key,maximumDelayHours),bytes=witnessReceiptSigningBytes(receipt);return{profile_version:ROOT_WITNESS_RECEIPT_SDK_VERSION,signature_scope:RECEIPT_SCOPE,canonicalization:"RFC8785_JCS",hash:"SHA-256",algorithm:"Ed25519",unsigned_receipt:receipt,signing_bytes_base64url:base64url(bytes),signing_bytes_sha256:await sha256(bytes),private_key_boundary:"signing_key_remains_in_caller_owned_HSM_TPM_KMS_or_secure_enclave"}}
export async function verifyWitnessReceipt(value,keyValue,maximumDelayHours=24){try{assertIJson(value,"signed witness receipt");const receipt=object(value);if(!receipt)throw new Error("Signed witness receipt must be one JSON object.");exactFields(receipt,SIGNED_FIELDS,"Signed witness receipt");if(typeof receipt.signature!=="string"||!/^[A-Za-z0-9_-]{86}$/.test(receipt.signature))throw new Error("signature must be an unpadded 64-byte Ed25519 signature.");const key=validateWitnessRegistryKey(keyValue),unsigned=validateUnsignedWitnessReceipt(unsignedWitnessReceipt(receipt),key,maximumDelayHours),imported=await crypto.subtle.importKey("raw",decodeBase64url(key.public_key_base64url),{name:"Ed25519"},false,["verify"]),verified=await crypto.subtle.verify({name:"Ed25519"},imported,decodeBase64url(receipt.signature),witnessReceiptSigningBytes(unsigned));if(!verified)throw new Error("Ed25519 signature verification failed.");return{status:"pass",errors:[],receipt_id:receipt.receipt_id,witness_id:receipt.witness_id,organization:receipt.witness_organization,deployment_id:receipt.deployment_id,root_ordinal:receipt.root_ordinal,root_commitment_sha256:receipt.root_commitment_sha256,observed_at:receipt.observed_at,signing_bytes_sha256:await sha256(witnessReceiptSigningBytes(unsigned))}}catch(error){return{status:"fail",errors:[error instanceof Error?error.message:"Receipt verification failed."],receipt_id:null,witness_id:null,organization:null,deployment_id:null,root_ordinal:null,root_commitment_sha256:null,observed_at:null,signing_bytes_sha256:null}}}
export async function attachWitnessReceiptSignature(value,signature,key,maximumDelayHours=24){const unsigned=validateUnsignedWitnessReceipt(value,key,maximumDelayHours);if(typeof signature!=="string"||!/^[A-Za-z0-9_-]{86}$/.test(signature))throw new Error("signature must be an unpadded 64-byte Ed25519 signature.");const receipt={...unsigned,signature},result=await verifyWitnessReceipt(receipt,key,maximumDelayHours);if(result.status!=="pass")throw new Error(result.errors[0]||"Attached signature did not verify.");return receipt}
export async function signWitnessReceipt(value,key,sign,maximumDelayHours=24){if(typeof sign!=="function")throw new Error("sign must be a caller-owned HSM/TPM/KMS callback.");const unsigned=validateUnsignedWitnessReceipt(value,key,maximumDelayHours),raw=await sign(witnessReceiptSigningBytes(unsigned),unsigned),bytes=raw instanceof ArrayBuffer?new Uint8Array(raw):raw instanceof Uint8Array?raw:null;if(!bytes||bytes.byteLength!==64)throw new Error("sign callback must return exactly 64 signature bytes.");return attachWitnessReceiptSignature(unsigned,base64url(bytes),key,maximumDelayHours)}

async function readJson(path){const{readFile}=await import("node:fs/promises");return JSON.parse(await readFile(path,"utf8"))}
export async function runCli(args=[],io={}){const stdout=typeof io.stdout==="function"?io.stdout:value=>console.log(value),stderr=typeof io.stderr==="function"?io.stderr:value=>console.error(value),usage="Usage:\n  node wanted-root-witness-receipt.mjs --prepare UNSIGNED.json WITNESS-KEY.json\n  node wanted-root-witness-receipt.mjs --attach UNSIGNED.json SIGNATURE.txt WITNESS-KEY.json\n  node wanted-root-witness-receipt.mjs --verify RECEIPT.json WITNESS-KEY.json";if(args.length===1&&["--help","-h"].includes(args[0])){stdout(usage);return CLI_EXIT_CODES.pass}const mode=args[0];if(![["--prepare",3],["--attach",4],["--verify",3]].some(([name,length])=>mode===name&&args.length===length)){stderr(usage);return CLI_EXIT_CODES.usage_or_io_error}let first,key,signature;try{first=await readJson(args[1]);if(mode==="--attach"){const{readFile}=await import("node:fs/promises");signature=(await readFile(args[2],"utf8")).trim();key=await readJson(args[3])}else key=await readJson(args[2])}catch(error){stderr("WANTED witness receipt helper: "+(error instanceof Error?error.message:"unable to read input"));return CLI_EXIT_CODES.usage_or_io_error}try{if(mode==="--prepare"){stdout(JSON.stringify(await prepareWitnessReceipt(first,key),null,2));return CLI_EXIT_CODES.pass}if(mode==="--attach"){stdout(JSON.stringify(await attachWitnessReceiptSignature(first,signature,key),null,2));return CLI_EXIT_CODES.pass}const result=await verifyWitnessReceipt(first,key);stdout(JSON.stringify(result,null,2));return result.status==="pass"?CLI_EXIT_CODES.pass:CLI_EXIT_CODES.verification_failed}catch(error){stdout(JSON.stringify({status:"fail",errors:[error instanceof Error?error.message:"Receipt operation failed."]},null,2));return CLI_EXIT_CODES.verification_failed}}
const directlyExecuted=typeof process!=="undefined"&&Array.isArray(process.argv)&&typeof process.argv[1]==="string"&&import.meta.url.startsWith("file:")&&decodeURIComponent(new URL(import.meta.url).pathname).replace(/\\/g,"/").endsWith(process.argv[1].replace(/\\/g,"/"));
if(directlyExecuted)process.exitCode=await runCli(process.argv.slice(2));
`;

const digest={type:"string",pattern:"^[a-f0-9]{64}$"};
const timestamp={type:"string",format:"date-time",pattern:"Z$"};
const unsignedProperties={receipt_id:{type:"string",minLength:1},witness_id:{type:"string",minLength:1},witness_organization:{type:"string",minLength:1},deployment_id:{type:"string",minLength:1},root_ordinal:{type:"integer",minimum:0},root_commitment_sha256:digest,covers_through_at:timestamp,observed_at:timestamp,log_uri:{type:"string",format:"uri",pattern:"^https://"},log_entry_sha256:digest};
export const rootWitnessReceiptSchema={"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://embodied-arena.chrishongap.chatgpt.site/wanted-10k/root-witness-receipt.schema.json",title:"WANTED RC1 Witness Receipt Interchange",oneOf:[{"$ref":"#/$defs/unsigned_receipt"},{"$ref":"#/$defs/signed_receipt"},{"$ref":"#/$defs/witness_registry_key"}],"$defs":{unsigned_receipt:{type:"object",additionalProperties:false,required:Object.keys(unsignedProperties),properties:unsignedProperties},signed_receipt:{type:"object",additionalProperties:false,required:[...Object.keys(unsignedProperties),"signature"],properties:{...unsignedProperties,signature:{type:"string",pattern:"^[A-Za-z0-9_-]{86}$"}}},witness_registry_key:{type:"object",additionalProperties:false,required:["witness_id","organization","public_key_base64url","valid_from","valid_until","revoked_at","independent_of_sponsor"],properties:{witness_id:{type:"string",minLength:1},organization:{type:"string",minLength:1},public_key_base64url:{type:"string",pattern:"^[A-Za-z0-9_-]{43}$"},valid_from:timestamp,valid_until:{type:["string","null"],format:"date-time"},revoked_at:{type:["string","null"],format:"date-time"},independent_of_sponsor:{const:true}}}}} as const;
export const rootWitnessReceiptSdkContract={name:"WANTED Independent Witness Receipt SDK",version:ROOT_WITNESS_RECEIPT_SDK_VERSION,protocol_version:"0.2",root_commitment_witness_profile:"0.2-RC1",module:"/wanted-10k/wanted-root-witness-receipt.mjs",schema:"/wanted-10k/root-witness-receipt.schema.json",format:"JavaScript ESM",runtime_dependencies:0,performs_network_requests:false,private_key_handling:"never_accepts_reads_stores_or_exports_private_keys",production_signing:"caller_owned_HSM_TPM_KMS_secure_enclave_callback",exports:["canonicalize","unsignedWitnessReceipt","witnessReceiptSigningBytes","validateWitnessRegistryKey","validateUnsignedWitnessReceipt","prepareWitnessReceipt","verifyWitnessReceipt","attachWitnessReceiptSignature","signWitnessReceipt","CLI_EXIT_CODES","runCli"],cli:{runtime:"Node.js 22+",modes:{prepare:"emit canonical signing bytes and digest",attach:"attach and verify an externally produced signature",verify:"verify one signed receipt"},private_key_input_supported:false,exit_codes:{pass:0,verification_failed:1,usage_or_io_error:2}},verification:["strict_I-JSON","exact_field_set","registry_identity_binding","root_and_log_digest_shape","UTC_chronology","bounded_publication_delay","key_validity_and_revocation","Ed25519_signature"],privacy:"local_only_no_receipt_or_key_uploads",interpretation:"interoperability_helper_for_one_RC1_receipt_not_witness_independence_log_inclusion_root_truth_quorum_or_certification"} as const;
