"use client";
import { useState } from "react";
import { SiteNav } from "../components/SiteNav";
import { track } from "../components/AnalyticsHeartbeat";
const videos=[
{type:"Breakdown",length:"12:42",mark:"95→5",title:"Why 95% task success can still fail on the factory floor",creator:"Arena Editorial",desc:"A field-operations view of throughput, interventions, and the cost of a failure every four minutes."},
{type:"Builder log",length:"18:06",mark:"π:G",title:"π0.5 vs GR00T: what a single rank leaves out",creator:"Arena Lab Notes",desc:"How embodiment, data mix, and control frequency change what a leaderboard result actually means."},
{type:"Paper club",length:"09:18",mark:"01—05",title:"The five abilities every embodied brain needs",creator:"Arena Paper Club",desc:"Intent, perception, planning, affordance, and failure analysis—explained as one execution pipeline."},
{type:"Hardware",length:"15:24",mark:"TACT",title:"Tactile data changes dexterous manipulation",creator:"Arena Hardware Desk",desc:"What tactile benchmark design reveals that vision-only success metrics routinely miss."},
{type:"Methods",length:"08:10",mark:"MTBF",title:"Mean time between failures for robot people",creator:"Arena Field Guide",desc:"A practical reliability metric that turns autonomy claims into staffing and economics questions."},
{type:"Research",length:"11:05",mark:"FRESH",title:"Fresh objects, fresh poses, honest scores",creator:"Arena Research",desc:"Why calibration grids and stale object sets can hide brittle policy behavior."},
];
export default function Watch(){const [active,setActive]=useState<number|null>(null);return <main><SiteNav/><section className="subHero shell"><span className="kicker">RESEARCH / EDITORIAL PREVIEWS</span><h1>Evidence,<br/><em>without the highlight reel.</em></h1><p>Explore upcoming topics about robot models and evaluation. These are short editorial previews; videos and full articles are not yet published.</p><a href="/studio">Create your own benchmark & charts →</a></section><section className="routeSection shell"><div className="watchGrid">{videos.map((v,i)=><button key={v.title} aria-expanded={active===i} onClick={()=>{setActive(active===i?null:i);track("editorial_preview_opened","/watch",{title:v.title})}} className={active===i?"open":""}><div className={`watchArt w${i}`}><span>{v.mark}</span><i aria-hidden="true">↗</i><small>Preview</small></div><div className="watchCopy"><small>{v.type.toUpperCase()}</small><h2>{v.title}</h2><p>{v.creator}</p>{active===i&&<div className="watchDetail"><p>{v.desc}</p><span>Editorial preview · not a published video</span></div>}</div></button>)}</div><div className="internalRecommend"><div><span className="kicker">SUGGEST A TOPIC</span><h2>Pitch the next teardown.</h2><p>Email your suggestion to hfxaa llc. Include the robot, paper, or benchmark you would like covered.</p></div><a href="mailto:privacy@getrobotrouter.com?subject=Robot%20Router%20topic%20suggestion">Email a recommendation →</a></div></section></main>}
