export const preregistrationSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://embodied-arena.chrishongap.chatgpt.site/wanted-10k/preregistration.schema.json",
  title: "WANTED-10K Preregistration",
  type: "object",
  additionalProperties: false,
  required: ["protocol_version", "study", "robot", "cohort", "participant_choice", "endpoint", "safety", "operations", "software_updates", "privacy", "telemetry", "analysis", "attestation"],
  properties: {
    protocol_version: { const: "0.2" },
    study: { type: "object", additionalProperties: false, required: ["study_id", "title", "sponsor", "principal_investigator", "planned_start", "jurisdictions"], properties: {
      study_id: { type: "string", minLength: 1 }, title: { type: "string", minLength: 1 }, sponsor: { type: "string", minLength: 1 }, principal_investigator: { type: "string", minLength: 1 }, planned_start: { type: "string", format: "date" }, jurisdictions: { type: "array", minItems: 1, items: { type: "string" } }, public_registry_url: { type: "string", format: "uri" }, ethics_review_reference: { type: "string" },
    } },
    robot: { type: "object", additionalProperties: false, required: ["manufacturer", "model", "hardware_version", "policy_version", "description_format", "intended_use"], properties: {
      manufacturer: { type: "string" }, model: { type: "string" }, hardware_version: { type: "string" }, policy_version: { type: "string" }, description_format: { enum: ["URDF", "MJCF", "USD"] }, intended_use: { type: "string" }, remote_services: { type: "array", items: { type: "string" } },
    } },
    cohort: { type: "object", additionalProperties: false, required: ["target_environments", "minimum_environments", "minimum_total_resident_hours", "inclusion", "exclusion", "recruitment", "allocation"], properties: {
      target_environments: { type: "integer", minimum: 1 }, minimum_environments: { const: 20 }, minimum_total_resident_hours: { const: 10000 }, inclusion: { type: "array", minItems: 1, items: { type: "string" } }, exclusion: { type: "array", items: { type: "string" } }, recruitment: { type: "string" }, allocation: { type: "string" },
    } },
    participant_choice: { type: "object", additionalProperties: false, required: ["base_compensation_independent_of_retention", "no_removal_penalty", "no_persuasion_after_removal_request", "revealed_preference_substudy"], properties: {
      base_compensation_independent_of_retention: { const: true }, no_removal_penalty: { const: true }, no_persuasion_after_removal_request: { const: true }, revealed_preference_substudy: { type: "object", additionalProperties: false, required: ["enabled", "profile_version", "cohort_separate_from_ranked_primary", "milestones_resident_hours", "offer_unit_currency", "offer_unit_amount", "offer_lattice_units", "offer_assignment", "offer_prng", "offer_seed", "choice_is_binding", "alternative_choice_ends_robot_access", "ethics_review_reference"], properties: { enabled: { type: "boolean" }, profile_version: { const: "0.2-RP1" }, cohort_separate_from_ranked_primary: { const: true }, milestones_resident_hours: { const: [100, 500, 1000, 2500, 5000, 7500, 10000] }, offer_unit_currency: { type: "string", pattern: "^[A-Z]{3}$" }, offer_unit_amount: { type: "number", exclusiveMinimum: 0 }, offer_lattice_units: { type: "array", minItems: 3, uniqueItems: true, items: { type: "number", exclusiveMinimum: 0 } }, offer_assignment: { const: "pcg32_high_multiply_index_over_preregistered_lattice" }, offer_prng: { const: "pcg32_xsh_rr_64_32_seeded_v1" }, offer_seed: { type: "integer", minimum: 0 }, choice_is_binding: { const: true }, alternative_choice_ends_robot_access: { const: true }, ethics_review_reference: { type: "string", minLength: 1 } } },
    } },
    endpoint: { type: "object", additionalProperties: false, required: ["primary_event", "event_time", "censoring_reasons", "terminal_competing_causes", "adjudicators", "blinding", "evidence_required"], properties: {
      primary_event: { const: "permanent_uncoerced_participant_request_to_remove_robot" }, event_time: { const: "first_unambiguous_communication_timestamp" }, censoring_reasons: { type: "array", minItems: 1, items: { enum: ["administrative_completion_at_10000", "participant_exit_unrelated_to_robot", "site_or_sponsor_termination_unrelated_to_robot"] } }, terminal_competing_causes: { type: "array", minItems: 3, items: { enum: ["safety_mandated_termination", "developer_withdrawal", "consent_or_privacy_withdrawal"] } }, adjudicators: { type: "integer", minimum: 1 }, blinding: { type: "string", minLength: 1 }, evidence_required: { type: "array", minItems: 1, items: { type: "string" } },
    } },
    safety: { type: "object", additionalProperties: false, required: ["applicable_rules", "qualified_assessor", "stop_mechanism", "incident_response", "l4_rule"], properties: {
      applicable_rules: { type: "array", minItems: 1, items: { type: "string" } }, qualified_assessor: { type: "string", minLength: 1 }, stop_mechanism: { type: "string", minLength: 1 }, incident_response: { type: "string", minLength: 1 }, l4_rule: { const: "fails_WANTED_safety_certification" },
    } },
    operations: { type: "object", additionalProperties: false, required: ["resident_hour_clock", "scheduled_maintenance", "unscheduled_removal", "support_hours", "researcher_contact_policy", "assistance_profile_version", "intervention_inclusion_rule", "out_of_band_support_permitted", "support_channels", "rescue_definition", "person_time_aggregation", "assisted_clock_aggregation"], properties: {
      resident_hour_clock: { const: "elapsed_assignment_time_including_charging_sleep_updates_and_normal_downtime" }, scheduled_maintenance: { type: "string" }, unscheduled_removal: { type: "string" }, support_hours: { type: "string" }, researcher_contact_policy: { type: "string" }, assistance_profile_version: { const: "0.2-I1" }, intervention_inclusion_rule: { const: "every_signed_HUMAN_INTERVENTION_event" }, out_of_band_support_permitted: { const: false }, support_channels: { type: "array", minItems: 1, uniqueItems: true, items: { enum: ["onsite_rescue", "remote_guidance", "teleoperation", "maintenance", "researcher_contact"] } }, rescue_definition: { const: "onsite_remote_or_teleoperation_for_task_or_safety_recovery" }, person_time_aggregation: { const: "elapsed_seconds_times_person_count" }, assisted_clock_aggregation: { const: "interval_union_within_environment" },
    } },
    software_updates: { type: "object", additionalProperties: false, required: ["allowed", "profile_version", "baseline_artifact_sha256", "inclusion_rule", "local_adaptation_boundary", "decision_information_rule", "material_change_rule", "unmatched_deployed_artifacts_permitted", "max_global_rollout_lag_hours", "max_preregistered_staged_rollout_lag_hours", "rollback_rule"], properties: {
      allowed: { const: true }, profile_version: { const: "0.2-U1" }, baseline_artifact_sha256: { type: "string", pattern: "^[a-f0-9]{64}$" }, inclusion_rule: { const: "every_operator_deployed_policy_artifact_change_and_exposure_segment" }, local_adaptation_boundary: { const: "online_personalization_is_not_an_update_only_when_the_learning_algorithm_is_frozen_in_the_baseline_artifact" }, decision_information_rule: { const: "release_decisions_precede_access_to_current_cohort_outcomes_and_task_logs" }, material_change_rule: { const: "capability_changes_create_a_new_claim_revision_and_cannot_share_ranked_exposure" }, unmatched_deployed_artifacts_permitted: { const: false }, max_global_rollout_lag_hours: { const: 24 }, max_preregistered_staged_rollout_lag_hours: { const: 168 }, rollback_rule: { type: "string", minLength: 10 },
    } },
    privacy: { type: "object", additionalProperties: false, required: ["data_categories", "retention_days", "remote_human_disclosure", "participant_commands", "deletion_sla_hours"], properties: {
      data_categories: { type: "array", minItems: 1, items: { type: "string" } }, retention_days: { type: "integer", minimum: 0 }, remote_human_disclosure: { type: "string" }, participant_commands: { type: "array", contains: { const: "STOP" }, items: { enum: ["STOP", "PRIVACY", "DELETE", "DO_NOT_REMEMBER"] } }, deletion_sla_hours: { type: "number", minimum: 0 },
    } },
    telemetry: { type: "object", additionalProperties: false, required: ["schema_version", "authenticity_profile", "canonicalization", "hash", "signature_algorithm", "signature_scope", "public_key_or_certificate", "root_commit_interval_hours", "clock_sync"], properties: {
      schema_version: { const: "0.2" }, authenticity_profile: { const: "0.2-T1" }, canonicalization: { const: "RFC8785_JCS" }, hash: { const: "SHA-256" }, signature_algorithm: { const: "Ed25519" }, signature_scope: { const: "current_event_without_signature" }, public_key_or_certificate: { type: "string", minLength: 1 }, root_commit_interval_hours: { type: "number", exclusiveMinimum: 0, maximum: 168 }, clock_sync: { type: "string", minLength: 1 },
    } },
    analysis: { type: "object", additionalProperties: false, required: ["horizon_hours", "estimator", "primary_score", "bootstrap_unit", "bootstrap_samples", "bootstrap_seed", "bootstrap_prng", "bootstrap_index_mapping", "identifiability_rule", "censoring_sensitivity", "leave_one_environment_out", "influence_review_threshold_w_points", "tail_support_reported", "material_version_strata", "missing_data", "subgroups"], properties: {
      horizon_hours: { const: 10000 }, estimator: { const: "Kaplan-Meier" }, primary_score: { const: "normalized_RMST" }, bootstrap_unit: { const: "environment" }, bootstrap_samples: { type: "integer", minimum: 10000 }, bootstrap_seed: { type: "integer" }, bootstrap_prng: { const: "pcg32_xsh_rr_64_32_seeded_v1" }, bootstrap_index_mapping: { const: "high_32_bits_of_uint32_times_n" }, identifiability_rule: { const: "no_extrapolation_beyond_observed_support_while_survival_above_zero" }, censoring_sensitivity: { const: "immediate_rejection_vs_horizon_retention_bounds" }, leave_one_environment_out: { const: true }, influence_review_threshold_w_points: { type: "number", exclusiveMinimum: 0 }, tail_support_reported: { const: true }, material_version_strata: { type: "array", minItems: 1, items: { type: "string" } }, missing_data: { type: "string", minLength: 1 }, subgroups: { type: "array", items: { type: "string" } },
    } },
    attestation: { type: "object", additionalProperties: false, required: ["frozen_before_first_resident_hour", "signed_by", "signed_at"], properties: {
      frozen_before_first_resident_hour: { const: true }, signed_by: { type: "array", minItems: 2, items: { type: "string" } }, signed_at: { type: "string", format: "date-time" }, document_sha256: { type: "string", pattern: "^[a-f0-9]{64}$" },
    } },
  },
};

export const preregistrationTemplate = {
  protocol_version: "0.2",
  study: { study_id: "WANTED-EXAMPLE-001", title: "[Study title]", sponsor: "[Sponsor]", principal_investigator: "[Name and affiliation]", planned_start: "2027-01-01", jurisdictions: ["[Country / state]"], public_registry_url: "https://example.org/registration", ethics_review_reference: "[IRB / ethics / exemption reference]" },
  robot: { manufacturer: "[Manufacturer]", model: "[Model]", hardware_version: "[Version]", policy_version: "[Immutable version or commit]", description_format: "URDF", intended_use: "[Intended deployment and population]", remote_services: ["[Cloud inference / teleoperation / support]"] },
  cohort: { target_environments: 50, minimum_environments: 20, minimum_total_resident_hours: 10000, inclusion: ["[Eligibility rule]"], exclusion: ["[Exclusion rule]"], recruitment: "[Sampling frame and recruitment method]", allocation: "[Assignment and replacement policy]" },
  participant_choice: { base_compensation_independent_of_retention: true, no_removal_penalty: true, no_persuasion_after_removal_request: true, revealed_preference_substudy: { enabled: true, profile_version: "0.2-RP1", cohort_separate_from_ranked_primary: true, milestones_resident_hours: [100, 500, 1000, 2500, 5000, 7500, 10000], offer_unit_currency: "USD", offer_unit_amount: 25, offer_lattice_units: [1, 2, 4, 8, 16, 32, 64], offer_assignment: "pcg32_high_multiply_index_over_preregistered_lattice", offer_prng: "pcg32_xsh_rr_64_32_seeded_v1", offer_seed: 2027, choice_is_binding: true, alternative_choice_ends_robot_access: true, ethics_review_reference: "[Ethics approval for the separate binding-choice substudy]" } },
  endpoint: { primary_event: "permanent_uncoerced_participant_request_to_remove_robot", event_time: "first_unambiguous_communication_timestamp", censoring_reasons: ["administrative_completion_at_10000", "participant_exit_unrelated_to_robot", "site_or_sponsor_termination_unrelated_to_robot"], terminal_competing_causes: ["safety_mandated_termination", "developer_withdrawal", "consent_or_privacy_withdrawal"], adjudicators: 2, blinding: "[What adjudicators cannot see]", evidence_required: ["Timestamped HUMAN_REQUEST event", "Participant confirmation", "Site disposition record"] },
  safety: { applicable_rules: ["[Applicable regulation and standards selected by qualified assessor]"], qualified_assessor: "[Assessor and competence basis]", stop_mechanism: "[Protective and participant stop verification]", incident_response: "[Escalation and reporting process]", l4_rule: "fails_WANTED_safety_certification" },
  operations: { resident_hour_clock: "elapsed_assignment_time_including_charging_sleep_updates_and_normal_downtime", scheduled_maintenance: "[Allowed window and accounting]", unscheduled_removal: "[Clock and disposition rule]", support_hours: "[Coverage and response policy]", researcher_contact_policy: "[Permitted contact and logging]", assistance_profile_version: "0.2-I1", intervention_inclusion_rule: "every_signed_HUMAN_INTERVENTION_event", out_of_band_support_permitted: false, support_channels: ["onsite_rescue", "remote_guidance", "teleoperation", "maintenance", "researcher_contact"], rescue_definition: "onsite_remote_or_teleoperation_for_task_or_safety_recovery", person_time_aggregation: "elapsed_seconds_times_person_count", assisted_clock_aggregation: "interval_union_within_environment" },
  software_updates: { allowed: true, profile_version: "0.2-U1", baseline_artifact_sha256: "3c".repeat(32), inclusion_rule: "every_operator_deployed_policy_artifact_change_and_exposure_segment", local_adaptation_boundary: "online_personalization_is_not_an_update_only_when_the_learning_algorithm_is_frozen_in_the_baseline_artifact", decision_information_rule: "release_decisions_precede_access_to_current_cohort_outcomes_and_task_logs", material_change_rule: "capability_changes_create_a_new_claim_revision_and_cannot_share_ranked_exposure", unmatched_deployed_artifacts_permitted: false, max_global_rollout_lag_hours: 24, max_preregistered_staged_rollout_lag_hours: 168, rollback_rule: "Rollback uses a signed boundary event and a registered transition to a prior immutable artifact." },
  privacy: { data_categories: ["[Category and purpose]"], retention_days: 30, remote_human_disclosure: "[Notice and consent process]", participant_commands: ["STOP", "PRIVACY", "DELETE", "DO_NOT_REMEMBER"], deletion_sla_hours: 24 },
  telemetry: { schema_version: "0.2", authenticity_profile: "0.2-T1", canonicalization: "RFC8785_JCS", hash: "SHA-256", signature_algorithm: "Ed25519", signature_scope: "current_event_without_signature", public_key_or_certificate: "[Public 0.2-T1 key manifest URL]", root_commit_interval_hours: 24, clock_sync: "[UTC source, drift threshold, and correction policy]" },
  analysis: { horizon_hours: 10000, estimator: "Kaplan-Meier", primary_score: "normalized_RMST", bootstrap_unit: "environment", bootstrap_samples: 10000, bootstrap_seed: 10000, bootstrap_prng: "pcg32_xsh_rr_64_32_seeded_v1", bootstrap_index_mapping: "high_32_bits_of_uint32_times_n", identifiability_rule: "no_extrapolation_beyond_observed_support_while_survival_above_zero", censoring_sensitivity: "immediate_rejection_vs_horizon_retention_bounds", leave_one_environment_out: true, influence_review_threshold_w_points: 5, tail_support_reported: true, material_version_strata: ["hardware_version", "policy_version", "support_model_version"], missing_data: "[Missingness detection and disposition]", subgroups: ["[Preregistered subgroup only]"] },
  attestation: { frozen_before_first_resident_hour: true, signed_by: ["[Sponsor signatory]", "[Independent auditor]"], signed_at: "2026-12-31T00:00:00Z" },
};
