"use client";

import { ChangeEvent, DragEvent, useRef, useState } from "react";
import { track } from "./AnalyticsHeartbeat";

type Report={fileName:string;robotName:string;score:number;links:number;joints:number;dof:number;meshes:number;collisions:number;inertials:number;mass:number;issues:{level:"pass"|"warn"|"fail";text:string}[];recommendations:string[]};
const example=`<?xml version="1.0"?><robot name="arena_demo_arm"><link name="base"><inertial><mass value="12.5"/><inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/></inertial><visual><geometry><box size=".4 .4 .2"/></geometry></visual><collision><geometry><box size=".4 .4 .2"/></geometry></collision></link><link name="shoulder"><inertial><mass value="4.2"/><inertia ixx=".2" ixy="0" ixz="0" iyy=".2" iyz="0" izz=".2"/></inertial><visual><geometry><cylinder length=".5" radius=".06"/></geometry></visual><collision><geometry><cylinder length=".5" radius=".06"/></geometry></collision></link><link name="wrist"><visual><geometry><mesh filename="package://arena/wrist.stl"/></geometry></visual><collision><geometry><sphere radius=".08"/></geometry></collision></link><link name="gripper"><visual><geometry><mesh filename="package://arena/gripper.stl"/></geometry></visual></link><joint name="shoulder_pan" type="revolute"><parent link="base"/><child link="shoulder"/><limit lower="-3.14" upper="3.14" effort="120" velocity="2.2"/></joint><joint name="wrist_roll" type="continuous"><parent link="shoulder"/><child link="wrist"/><limit effort="32" velocity="3.1"/></joint><joint name="gripper_fixed" type="fixed"><parent link="wrist"/><child link="gripper"/></joint></robot>`;

export function UrdfScanner(){
  const input=useRef<HTMLInputElement>(null);const [dragging,setDragging]=useState(false);const [report,setReport]=useState<Report|null>(null);const [scanning,setScanning]=useState(false);const [error,setError]=useState("");
  const parse=(text:string,fileName:string)=>{setError("");setReport(null);setScanning(true);track("scan_started","/",{kind:fileName.split(".").pop()});window.setTimeout(()=>{const doc=new DOMParser().parseFromString(text,"application/xml");if(doc.querySelector("parsererror")||!doc.querySelector("robot")){setError("This file is not valid URDF/XML. Check its structure and try again.");setScanning(false);track("scan_failed");return}const robot=doc.querySelector("robot")!;const links=Array.from(doc.querySelectorAll("link"));const joints=Array.from(doc.querySelectorAll("joint"));const names=links.map(x=>x.getAttribute("name")||"unnamed");const children=joints.map(j=>j.querySelector("child")?.getAttribute("link")).filter(Boolean) as string[];const broken=joints.filter(j=>{const p=j.querySelector("parent")?.getAttribute("link"),c=j.querySelector("child")?.getAttribute("link");return !!((p&&!names.includes(p))||(c&&!names.includes(c)))}).length;const duplicates=names.filter((n,i)=>names.indexOf(n)!==i);const roots=names.filter(n=>!children.includes(n));const inertials=doc.querySelectorAll("inertial").length,collisions=doc.querySelectorAll("collision").length,meshes=doc.querySelectorAll("mesh").length;const dof=joints.filter(j=>!['fixed','floating'].includes(j.getAttribute('type')||'')).length;const mass=Array.from(doc.querySelectorAll("mass")).reduce((s,n)=>s+Number(n.getAttribute("value")||0),0);let score=100-broken*18-duplicates.length*15-Math.max(0,links.length-inertials)*4-Math.max(0,links.length-collisions)*3-(roots.length===1?0:10);score=Math.max(12,Math.min(100,score));const issues:Report['issues']=[{level:links.length?'pass':'fail',text:`${links.length} links and ${joints.length} joints parsed`},{level:roots.length===1?'pass':'warn',text:roots.length===1?`Single root link: ${roots[0]}`:`${roots.length} root links detected`},{level:broken?'fail':'pass',text:broken?`${broken} broken joint reference(s)`:'All joint references resolve'},{level:inertials===links.length?'pass':'warn',text:`Inertial data on ${inertials}/${links.length} links`},{level:collisions>=Math.max(1,links.length-1)?'pass':'warn',text:`Collision geometry on ${collisions}/${links.length} links`}];const lower=`${robot.getAttribute('name')} ${names.join(' ')}`.toLowerCase();const recommendations=[dof>=5?'Manipulation stress suite':'Embodied reasoning suite',/wheel|mobile|base/.test(lower)?'Navigation reality-gap suite':'Fresh-object generalization',/grip|finger|hand/.test(lower)?'Dexterity + tactile suite':'Reliability endurance run'];const result={fileName,robotName:robot.getAttribute("name")||"Unnamed robot",score,links:links.length,joints:joints.length,dof,meshes,collisions,inertials,mass,issues,recommendations};setReport(result);setScanning(false);track("scan_completed","/",{score,links:links.length,joints:joints.length})},650)};
  const file=async(f?:File)=>{if(!f)return;if(f.size>25*1024*1024){setError("File is larger than 25 MB.");return}if(!/\.(urdf|xml)$/i.test(f.name)){setError("Upload a .urdf or .xml file.");return}parse(await f.text(),f.name)};
  const drop=(e:DragEvent<HTMLDivElement>)=>{e.preventDefault();setDragging(false);file(e.dataTransfer.files[0])};
  const download=()=>{if(!report)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));a.download=`${report.robotName.replace(/\W+/g,'-').toLowerCase()}-readiness.json`;a.click();URL.revokeObjectURL(a.href);track("report_downloaded")};
  return <div className="homeScanner">
    <div className={`homeDrop ${dragging?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={drop} onClick={()=>input.current?.click()} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==='Enter')input.current?.click()}}><input ref={input} type="file" accept=".urdf,.xml" onChange={(e:ChangeEvent<HTMLInputElement>)=>file(e.target.files?.[0])}/><span>↑</span><b>{dragging?'Release to scan':'Drop robot.urdf here'}</b><small>or click to browse · processed privately in this browser</small><i>OR</i><button onClick={e=>{e.stopPropagation();parse(example,'arena-demo.urdf')}}>Try the example</button></div>
    <div className="homeReport">
      {!report&&!scanning&&<div className="reportStandby"><div className="standbyRing"><i/></div><span>ANALYZER READY</span><p>Topology · limits · inertia · collision · benchmark fit</p></div>}
      {scanning&&<div className="reportStandby scanningNow"><div className="standbyRing"><i/></div><span>READING ROBOT GRAPH</span><p>Running five readiness modules…</p></div>}
      {report&&<><header><div><small>SCAN COMPLETE · {report.fileName}</small><h2>{report.robotName}</h2></div><div className="readyScore"><b>{report.score}</b><span>/100<br/>READY</span></div></header><div className="miniStats"><div><b>{report.links}</b><span>links</span></div><div><b>{report.joints}</b><span>joints</span></div><div><b>{report.dof}</b><span>DOF</span></div><div><b>{report.mass.toFixed(1)}</b><span>kg</span></div></div><div className="homeIssues">{report.issues.map((x,i)=><p key={i}><i className={x.level}>{x.level==='pass'?'✓':x.level==='warn'?'!':'×'}</i>{x.text}</p>)}</div><div className="matchList"><small>BEST NEXT TESTS</small>{report.recommendations.map(x=><span key={x}>{x}<b>→</b></span>)}</div><button className="downloadBtn" onClick={download}>Download report.json</button></>}
    </div>{error&&<div className="homeError">⚠ {error}</div>}
  </div>;
}
