import assert from "node:assert/strict";
import test from "node:test";
import { ANALYSIS_ESTIMATOR, ANALYSIS_REPRODUCTION_VERSION, analysisReproductionContract, analysisReproductionSchema, analysisReproductionTemplate, assessAnalysisReproduction } from "../app/wanted-10k/analysis-reproduction/profile.ts";
import { auditManifestTemplates } from "../app/wanted-10k/audit/manifest.ts";
import { assessManifest } from "../app/wanted-10k/audit/readiness.ts";

const clone=value=>structuredClone(value);const gate=(result,id)=>result.gates.find(item=>item.id===id);

test("reproduces the complete synthetic WILD analysis exactly",()=>{const result=assessAnalysisReproduction(analysisReproductionTemplate);assert.equal(result.status,"passed",JSON.stringify(result.gates));assert.equal(result.summary.wanted_score,87.5);assert.ok(Math.abs(result.summary.ci95_lower-75)<1e-6);assert.equal(result.summary.ci95_upper,96.875);assert.equal(result.summary.support_at_10000,8);assert.equal(result.summary.environment_count,24);assert.equal(result.summary.total_resident_hours,120000)});

test("fails altered primary, uncertainty, and robustness claims",()=>{const primary=clone(analysisReproductionTemplate);primary.claimed.wanted_score+=.01;assert.equal(gate(assessAnalysisReproduction(primary),"A5").passed,false);const uncertainty=clone(analysisReproductionTemplate);uncertainty.claimed.ci95_lower+=.01;assert.equal(gate(assessAnalysisReproduction(uncertainty),"A6").passed,false);const robustness=clone(analysisReproductionTemplate);robustness.claimed.censoring_bound_width-=1;assert.equal(gate(assessAnalysisReproduction(robustness),"A6").passed,false)});

test("fails duplicate units and terminal competing causes",()=>{const duplicate=clone(analysisReproductionTemplate);duplicate.records[1].environment_id_sha256=duplicate.records[0].environment_id_sha256;assert.equal(gate(assessAnalysisReproduction(duplicate),"A3").passed,false);const terminal=clone(analysisReproductionTemplate);terminal.records[8].disposition="developer_withdrawal";assert.equal(gate(assessAnalysisReproduction(terminal),"A2").passed,false)});

test("binds analysis reproduction only to WANTED WILD audit claims",async()=>{assert.equal(auditManifestTemplates.WANTED_WILD.analysis_reproduction.profile_version,"0.2-A1");for(const target of ["PREQUALIFIED","WANTED_LAB","WANTED_10K"])assert.equal(auditManifestTemplates[target].analysis_reproduction.applicable,false);const result=await assessManifest(JSON.stringify(auditManifestTemplates.WANTED_WILD));assert.equal(result.status,"test",JSON.stringify(result.gates));assert.equal(result.projection.analysis_reproduced,true);assert.equal(result.projection.wanted_score,87.5);const missing=clone(auditManifestTemplates.WANTED_WILD);missing.evidence=missing.evidence.filter(item=>item.role!=="analysis_reproduction_report");assert.equal(gate(await assessManifest(JSON.stringify(missing)),"G4").status,"fail");const altered=clone(auditManifestTemplates.WANTED_WILD);altered.primary.wanted_score+=.1;assert.equal(gate(await assessManifest(JSON.stringify(altered)),"G4").status,"fail");const unbound=clone(auditManifestTemplates.WANTED_WILD);unbound.analysis_reproduction.exposure_integrity_sha256=`ff${"0123456789abcdef".repeat(4)}`.slice(0,64);assert.equal(gate(await assessManifest(JSON.stringify(unbound)),"G4").status,"fail")});

test("publishes a strict non-ranking analysis contract",()=>{assert.equal(ANALYSIS_REPRODUCTION_VERSION,"0.2-A1");assert.equal(analysisReproductionContract.estimator,ANALYSIS_ESTIMATOR);assert.equal(analysisReproductionContract.ranking_effect,"eligibility_gate_not_score");assert.equal(analysisReproductionContract.bootstrap.minimum_samples,10000);assert.equal(analysisReproductionSchema.additionalProperties,false);assert.equal(analysisReproductionSchema.properties.bootstrap.properties.prng.const,"pcg32_xsh_rr_64_32_seeded_v1")});
