import assert from "node:assert/strict";
import test from "node:test";
import { assessAssistance, assistanceContract, assistanceTemplate, assistanceTemplateFor, reproduceAssistance } from "../app/wanted-10k/assistance-integrity/profile.ts";
const clone=value=>structuredClone(value),gate=(result,id)=>result.gates.find(item=>item.id===id);

test("reproduces complete assistance burden from signed episodes",()=>{const result=assessAssistance(assistanceTemplate);assert.equal(result.status,"passed",JSON.stringify(result));assert.equal(result.summary.environment_count,24);assert.equal(result.summary.intervention_count,72);assert.equal(result.summary.rescue_events,48);assert.equal(result.summary.mode_profiles.length,5);assert.ok(result.summary.assistance_ci95_lower<=result.summary.assistance_minutes_per_100_hours);assert.ok(result.summary.assistance_minutes_per_100_hours<=result.summary.assistance_ci95_upper)});
test("enforces every target's field exposure",()=>{for(const target of ["WANTED_LAB","WANTED_WILD","WANTED_10K"]){const result=assessAssistance(assistanceTemplateFor(target));assert.equal(result.status,"passed",target)}const short=assistanceTemplateFor("WANTED_10K");short.environments[0].resident_seconds-=3600;assert.equal(gate(assessAssistance(short),"I3").passed,false)});
test("rejects omitted and out-of-band help",()=>{const omitted=clone(assistanceTemplate);omitted.interventions.pop();assert.equal(gate(assessAssistance(omitted),"I1").passed,false);const hidden=clone(assistanceTemplate);hidden.out_of_band_support_sessions=1;assert.equal(gate(assessAssistance(hidden),"I1").passed,false)});
test("rejects invalid clocks, taxonomy drift, and claim manipulation",()=>{const clock=clone(assistanceTemplate);clock.interventions[0].ended_at=clock.interventions[0].started_at;assert.equal(gate(assessAssistance(clock),"I4").passed,false);const taxonomy=clone(assistanceTemplate);taxonomy.interventions[0].mode="phone_call";assert.equal(gate(assessAssistance(taxonomy),"I4").passed,false);const claim=clone(assistanceTemplate);claim.claimed.assistance_minutes_per_100_hours+=1;assert.equal(gate(assessAssistance(claim),"I6").passed,false)});
test("uses a lower bound, never infinity, when no rescue occurs",()=>{const manifest=assistanceTemplateFor("WANTED_LAB");manifest.interventions=manifest.interventions.filter(record=>record.mode==="maintenance");manifest.declared_intervention_count=manifest.interventions.length;manifest.claimed=reproduceAssistance(manifest.environments,manifest.interventions);const result=assessAssistance(manifest);assert.equal(result.status,"passed");assert.equal(result.summary.mean_time_between_human_rescue_hours,null);assert.equal(result.summary.no_rescue_lower_bound_hours,100)});
test("publishes a strict non-ranking assistance contract",()=>{assert.equal(assistanceContract.version,"0.2-I1");assert.equal(assistanceContract.ranking_effect,"none");assert.match(assistanceContract.interpretation,/nonranking/);assert.match(assistanceContract.uncertainty,/PCG32/)});
