import test from "node:test";
import assert from "node:assert/strict";
import { assessEndpointAdjudication, endpointContract, endpointSchema, endpointTemplateFor } from "../app/wanted-10k/endpoint-adjudication/profile.ts";

const clone = value => structuredClone(value);

test("reproduces every target endpoint decision set",()=>{for(const target of ["WANTED_LAB","WANTED_WILD","WANTED_10K"]){const input=endpointTemplateFor(target);const result=assessEndpointAdjudication(input);assert.equal(result.status,"passed",`${target}: ${result.gates.filter(g=>!g.passed).map(g=>g.id).join(",")}`);assert.equal(result.summary.environment_count,input.declared_environment_count);assert.equal(result.summary.unresolved_decisions,0)}});
test("WILD matches the canonical survival endpoint table",()=>{const result=assessEndpointAdjudication(endpointTemplateFor("WANTED_WILD"));assert.equal(result.summary.environment_count,24);assert.equal(result.summary.resident_hours,120000);assert.equal(result.summary.voluntary_rejections,4);assert.equal(result.summary.administrative_completions,8);assert.equal(result.summary.administrative_censors,12)});
test("rejects coerced or unconfirmed rejection and strategic relabeling",()=>{const coerced=clone(endpointTemplateFor("WANTED_WILD"));coerced.records[8].request_evidence.uncoerced=false;assert.equal(assessEndpointAdjudication(coerced).status,"failed");const relabeled=clone(endpointTemplateFor("WANTED_WILD"));relabeled.records[8].trigger="safety_plan";relabeled.records[8].final_decision.disposition="unrelated_censor";relabeled.records[8].final_decision.analysis_mapping="unrelated_censor";relabeled.records[8].request_evidence=null;relabeled.records[8].reviews.forEach(review=>review.disposition="unrelated_censor");assert.equal(assessEndpointAdjudication(relabeled).status,"failed")});
test("requires distinct blinded reviews and a third-review majority on disagreement",()=>{const duplicate=clone(endpointTemplateFor("WANTED_WILD"));duplicate.records[0].reviews[1].adjudicator_id_sha256=duplicate.records[0].reviews[0].adjudicator_id_sha256;assert.equal(assessEndpointAdjudication(duplicate).status,"failed");const unresolved=clone(endpointTemplateFor("WANTED_WILD"));unresolved.records[0].reviews[1].disposition="administrative_censor";assert.equal(assessEndpointAdjudication(unresolved).status,"failed")});
test("rejects missing candidates and aggregate manipulation",()=>{const omitted=clone(endpointTemplateFor("WANTED_WILD"));omitted.omitted_terminal_candidates=1;assert.equal(assessEndpointAdjudication(omitted).status,"failed");const altered=clone(endpointTemplateFor("WANTED_WILD"));altered.claimed.voluntary_rejections+=1;assert.equal(assessEndpointAdjudication(altered).status,"failed")});
test("publishes a strict nonranking endpoint contract",()=>{assert.equal(endpointContract.version,"0.2-J1");assert.match(endpointContract.ranking_effect,/never_score_or_tiebreaker/);assert.equal(endpointSchema.additionalProperties,false);assert.ok(endpointContract.hard_failures.includes("terminal_competing_cause_relabelled_as_censor"))});
