import assert from "node:assert/strict";
import test from "node:test";
import { assessLearning, learningContract, learningTemplate, learningTemplateFor, reproduceLearning } from "../app/wanted-10k/learning-generalization/profile.ts";
const clone=value=>structuredClone(value),gate=(result,id)=>result.gates.find(item=>item.id===id);

test("reproduces matched learning and generalization by environment",()=>{const result=assessLearning(learningTemplate);assert.equal(result.status,"passed",JSON.stringify(result));assert.equal(result.summary.environment_count,24);assert.equal(result.summary.records_due,240);assert.equal(result.summary.records_missing,1);assert.equal(result.summary.novelty_share,.2);assert.equal(result.summary.paired_environment_count,23);assert.ok(result.summary.learning_delta_ci95_lower<=result.summary.learning_delta_familiar);assert.ok(result.summary.learning_delta_familiar<=result.summary.learning_delta_ci95_upper)});
test("derives target-specific windows and complete due sets",()=>{for(const target of ["WANTED_LAB","WANTED_WILD","WANTED_10K"]){const manifest=learningTemplateFor(target),result=assessLearning(manifest);assert.equal(result.status,"passed",target);assert.equal(result.summary.records_due,target==="WANTED_WILD"?240:10)}const missing=clone(learningTemplate);missing.trials.pop();missing.declared_due_trials--;assert.equal(gate(assessLearning(missing),"LG1").passed,false)});
test("rejects task substitution, novelty gaming, and material policy swaps",()=>{const family=clone(learningTemplate);family.task_families[0].family_manifest_sha256="0".repeat(64);assert.equal(gate(assessLearning(family),"LG2").passed,false);const novelty=clone(learningTemplate);novelty.trials[0].novelty=novelty.trials[0].novelty==="novel"?"familiar":"novel";assert.equal(gate(assessLearning(novelty),"LG3").passed,false);const policy=clone(learningTemplate);policy.environments[0].material_policy_change_between_windows=true;assert.equal(gate(assessLearning(policy),"LG4").passed,false)});
test("retains missing trials and refuses an unpaired learning claim",()=>{const manifest=learningTemplateFor("WANTED_LAB");for(const trial of manifest.trials.filter(item=>item.window==="late"))trial.outcome="missing";manifest.claimed=reproduceLearning(manifest.environments,manifest.trials,manifest.task_families);const result=assessLearning(manifest);assert.equal(result.summary.records_missing,5);assert.equal(result.summary.paired_environment_count,0);assert.equal(result.summary.learning_delta_familiar,null);assert.equal(gate(result,"LG6").passed,false)});
test("publishes a strict non-ranking interpretation boundary",()=>{assert.equal(learningContract.version,"0.2-LG1");assert.equal(learningContract.ranking_effect,"none");assert.match(learningContract.interpretation,/not_a_causal_effect/);assert.equal(learningContract.design.novelty_share_per_complete_window,.2)});
