import assert from "node:assert/strict";
import test from "node:test";
import { assessPreregistrationIntegrity, preregistrationIntegrityContract, preregistrationIntegritySchema, preregistrationTemplateFor, PREREGISTRATION_TARGETS } from "../app/wanted-10k/preregistration-integrity/profile.ts";

const clone = value => structuredClone(value);

test("passes every certification target with a frozen root and complete amendment history",()=>{for(const target of PREREGISTRATION_TARGETS){const value=preregistrationTemplateFor(target);const result=assessPreregistrationIntegrity(value);assert.equal(result.status,"passed",`${target}: ${JSON.stringify(result.gates)}`);assert.equal(result.gates.length,7);assert.equal(result.summary.target_certification,target);assert.equal(result.summary.chain_breaks,0)}});

test("rejects a late or mutable registration root",()=>{const late=clone(preregistrationTemplateFor("WANTED_WILD"));late.original.registered_at=late.original.first_preflight_trial_at;late.original.receipt.issued_at=late.original.registered_at;assert.equal(assessPreregistrationIntegrity(late).gates.find(g=>g.id==="PR2").passed,false);const mutable=clone(preregistrationTemplateFor("WANTED_WILD"));mutable.original.registry_record_immutable=false;assert.equal(assessPreregistrationIntegrity(mutable).gates.find(g=>g.id==="PR2").passed,false)});

test("rejects broken parent links and receipt-imprint substitution",()=>{const broken=clone(preregistrationTemplateFor("WANTED_WILD"));broken.amendments[1].parent_document_sha256=broken.original.document_sha256;assert.equal(assessPreregistrationIntegrity(broken).gates.find(g=>g.id==="PR4").passed,false);const substituted=clone(preregistrationTemplateFor("WANTED_WILD"));substituted.amendments[0].receipt.message_imprint_sha256=substituted.original.document_sha256;assert.equal(assessPreregistrationIntegrity(substituted).gates.find(g=>g.id==="PR4").passed,false)});

test("rejects outcome-informed and retroactive amendments",()=>{const informed=clone(preregistrationTemplateFor("WANTED_WILD"));informed.amendments[1].aggregate_w_accessed=true;informed.claimed.outcome_informed_amendments=1;assert.equal(assessPreregistrationIntegrity(informed).gates.find(g=>g.id==="PR5").passed,false);const retroactive=clone(preregistrationTemplateFor("WANTED_WILD"));retroactive.amendments[1].retroactive_application=true;retroactive.claimed.retroactive_amendments=1;assert.equal(assessPreregistrationIntegrity(retroactive).gates.find(g=>g.id==="PR6").passed,false)});

test("forces material changes into a new claim revision",()=>{const sameClaim=clone(preregistrationTemplateFor("WANTED_WILD"));sameClaim.amendments[1].classification="material";sameClaim.claimed.administrative_amendments=0;sameClaim.claimed.material_amendments=1;sameClaim.claimed.material_amendments_in_same_claim=1;assert.equal(assessPreregistrationIntegrity(sameClaim).gates.find(g=>g.id==="PR6").passed,false);const newClaim=clone(preregistrationTemplateFor("WANTED_WILD"));newClaim.amendments[1].classification="material";newClaim.amendments[1].creates_new_claim_revision=true;newClaim.amendments[1].claim_revision_id="claim-r2";newClaim.claimed.administrative_amendments=0;newClaim.claimed.material_amendments=1;assert.equal(assessPreregistrationIntegrity(newClaim).status,"passed")});

test("rejects aggregate history manipulation and publishes a strict nonranking contract",()=>{const value=clone(preregistrationTemplateFor("WANTED_WILD"));value.claimed.post_activity_amendments=0;assert.equal(assessPreregistrationIntegrity(value).gates.find(g=>g.id==="PR7").passed,false);assert.equal(preregistrationIntegrityContract.version,"0.2-PR1");assert.equal(preregistrationIntegrityContract.ranking_effect,"eligibility_only_never_score_or_tiebreaker");assert.equal(preregistrationIntegritySchema.additionalProperties,false);assert.equal(preregistrationIntegritySchema.properties.claimed.properties.outcome_informed_amendments.const,0)});
