import assert from "node:assert/strict";
import test from "node:test";
import { assessProtocolDeviations, deviationTemplateFor, protocolDeviationContract, protocolDeviationSchema, reproduceDeviationClaims } from "../app/wanted-10k/protocol-deviations/profile.ts";

const clone = value => structuredClone(value);
test("passes every target with complete deviation reconciliation",()=>{for(const target of ["PREQUALIFIED","WANTED_LAB","WANTED_WILD","WANTED_10K"]){const input=deviationTemplateFor(target),result=assessProtocolDeviations(input);assert.equal(result.status,"passed",`${target}: ${JSON.stringify(result.gates)}`);assert.deepEqual(reproduceDeviationClaims(input),input.claimed);assert.equal(result.gates.length,7)}});
test("rejects suppressed discovery candidates and duplicate sources",()=>{const input=clone(deviationTemplateFor("WANTED_WILD"));input.reconciliation.unique_candidates=3;input.claimed.suppressed_deviations=1;assert.equal(assessProtocolDeviations(input).gates.find(g=>g.id==="DV2").passed,false);const duplicate=clone(deviationTemplateFor("WANTED_WILD"));duplicate.records[1].source_record_sha256=duplicate.records[0].source_record_sha256;assert.equal(assessProtocolDeviations(duplicate).gates.find(g=>g.id==="DV3").passed,false)});
test("rejects late reporting and incomplete important CAPA",()=>{const late=clone(deviationTemplateFor("WANTED_WILD"));late.records[0].reported_at="2026-02-05T04:00:00Z";late.records[0].report_delay_hours=97;assert.equal(assessProtocolDeviations(late).gates.find(g=>g.id==="DV3").passed,false);const capa=clone(deviationTemplateFor("WANTED_WILD"));capa.records[1].preventive_action=null;assert.equal(assessProtocolDeviations(capa).gates.find(g=>g.id==="DV4").passed,false)});
test("rejects deviation labels used as analytic escape hatches",()=>{for(const [key,value] of [["excluded_from_primary_analysis",true],["resident_seconds_deducted",3600],["endpoint_reclassified",true],["outcome_or_aggregate_w_used_for_classification",true],["unresolved",true],["claim_invalidated",true]]){const input=clone(deviationTemplateFor("WANTED_WILD"));input.records[0][key]=value;assert.equal(assessProtocolDeviations(input).gates.find(g=>g.id==="DV6").passed,false,key)}});
test("enforces notifications and exact aggregate claims",()=>{const notice=clone(deviationTemplateFor("WANTED_WILD"));notice.records[1].participant_notice_required=true;assert.equal(assessProtocolDeviations(notice).gates.find(g=>g.id==="DV5").passed,false);const claim=clone(deviationTemplateFor("WANTED_WILD"));claim.claimed.important_deviations=0;assert.equal(assessProtocolDeviations(claim).gates.find(g=>g.id==="DV7").passed,false)});
test("publishes a strict nonranking machine contract",()=>{assert.equal(protocolDeviationContract.version,"0.2-DV1");assert.equal(protocolDeviationContract.universal_reporting_deadline_hours,null);assert.match(protocolDeviationContract.ranking_effect,/never_score_or_tiebreaker/);assert.equal(protocolDeviationSchema.additionalProperties,false);assert.equal(protocolDeviationSchema.properties.records.items.properties.excluded_from_primary_analysis.const,false);assert.equal(protocolDeviationSchema.properties.claimed.properties.suppressed_deviations.const,0)});
