import assert from "node:assert/strict";
import test from "node:test";
import { assessSamplingStopping, samplingStoppingContract, samplingStoppingSchema, samplingStoppingTemplateFor } from "../app/wanted-10k/sampling-stopping/profile.ts";

const clone=value=>structuredClone(value);
test("passes every target under a prospectively frozen result-independent closure",()=>{for(const target of ["PREQUALIFIED","WANTED_LAB","WANTED_WILD","WANTED_10K"]){const result=assessSamplingStopping(samplingStoppingTemplateFor(target));assert.equal(result.status,"passed",`${target}: ${JSON.stringify(result.gates)}`);assert.equal(result.gates.length,7);assert.equal(result.summary.target_certification,target);}});
test("rejects outcome access and result-informed extensions or early stops",()=>{for(const key of ["primary_outcome_access_events_before_cutoff","unscheduled_primary_analyses","result_informed_extensions","result_informed_early_stops"]){const input=clone(samplingStoppingTemplateFor("WANTED_WILD"));input.execution[key]=1;input.claimed[key]=1;const result=assessSamplingStopping(input);assert.equal(result.gates.find(row=>row.id==="ST3").passed,false);}});
test("rejects post-activity target and cutoff changes",()=>{const target=clone(samplingStoppingTemplateFor("WANTED_WILD"));target.execution.target_changes_after_activity=1;target.claimed.target_changes_after_activity=1;assert.equal(assessSamplingStopping(target).status,"failed");const cutoff=clone(samplingStoppingTemplateFor("WANTED_WILD"));cutoff.execution.observation_cutoff_at="2026-08-28T18:00:00Z";assert.equal(assessSamplingStopping(cutoff).gates.find(row=>row.id==="ST4").passed,false);});
test("requires sufficient targets and retains every overshoot unit",()=>{const short=clone(samplingStoppingTemplateFor("WANTED_WILD"));short.plan.planned_units=19;short.execution.actual_units=19;short.claimed.planned_units=19;short.claimed.actual_units=19;assert.equal(assessSamplingStopping(short).gates.find(row=>row.id==="ST2").passed,false);const excluded=clone(samplingStoppingTemplateFor("WANTED_WILD"));excluded.execution.all_overshoot_units_retained=false;excluded.claimed.excluded_overshoot_units=1;assert.equal(assessSamplingStopping(excluded).gates.find(row=>row.id==="ST5").passed,false);});
test("keeps interim monitoring independent and blind",()=>{const input=clone(samplingStoppingTemplateFor("WANTED_WILD"));input.monitoring_reviews[0].aggregate_w_visible=true;assert.equal(assessSamplingStopping(input).gates.find(row=>row.id==="ST6").passed,false);});
test("publishes a strict nonranking machine contract",()=>{assert.equal(samplingStoppingContract.version,"0.2-ST1");assert.equal(samplingStoppingContract.ranking_effect,"eligibility_only_never_score_or_tiebreaker");assert.equal(samplingStoppingContract.outcome_adaptive_enrollment_permitted,false);assert.equal(samplingStoppingSchema.properties.execution.properties.primary_outcome_access_events_before_cutoff.const,0);assert.equal(samplingStoppingSchema.properties.protocol.properties.efficacy_or_futility_stopping_permitted.const,false);});
