import assert from "node:assert/strict";
import test from "node:test";
import { assessServiceContinuity, reproduceServiceContinuity, serviceContract, serviceTemplate, serviceTemplateFor } from "../app/wanted-10k/service-continuity/profile.ts";

const clone = value => structuredClone(value);
const gate = (result, id) => result.gates.find(row => row.id === id);

test("passing service template reproduces every public metric", () => { const result = assessServiceContinuity(serviceTemplate); assert.equal(result.status, "passed"); assert.deepEqual(result.summary, { profile_version: "0.2-SC1", status: "passed", target_certification: "WANTED_WILD", ...reproduceServiceContinuity(serviceTemplate.environments, serviceTemplate.service_segments, serviceTemplate.maintenance_actions) }); });
test("target templates carry exact exposure", () => { const lab = serviceTemplateFor("WANTED_LAB"), wild = serviceTemplateFor("WANTED_WILD"), lifetime = serviceTemplateFor("WANTED_10K"); assert.equal(lab.claimed.resident_hours, 100); assert.equal(wild.environments.length, 24); assert.equal(wild.claimed.resident_hours, 120000); assert.equal(lifetime.claimed.resident_hours, 10000); for (const manifest of [lab, wild, lifetime]) assert.equal(assessServiceContinuity(manifest).status, "passed"); });
test("rejects gaps, overlaps, and hidden service events", () => { const gap = clone(serviceTemplate); gap.service_segments[0].ended_at = new Date(Date.parse(gap.service_segments[0].ended_at) - 1000).toISOString().replace(".000Z", "Z"); assert.equal(gate(assessServiceContinuity(gap), "SC3").passed, false); const hidden = clone(serviceTemplate); hidden.undocumented_service_events = 1; assert.equal(gate(assessServiceContinuity(hidden), "SC1").passed, false); assert.equal(gate(assessServiceContinuity(hidden), "SC5").passed, false); });
test("rejects omitted maintenance and mismatched claims", () => { const omitted = clone(serviceTemplate); omitted.maintenance_actions.pop(); assert.equal(gate(assessServiceContinuity(omitted), "SC1").passed, false); const claim = clone(serviceTemplate); claim.claimed.autonomous_available_fraction = .999; assert.equal(gate(assessServiceContinuity(claim), "SC6").passed, false); });
test("service integrity stays nonranking and has no universal uptime threshold", () => { assert.equal(serviceContract.version, "0.2-SC1"); assert.equal(serviceContract.certification_effect, "field_evidence_integrity_gate"); assert.equal(serviceContract.ranking_effect, "none"); assert.match(serviceContract.interpretation, /does not certify a minimum reliability or availability level/); });
