"use client";
import { useState } from "react";
import { assessExposureLedger, exposureLedgerTemplate, type ExposureResult } from "./profile";

const initial = assessExposureLedger(exposureLedgerTemplate);
export function ExposureLedgerLab(){
  const [input,setInput]=useState(JSON.stringify(exposureLedgerTemplate,null,2));
  const [result,setResult]=useState<ExposureResult>(initial);
  const load=()=>{const text=JSON.stringify(exposureLedgerTemplate,null,2);setInput(text);setResult(assessExposureLedger(exposureLedgerTemplate))};
  const run=()=>{try{setResult(assessExposureLedger(JSON.parse(input)))}catch(error){setResult({status:"invalid",errors:[error instanceof Error?error.message:"Invalid JSON."],gates:[],summary:null})}};
  const exportResult=()=>{if(!result.summary)return;const payload={benchmark:"WANTED-10K",exposure_ledger_profile_version:"0.2-X1",generated_at:new Date().toISOString(),status:result.status,gates:result.gates,...result.summary,note:"Local boundary, sequence, and arithmetic check only. Signatures, source events, commitments, and assessor independence require external verification."};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));const anchor=document.createElement("a");anchor.href=url;anchor.download="wanted-exposure-ledger-result.json";anchor.click();URL.revokeObjectURL(url)};
  return <section className="exposureLab"><header><div><span>LOCAL EXPOSURE-LEDGER EVALUATOR</span><b>PROFILE / 0.2-X1</b></div><div><button onClick={load}>LOAD SYNTHETIC EXAMPLE</button><button className="runExposure" onClick={run}>RECONCILE -&gt;</button></div></header><div className="exposureWorkspace"><div className="exposureEditor"><label htmlFor="exposure-input">SIGNED BOUNDARY + STREAM RECONCILIATION MANIFEST</label><textarea id="exposure-input" spellCheck={false} value={input} onChange={event=>setInput(event.target.value)}/><footer><a href="/wanted-10k/exposure-ledger.schema.json">MANIFEST SCHEMA</a><span>Runs locally. No participant data is uploaded.</span></footer></div><div className="exposureOutput"><div className={`exposureStatus ${result.status}`}><span>RESIDENT CLOCK</span><b>{result.status.toUpperCase()}</b><small>{result.errors[0]||(result.status==="passed"?"All seven exposure-ledger gates pass.":"One or more hard gates failed.")}</small></div>{result.summary&&<><div className="exposureMetrics"><article><span>ENVIRONMENTS</span><b>{result.summary.environment_count}</b></article><article><span>OFFICIAL HOURS</span><b>{result.summary.total_resident_hours.toLocaleString()}</b></article><article><span>PAUSE DEDUCTIONS</span><b>{result.summary.paused_seconds_deducted}</b></article><article><span>BOUNDARY MISMATCHES</span><b>{result.summary.boundary_mismatches}</b></article></div><div className="exposureGates">{result.gates.map(item=><article className={item.passed?"pass":"fail"} key={item.id}><span>{item.id}</span><div><b>{item.label}</b><p>{item.detail}</p></div><i>{item.passed?"PASS":"FAIL"}</i></article>)}</div><button className="exportExposure" onClick={exportResult}>EXPORT RESULT</button></>}</div></div><aside><b>RESIDENCE != UPTIME</b><p>The official clock measures elapsed assignment time, not autonomous availability. Charging, sleep, updates, degraded operation, maintenance, temporary pauses, and telemetry outages remain inside the resident interval and are disclosed separately.</p></aside></section>;
}
