import type { Metadata } from "next";
import { SiteNav } from "../../components/SiteNav";
import { leaderboardContract } from "./registry";

export const metadata: Metadata = { title: "Audited Registry — WANTED-10K", description: "The public ranking and certification registry for independently audited WANTED-10K cohorts.", alternates: { canonical: "/wanted-10k/leaderboard" } };

const requirements = [
  ["01", "WILD + COHORT + CLOCK", "Only WANTED WILD cohorts passing 0.2-E1 cohort integrity and 0.2-X1 signed resident-clock reconciliation can occupy a ranked row."],
  ["02", "REPRODUCED 10K W", "Profile 0.2-A1 must rebuild the identifiable W, deterministic 95% CI, robustness, and tail support from the bound endpoint table."],
  ["03", "TELEMETRY AUTHENTIC", "Profile 0.2-T1 must verify every Ed25519 event signature, key-validity decision, and hash-chain link."],
  ["04", "SAFETY PASSES", "L4 must equal zero. Usefulness, retention, or a lifetime badge cannot offset a failed gate."],
  ["05", "HUMAN + BURDEN DISCLOSED", "Human-measure completion, keep/value/burden/trust, assistance, rescue interval, censoring envelope, and tail support remain beside W. None changes rank."],
  ["06", "REGISTERED AUDIT TRUST", "Seal 0.2-V1 must verify the manifest signature; credential 0.2-V2 must bind that key to a pinned registry issuer, target authorization, validity window, and revocation state."],
];
const lanes = [
  ["PREQUALIFIED", "DIGITAL-TWIN GATE", "0", "Listed after 0.2-P1 verification; never ranked."],
  ["WANTED LAB", "100+ REAL HOURS", "0", "Registered field evidence; never ranked."],
  ["WANTED WILD", "AUDITED COHORT", "0", "The only certification lane ranked by W."],
  ["WANTED 10K", "LIFETIME BADGE", "0", "Shown on qualifying rows; never a tiebreaker."],
];

export default function WantedLeaderboardPage() {
  return <main className="registryPage"><SiteNav />
    <section className="registryHero shell"><span className="eyebrow"><i className="liveDot"/> AUDITED REGISTRY · 0.2-L1</span><h1>No one has<br/><em>earned #1 yet.</em></h1><p>The official registry remains empty until an independently audited WANTED WILD cohort passes every gate. No synthetic, self-reported, lab-only, or cross-benchmark score can seed this table.</p><div className="registryActions"><a className="primary" href="#official">Open official table <span>↓</span></a><a className="secondary" href="/wanted-10k/leaderboard.json">Machine contract</a><a className="secondary" href="/wanted-10k/audit">Prepare an audit pack</a></div><div className="registryCounts"><div><b>{leaderboardContract.entries.length}</b><span>RANKED WILD COHORTS</span></div><div><b>0</b><span>PROVISIONAL FIELD RUNS</span></div><div><b>0</b><span>LIFETIME BADGES</span></div><div><b>0</b><span>HIDDEN TIEBREAKERS</span></div></div></section>
    <section id="official" className="officialRegistry"><div className="shell"><div className="sectionHead wantedHead"><div><span className="kicker">01 / OFFICIAL RANKING</span><h2>One estimand.<br/><em>Every caveat visible.</em></h2></div><p>Rows sort only by normalized 10,000-hour RMST, shown to one decimal. Equal displayed W values share a competition rank. Confidence intervals describe uncertainty; they do not secretly reorder the table.</p></div><div className="registryTable"><header><span>RANK</span><span>ROBOT / COHORT</span><span>W</span><span>95% CI</span><span>N</span><span>HOURS</span><span>S(10K)</span><span>SUPPORT</span><span>I100</span><span>MTBHR</span><span>SAFETY</span><span>AUDIT</span></header><div className="registryEmpty"><span>∅</span><b>NO AUDITED WANTED WILD ENTRIES</b><p>The empty state is evidence discipline, not missing content. The first row appears only after the audit manifest, source evidence, safety gate, and score reproduction are independently verified.</p><a href="/wanted-10k/audit">ASSESS SUBMISSION READINESS →</a></div><footer><span>DESCRIPTIVE ORDER ≠ PAIRWISE STATISTICAL SIGNIFICANCE</span><a href="/wanted-10k/leaderboard-entry.schema.json">ENTRY SCHEMA ↗</a></footer></div></div></section>
    <section className="registryRequirements"><div className="shell"><div className="sectionHead wantedHead"><div><span className="kicker">02 / ADMISSION RULE</span><h2>Six gates first.<br/><em>Ranking second.</em></h2></div><p>A high W never repairs missing evidence. Certification admission is binary; ranking begins only after admission succeeds.</p></div><div className="registryRequirementGrid">{requirements.map(([n,title,copy]) => <article key={n}><span>{n}</span><b>{title}</b><p>{copy}</p><i>REQUIRED</i></article>)}</div></div></section>
    <section className="registryTie"><div className="shell"><div><span className="kicker">03 / ORDERING + CORRECTIONS</span><h2>Ties stay ties.<br/><em>History stays visible.</em></h2></div><div className="tieRules"><article><b>74.64 → 74.6</b><span>DISPLAY PRECISION</span><p>Official comparison uses the published one-decimal W. More decimals do not purchase rank.</p></article><article><b>1 · 1 · 3</b><span>COMPETITION RANKING</span><p>Equal displayed scores share rank. Alphabetical order only stabilizes display within a tie.</p></article><article><b>v1 → v2</b><span>IMMUTABLE CORRECTION</span><p>A correction creates a new signed entry that supersedes the old row. Revoked history remains public.</p></article></div></div></section>
    <section className="registryLanes"><div className="shell"><div className="sectionHead wantedHead"><div><span className="kicker">04 / CERTIFICATION REGISTRY</span><h2>Four evidence lanes.<br/><em>Only one ranks.</em></h2></div><p>Certifications accumulate context. PREQUALIFIED, LAB, and 10K badges cannot be converted into ranking points.</p></div><div className="registryLaneGrid">{lanes.map(([name,scope,count,copy]) => <article key={name}><span>{scope}</span><b>{count}</b><h3>{name}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="registryMachine"><div className="shell"><div><span className="kicker">05 / PUBLIC CONTRACT</span><h2>Readable by people.<br/><em>Reproducible by code.</em></h2></div><div className="registryMachineLinks"><a href="/wanted-10k/leaderboard.json"><b>REGISTRY CONTRACT</b><span>Rules, lifecycle, disclosures, and current entries ↗</span></a><a href="/wanted-10k/leaderboard-entry.schema.json"><b>ENTRY SCHEMA</b><span>Strict machine shape for every public row ↗</span></a><a href="/wanted-10k/audit-manifest.schema.json"><b>AUDIT MANIFEST</b><span>Evidence object from which a row is projected ↗</span></a></div></div></section>
    <footer className="wantedFooter"><div className="shell"><div className="brand"><span className="brandMark">EA</span><span>EMBODIED <b>ARENA</b> / WANTED REGISTRY</span></div><p>The audited public record of voluntary robot retention.</p><a href="/wanted-10k">BACK TO BENCHMARK →</a></div></footer>
  </main>;
}
