import type { Metadata } from "next";
import { SiteNav } from "../../components/SiteNav";
import { ServiceContinuityLab } from "./ServiceContinuityLab";

export const metadata: Metadata = { title: "Service Continuity Integrity — WANTED-10K", description: "Reproduce complete robot availability, degraded service, downtime, maintenance, recovery, technician, parts, and cloud-dependency evidence.", alternates: { canonical: "/wanted-10k/service-continuity" } };

const controls = [
  ["01", "EVERY SECOND HAS A STATE", "Available, degraded, and unavailable segments form one exact partition of the continuous resident clock."],
  ["02", "DOWNTIME STAYS VISIBLE", "Planned work, outages, cloud loss, charging failures, and repairs never pause resident exposure."],
  ["03", "EVERY HAND IS COUNTED", "Participant, operator, and technician time is retained with person counts, work orders, parts, and consumables."],
  ["04", "ZERO IS CENSORED", "No outage means at least the observed exposure without one—not infinite time between failures."],
];

export default function ServiceContinuityPage() { return <main className="servicePage"><SiteNav/>
  <section className="serviceHero shell"><span className="eyebrow"><i className="liveDot"/> SERVICE CONTINUITY INTEGRITY · 0.2-SC1</span><h1>Ten thousand hours<br/><em>include the bad hours.</em></h1><p>A robot cannot earn trust by deleting downtime from the clock or hiding the people, parts, cloud services, and maintenance that keep it alive. Profile 0.2-SC1 turns every resident second into an auditable service state and every repair into reproducible burden.</p><div className="serviceActions"><a className="primary" href="#verifier">Verify a manifest <span>↓</span></a><a className="secondary" href="/wanted-10k/service-continuity.template.json">Download template</a><a className="secondary" href="/wanted-10k/service-continuity.json">Open contract</a></div><div className="serviceProof"><div><b>100%</b><span>RESIDENT CLOCK PARTITIONED</span></div><div><b>0</b><span>HIDDEN SERVICE EVENTS</span></div><div><b>3</b><span>MUTUALLY EXCLUSIVE STATES</span></div><div><b>0</b><span>RANKING EFFECT</span></div></div></section>
  <section className="serviceControls"><div className="shell"><div className="sectionHead wantedHead"><div><span className="kicker">01 / CONTINUOUS ACCOUNTING</span><h2>Availability is a record.<br/><em>Not a marketing claim.</em></h2></div><p>IEC dependability guidance separates reliability, availability, maintainability, and supportability. WANTED operationalizes that boundary for long-lived robots without inventing a universal uptime threshold.</p></div><div className="serviceControlGrid">{controls.map(([id, title, copy]) => <article key={id}><span>{id}</span><b>{title}</b><p>{copy}</p></article>)}</div></div></section>
  <section className="serviceDark"><div className="shell"><div><span className="kicker">02 / CANONICAL STATE CLOCK</span><h2>Gaps are failures<br/><em>of evidence.</em></h2><p>Each environment begins at signed activation and ends at its first terminal boundary. State segments must be contiguous, non-overlapping, and cryptographically linked to telemetry. Planned and unplanned downtime remain inside the denominator.</p></div><div className="serviceEquation"><span>RESIDENT SERVICE IDENTITY</span><b>A + D + U = 1</b><p>Autonomous available fraction + degraded fraction + unavailable fraction must reproduce exactly from the complete partition.</p><small>AGGREGATE EVIDENCE · PER ENVIRONMENT FIRST</small></div></div></section>
  <section id="verifier" className="serviceVerifier"><div className="shell"><div className="sectionHead wantedHead"><div><span className="kicker">03 / LOCAL REPRODUCTION</span><h2>Bring every outage.<br/><em>Keep every denominator.</em></h2></div><p>The browser checker reconstructs availability, planned and unplanned downtime, recovery time, maintenance labor, technician visits, parts, consumables, and cloud-dependent loss from the protected register.</p></div><ServiceContinuityLab/></div></section>
  <section className="serviceRule"><div className="shell"><b>INTEGRITY GATE, NOT AN UPTIME SCORE</b><p>A difficult deployment can pass by reporting poor service honestly. A polished robot fails if it omits downtime or support. Service metrics explain retention; only voluntary retention determines rank.</p><a href="/wanted-10k/diagnostics">OPEN LONGITUDINAL DIAGNOSTICS →</a></div></section>
  <footer className="wantedFooter"><div className="shell"><div className="brand"><span className="brandMark">EA</span><span>EMBODIED <b>ARENA</b> / SERVICE 0.2-SC1</span></div><p>Count every hour the robot was hard to keep.</p><a href="/wanted-10k">BACK TO BENCHMARK →</a></div></footer>
  </main>; }
