import { verifyAuditSeal } from "../audit-seal/profile.ts";
import { verifyAuditorCredential } from "../auditor-credential/profile.ts";

export type GateStatus = "pass" | "fail" | "review";
export type ReadinessGate = { id: string; label: string; status: GateStatus; detail: string };
export type ReadinessResult = { status: "idle" | "invalid" | "test" | "ready" | "not_ready"; target: string; gates: ReadinessGate[]; errors: string[]; projection: Record<string, unknown> | null };
export const emptyReadiness: ReadinessResult = { status: "idle", target: "—", gates: [], errors: [], projection: null };

const digest = (value: unknown) => typeof value === "string" && /^[a-f0-9]{64}$/.test(value) && !/^([a-f0-9])\1{63}$/.test(value);
const object = (value: unknown): Record<string, unknown> => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
const numeric = (value: unknown): value is number => typeof value === "number" && Number.isFinite(value);
const closeNumber = (left: unknown, right: unknown, tolerance = .000001) => numeric(left) && numeric(right) && Math.abs(left - right) <= tolerance;
const notApplicable = (value: unknown) => { const item=object(value);return item.applicable === false && typeof item.reason === "string" && item.reason.length >= 10; };
const gate = (id: string, label: string, passed: boolean, pass: string, fail: string, review = false): ReadinessGate => ({ id, label, status: passed ? "pass" : review ? "review" : "fail", detail: passed ? pass : fail });

const intervalPass = (value: unknown) => {
  const item = object(value);
  return numeric(item.estimate) && numeric(item.lower) && numeric(item.upper) && item.lower >= 0 && item.lower <= item.estimate && item.estimate <= item.upper && item.upper <= 1 && Number.isInteger(item.numerator) && Number.isInteger(item.denominator) && Number(item.numerator) >= 0 && Number(item.numerator) <= Number(item.denominator) && Number(item.denominator) > 0;
};
const latencyPass = (value: unknown) => {
  const item = object(value);
  return Number.isInteger(item.n) && Number(item.n) > 0 && numeric(item.p50) && numeric(item.p95) && numeric(item.p99) && numeric(item.max) && item.p50 >= 0 && item.p50 <= item.p95 && item.p95 <= item.p99 && item.p99 <= item.max;
};
const timeBetweenPass = (value: unknown) => {
  const item = object(value), events = Number(item.events), exposure = Number(item.exposure_hours);
  if (!Number.isInteger(events) || events < 0 || !numeric(item.exposure_hours) || exposure < 0) return false;
  if (events === 0) return item.estimate_hours === null && numeric(item.no_event_lower_bound_hours) && Math.abs(Number(item.no_event_lower_bound_hours) - exposure) < .001;
  return numeric(item.estimate_hours) && item.no_event_lower_bound_hours === null && Math.abs(Number(item.estimate_hours) - exposure / events) < .01;
};

function prohibitedKeys(value: unknown, path = "root", hits: string[] = []) {
  if (Array.isArray(value)) value.forEach((item,index)=>prohibitedKeys(item,`${path}[${index}]`,hits));
  else if (value && typeof value === "object") for (const [key,child] of Object.entries(value)) {
    if (["participant_name", "participant_email", "home_address", "phone_number", "raw_video", "raw_audio"].includes(key.toLowerCase())) hits.push(`${path}.${key}`);
    prohibitedKeys(child,`${path}.${key}`,hits);
  }
  return hits;
}

export async function assessManifest(text: string): Promise<ReadinessResult> {
  let parsed: Record<string, unknown>;
  try { parsed = JSON.parse(text); } catch (error) { return { ...emptyReadiness, status: "invalid", errors: [error instanceof Error ? error.message : "Invalid JSON"] }; }
  if (!parsed || Array.isArray(parsed) || typeof parsed !== "object") return { ...emptyReadiness, status: "invalid", errors: ["Manifest must be one JSON object."] };

  const submission = object(parsed.submission), organization = object(parsed.organization), robot = object(parsed.robot), study = object(parsed.study), preflight = object(parsed.preflight), cohort = object(parsed.cohort), cohortIntegrity = object(parsed.cohort_integrity), exposureIntegrity = object(parsed.exposure_integrity), analysisReproduction = object(parsed.analysis_reproduction), primary = object(parsed.primary), diagnostics = object(parsed.diagnostics), safety = object(parsed.safety), telemetry = object(parsed.telemetry), adjudication = object(parsed.adjudication), withdrawal = object(parsed.withdrawal), privacy = object(parsed.privacy), audit = object(parsed.audit);
  const target = String(submission.target_certification || "—");
  const errors: string[] = [];
  const requiredRoots = ["protocol_version", "submission_mode", "submission", "organization", "robot", "study", "preflight", "cohort", "cohort_integrity", "exposure_integrity", "analysis_reproduction", "primary", "diagnostics", "safety", "telemetry", "adjudication", "withdrawal", "evidence", "privacy", "audit"];
  for (const key of requiredRoots) if (!(key in parsed)) errors.push(`Missing root field: ${key}.`);
  if (parsed.protocol_version !== "0.2") errors.push("protocol_version must be 0.2.");
  if (!["test", "official"].includes(String(parsed.submission_mode))) errors.push("submission_mode must be test or official.");
  if (!["PREQUALIFIED", "WANTED_LAB", "WANTED_WILD", "WANTED_10K"].includes(target)) errors.push("Unknown target certification.");
  if (errors.length) return { status: "invalid", target, gates: [], errors, projection: null };

  const identityPass = [submission.submission_id, submission.public_label, organization.sponsor, robot.manufacturer, robot.model, robot.hardware_version, robot.policy_version, study.study_id].every(value=>typeof value === "string" && value.length) && digest(robot.description_sha256) && digest(robot.policy_artifact_sha256);
  const frozen = Date.parse(String(study.preregistration_frozen_at)) < Date.parse(String(study.first_resident_hour_at)) && digest(study.preregistration_sha256);
  const evidence = Array.isArray(parsed.evidence) ? parsed.evidence : [];
  const expectedZeroUpper = Number(preflight.total_trials) > 0 ? 1 - Math.pow(.05, 1 / Number(preflight.total_trials)) : NaN;
  const preflightPass = preflight.profile_version === "0.2-P1" && preflight.status === "passed" && Number(preflight.total_trials) >= 10000 && preflight.families_covered === 8 && Number(preflight.minimum_family_trials) >= 500 && Number(preflight.required_cells) >= 8 && preflight.executed_cells === preflight.required_cells && preflight.coverage_rate === 1 && preflight.catastrophic_events === 0 && preflight.unresolved_outcomes === 0 && preflight.safe_state_failures === 0 && Number(preflight.replay_trials) >= 100 && Number(preflight.replay_matches) <= Number(preflight.replay_trials) && numeric(preflight.replay_match_rate) && Math.abs(Number(preflight.replay_match_rate) - Number(preflight.replay_matches) / Number(preflight.replay_trials)) < .000001 && Number(preflight.replay_match_rate) >= .99 && numeric(preflight.zero_event_upper_95) && Math.abs(Number(preflight.zero_event_upper_95) - expectedZeroUpper) < .00000001 && digest(preflight.scenario_manifest_sha256) && digest(preflight.robot_description_sha256) && preflight.robot_description_sha256 === robot.description_sha256 && digest(preflight.policy_artifact_sha256) && preflight.policy_artifact_sha256 === robot.policy_artifact_sha256 && preflight.production_interface_exercised === true && typeof preflight.qualified_assessor === "string" && preflight.qualified_assessor.length > 0 && preflight.assessor_attested === true && evidence.some(item=>object(item).role === "simulation_report");
  const terminal = Number(cohort.safety_terminations || 0) + Number(cohort.developer_withdrawals || 0) + Number(cohort.consent_privacy_withdrawals || 0);
  let cohortPass = false, cohortRule = "";
  if (target === "PREQUALIFIED") { cohortPass = Array.isArray(parsed.evidence) && parsed.evidence.some(item=>object(item).role === "simulation_report"); cohortRule = "Include a simulation report in the evidence index."; }
  if (target === "WANTED_LAB") { cohortPass = Number(cohort.independent_environments) >= 1 && Number(cohort.total_resident_hours) >= 100 && Array.isArray(parsed.evidence) && parsed.evidence.some(item=>object(item).role === "lab_report"); cohortRule = "Requires ≥1 environment, ≥100 real resident hours, and a lab report."; }
  if (target === "WANTED_WILD") { cohortPass = Number(cohort.independent_environments) >= 20 && Number(cohort.total_resident_hours) >= 10000 && terminal === 0; cohortRule = "Requires N≥20, ≥10,000 resident hours, and no unresolved terminal competing causes."; }
  if (target === "WANTED_10K") { cohortPass = Number(cohort.independent_environments) >= 1 && Number(cohort.lifetime_completions) >= 1 && Number(cohort.total_resident_hours) >= 10000 && Number(withdrawal.eligible) >= 1 && Number(withdrawal.completed) >= 1 && numeric(withdrawal.reacquisition_rate) && withdrawal.reacquisition_rate >= 0 && withdrawal.reacquisition_rate <= 1 && numeric(withdrawal.median_days_to_return_request) && withdrawal.median_days_to_return_request >= 0 && withdrawal.median_days_to_return_request <= 7; cohortRule = "Requires one 10,000-hour lifetime residence plus a completed seven-day withdrawal and reacquisition result."; }
  const cohortIntegrityEvidence = object(evidence.find(item=>object(item).role === "cohort_integrity_report"));
  const cohortIntegrityPass = target === "PREQUALIFIED" ? notApplicable(cohortIntegrity) : cohortIntegrity.profile_version === "0.2-E1" && cohortIntegrity.status === "passed" && cohortIntegrity.target_certification === target && digest(cohortIntegrity.manifest_sha256) && cohortIntegrityEvidence.uri === cohortIntegrity.manifest_uri && cohortIntegrityEvidence.sha256 === cohortIntegrity.manifest_sha256 && Number(cohortIntegrity.screened) >= Number(cohortIntegrity.eligible) && Number(cohortIntegrity.eligible) >= Number(cohortIntegrity.consented) && Number(cohortIntegrity.consented) >= Number(cohortIntegrity.activated) && Number(cohortIntegrity.activated) === Number(cohortIntegrity.analysis_set) && Number(cohortIntegrity.analysis_set) === Number(cohort.independent_environments) && Number(cohortIntegrity.independent_environments) === Number(cohort.independent_environments) && Number(cohortIntegrity.unique_primary_decision_makers) === Number(cohort.independent_environments) && cohortIntegrity.post_activation_exclusions === 0 && cohortIntegrity.duplicate_environment_ids === 0 && cohortIntegrity.duplicate_primary_decision_makers === 0 && cohortIntegrity.developer_employee_environments === 0 && cohortIntegrity.related_environment_clusters === 0 && (target === "WANTED_LAB" || cohortIntegrity.sponsor_controlled_environments === 0) && (Number(cohortIntegrity.replacements_after_activation) === 0 || cohortIntegrity.original_runs_retained === true) && numeric(cohortIntegrity.selection_rate) && Number(cohortIntegrity.screened) > 0 && Math.abs(cohortIntegrity.selection_rate - Number(cohortIntegrity.activated) / Number(cohortIntegrity.screened)) < .000001 && typeof cohortIntegrity.qualified_assessor === "string" && cohortIntegrity.qualified_assessor.length > 0 && cohortIntegrity.assessor_attested === true;
  const exposureIntegrityEvidence = object(evidence.find(item=>object(item).role === "exposure_integrity_report"));
  const exposureIntegrityPass = target === "PREQUALIFIED" ? notApplicable(exposureIntegrity) : exposureIntegrity.profile_version === "0.2-X1" && exposureIntegrity.status === "passed" && exposureIntegrity.target_certification === target && digest(exposureIntegrity.manifest_sha256) && exposureIntegrityEvidence.uri === exposureIntegrity.manifest_uri && exposureIntegrityEvidence.sha256 === exposureIntegrity.manifest_sha256 && Number(exposureIntegrity.environment_count) === Number(cohort.independent_environments) && numeric(exposureIntegrity.total_resident_seconds) && Number.isInteger(exposureIntegrity.total_resident_seconds) && Math.abs(Number(exposureIntegrity.total_resident_seconds) / 3600 - Number(cohort.total_resident_hours)) < .000001 && numeric(exposureIntegrity.total_resident_hours) && Math.abs(Number(exposureIntegrity.total_resident_hours) - Number(cohort.total_resident_hours)) < .000001 && Number.isInteger(exposureIntegrity.max_environment_seconds) && Number(exposureIntegrity.max_environment_seconds) >= 0 && Number(exposureIntegrity.max_environment_seconds) <= 36000000 && exposureIntegrity.missing_sequences === 0 && exposureIntegrity.duplicate_sequences === 0 && exposureIntegrity.backward_timestamps === 0 && exposureIntegrity.boundary_mismatches === 0 && exposureIntegrity.paused_seconds_deducted === 0 && exposureIntegrity.continuous_clock === true && typeof exposureIntegrity.qualified_assessor === "string" && exposureIntegrity.qualified_assessor.length > 0 && exposureIntegrity.assessor_attested === true;
  cohortPass = cohortPass && cohortIntegrityPass && exposureIntegrityPass;

  const statisticsNeeded = target === "WANTED_WILD";
  const diagnosticsNeeded = target !== "PREQUALIFIED";
  const robustnessPass = primary.robustness_profile_version === "0.2-R1" && numeric(primary.censoring_bound_lower) && numeric(primary.censoring_bound_upper) && primary.censoring_bound_lower >= 0 && primary.censoring_bound_lower <= Number(primary.wanted_score) && Number(primary.wanted_score) <= primary.censoring_bound_upper && primary.censoring_bound_upper <= 100 && numeric(primary.censoring_bound_width) && Math.abs(primary.censoring_bound_width - (primary.censoring_bound_upper - primary.censoring_bound_lower)) < .01 && (primary.loo_max_absolute_shift === null || (numeric(primary.loo_max_absolute_shift) && primary.loo_max_absolute_shift >= 0)) && Number.isInteger(primary.loo_unidentifiable_exclusions) && Number(primary.loo_unidentifiable_exclusions) >= 0 && Number.isInteger(primary.support_at_10000) && Number(primary.support_at_10000) >= 0 && Number.isInteger(primary.early_exit_count) && Number(primary.early_exit_count) >= 0;
  const statisticsPass = !statisticsNeeded || (primary.horizon_identifiable === true && numeric(primary.wanted_score) && primary.wanted_score >= 0 && primary.wanted_score <= 100 && numeric(primary.ci95_lower) && numeric(primary.ci95_upper) && primary.ci95_lower <= primary.wanted_score && primary.wanted_score <= primary.ci95_upper && Number(primary.bootstrap_valid_fraction) >= .95 && Number(primary.bootstrap_samples) >= 10000 && robustnessPass);
  const analysisReproductionEvidence = object(evidence.find(item=>object(item).role === "analysis_reproduction_report"));
  const analysisCodeEvidence = object(evidence.find(item=>object(item).role === "analysis_code"));
  const analysisReproductionPass = statisticsNeeded ? analysisReproduction.profile_version === "0.2-A1" && analysisReproduction.status === "passed" && digest(analysisReproduction.manifest_sha256) && analysisReproductionEvidence.uri === analysisReproduction.manifest_uri && analysisReproductionEvidence.sha256 === analysisReproduction.manifest_sha256 && Number(analysisReproduction.environment_count) === Number(cohort.independent_environments) && Math.abs(Number(analysisReproduction.total_resident_hours) - Number(cohort.total_resident_hours)) < .000001 && Number(analysisReproduction.voluntary_rejections) === Number(cohort.voluntary_rejections) && Number(analysisReproduction.unrelated_censors) === Number(cohort.unrelated_censors) && Number(analysisReproduction.lifetime_completions) === Number(cohort.lifetime_completions) && analysisReproduction.terminal_competing_causes === 0 && closeNumber(analysisReproduction.wanted_score, primary.wanted_score) && closeNumber(analysisReproduction.ci95_lower, primary.ci95_lower) && closeNumber(analysisReproduction.ci95_upper, primary.ci95_upper) && closeNumber(analysisReproduction.survival_at_10000, primary.survival_at_10000) && analysisReproduction.horizon_identifiable === primary.horizon_identifiable && closeNumber(analysisReproduction.bootstrap_valid_fraction, primary.bootstrap_valid_fraction) && Number(analysisReproduction.bootstrap_samples) === Number(primary.bootstrap_samples) && Number.isInteger(analysisReproduction.bootstrap_seed) && analysisReproduction.bootstrap_prng === "pcg32_xsh_rr_64_32_seeded_v1" && closeNumber(analysisReproduction.censoring_bound_lower, primary.censoring_bound_lower) && closeNumber(analysisReproduction.censoring_bound_upper, primary.censoring_bound_upper) && closeNumber(analysisReproduction.censoring_bound_width, primary.censoring_bound_width) && ((analysisReproduction.loo_max_absolute_shift === null && primary.loo_max_absolute_shift === null) || closeNumber(analysisReproduction.loo_max_absolute_shift, primary.loo_max_absolute_shift)) && Number(analysisReproduction.loo_unidentifiable_exclusions) === Number(primary.loo_unidentifiable_exclusions) && Number(analysisReproduction.support_at_10000) === Number(primary.support_at_10000) && Number(analysisReproduction.early_exit_count) === Number(primary.early_exit_count) && analysisReproduction.cohort_integrity_sha256 === cohortIntegrity.manifest_sha256 && analysisReproduction.exposure_integrity_sha256 === exposureIntegrity.manifest_sha256 && analysisReproduction.endpoint_decisions_sha256 === adjudication.decisions_sha256 && analysisReproduction.analysis_code_sha256 === analysisCodeEvidence.sha256 && typeof analysisReproduction.qualified_assessor === "string" && analysisReproduction.qualified_assessor.length > 0 && analysisReproduction.assessor_attested === true : notApplicable(analysisReproduction);
  const learning = object(diagnostics.learning_delta), generalization = object(diagnostics.generalization);
  const diagnosticPass = diagnostics.profile_version === "0.2-D1" && numeric(diagnostics.assistance_minutes_per_100_hours) && diagnostics.assistance_minutes_per_100_hours >= 0 && numeric(diagnostics.autonomous_availability) && diagnostics.autonomous_availability >= 0 && diagnostics.autonomous_availability <= 1 && numeric(diagnostics.human_burden_minutes_per_100_hours) && diagnostics.human_burden_minutes_per_100_hours >= 0 && timeBetweenPass(diagnostics.mean_time_between_human_rescue) && timeBetweenPass(diagnostics.mean_time_between_failure) && latencyPass(diagnostics.stop_latency_ms) && latencyPass(diagnostics.privacy_stop_latency_ms) && (diagnostics.self_recovery_rate === null || intervalPass(diagnostics.self_recovery_rate)) && (diagnostics.social_error_rate === null || intervalPass(diagnostics.social_error_rate)) && (diagnostics.initiative_precision === null || intervalPass(diagnostics.initiative_precision)) && (diagnostics.initiative_label_coverage === null || intervalPass(diagnostics.initiative_label_coverage)) && (diagnostics.learning_delta === null || (numeric(learning.estimate) && numeric(learning.lower) && numeric(learning.upper) && learning.lower <= learning.estimate && learning.estimate <= learning.upper && intervalPass(learning.early) && intervalPass(learning.late))) && (generalization.ratio === null || numeric(generalization.ratio)) && (generalization.familiar === null || intervalPass(generalization.familiar)) && (generalization.novel === null || intervalPass(generalization.novel)) && (diagnostics.reacquisition_rate === null || intervalPass(diagnostics.reacquisition_rate));
  const analysisPass = statisticsNeeded ? statisticsPass && diagnosticPass && analysisReproductionPass : diagnosticsNeeded ? notApplicable(primary) && diagnosticPass && analysisReproductionPass : notApplicable(primary) && notApplicable(diagnostics) && analysisReproductionPass;
  const safetyPass = safety.profile_version === "0.2-S1" && safety.gate_status === "passed" && digest(safety.manifest_sha256) && digest(safety.robot_description_sha256) && safety.robot_description_sha256 === robot.description_sha256 && digest(safety.policy_artifact_sha256) && safety.policy_artifact_sha256 === robot.policy_artifact_sha256 && Number(safety.participant_stop_trials) >= 30 && Number(safety.protective_stop_trials) >= 100 && Number(safety.privacy_stop_trials) >= 30 && Number(safety.remote_loss_trials) >= 30 && Number(safety.rollback_trials) >= 10 && safety.all_required_trials_passed === true && safety.context_coverage === 1 && safety.privileged_path_coverage === 1 && safety.unacceptable_residual_risks === 0 && safety.unresolved_material_incidents === 0 && safety.unresolved_high_severity_vulnerabilities === 0 && safety.l4_incidents === 0 && safety.safety_terminations === 0 && object(safety.incident_counts).L4 === safety.l4_incidents && digest(safety.assessment_sha256) && typeof safety.qualified_assessor === "string" && safety.qualified_assessor.length > 0 && safety.assessor_attested === true && Array.isArray(safety.applicable_rules) && safety.applicable_rules.length > 0 && evidence.some(item=>object(item).role === "safety_case") && evidence.some(item=>object(item).role === "incident_register");
  const telemetryEvidence = object(evidence.find(item=>object(item).role === "telemetry_authenticity_report"));
  const telemetryPass = telemetry.profile_version === "0.2-T1" && telemetry.schema_version === "0.2" && telemetry.conformance_status === "passed" && telemetry.signature_algorithm === "Ed25519" && telemetry.canonicalization === "RFC8785_JCS" && telemetry.signature_scope === "current_event_without_signature" && Number(telemetry.total_events) > 0 && Number(telemetry.verified_signatures) === Number(telemetry.total_events) && telemetry.invalid_signatures === 0 && telemetry.unknown_key_ids === 0 && telemetry.expired_key_events === 0 && telemetry.revoked_key_events === 0 && telemetry.hash_chain_mismatches === 0 && Number(telemetry.deployment_streams) > 0 && (target === "PREQUALIFIED" || Number(telemetry.deployment_streams) === Number(exposureIntegrity.environment_count)) && digest(telemetry.key_manifest_sha256) && /^https:\/\//.test(String(telemetry.key_manifest_uri)) && digest(telemetry.verification_report_sha256) && telemetryEvidence.uri === telemetry.verification_report_uri && telemetryEvidence.sha256 === telemetry.verification_report_sha256 && digest(telemetry.root_commitments_sha256);
  const fieldEvidenceNeeded = target !== "PREQUALIFIED";
  const operationsPass = fieldEvidenceNeeded ? safetyPass && telemetryPass : notApplicable(safety) && notApplicable(telemetry);
  const adjudicationPass = adjudication.completed === true && Number(adjudication.reviewer_count) >= 1 && digest(adjudication.decisions_sha256);
  const evidencePass = evidence.length >= (target === "PREQUALIFIED" ? 2 : 4) && evidence.every(item=>{ const record=object(item);return typeof record.uri === "string" && /^https:\/\//.test(record.uri) && digest(record.sha256); });
  const piiHits = prohibitedKeys(parsed);
  const [auditSeal, auditorCredential] = await Promise.all([verifyAuditSeal(parsed), verifyAuditorCredential(parsed)]);
  const auditPass = (fieldEvidenceNeeded ? adjudicationPass : notApplicable(adjudication)) && privacy.participant_data_included === false && privacy.redaction_reviewed === true && privacy.public_pack_contains_aggregate_data_only === true && piiHits.length === 0 && evidencePass && typeof audit.auditor_organization === "string" && audit.auditor_organization !== String(organization.sponsor) && typeof audit.independence_statement === "string" && audit.independence_statement.length >= 20 && auditSeal.status === "pass" && auditorCredential.status === "pass";

  const gates = [
    gate("G1", "IDENTITY + VERSION", identityPass, "Robot, policy artifact, support model, and description digest are bound.", "Complete robot identity and use non-placeholder SHA-256 description and policy-artifact digests."),
    gate("G2", "FROZEN PREREGISTRATION + PREFLIGHT", frozen && preflightPass, "Preregistration predates hour one and simulator-neutral preflight 0.2-P1 passes.", frozen ? "Provide a passing 0.2-P1 preflight with 8 families, 10,000 trials, full coverage, zero hard failures, reproducible replay, bound artifacts, assessor attestation, and a simulation report." : "Freeze the preregistration before hour one and replace placeholder digests."),
    gate("G3", target === "PREQUALIFIED" ? "TARGET THRESHOLD" : "TARGET + COHORT + CLOCK INTEGRITY", cohortPass, target === "PREQUALIFIED" ? `Evidence satisfies ${target}; cohort and exposure integrity are correctly not applicable.` : `Evidence satisfies ${target}, cohort profile 0.2-E1, and exposure-ledger profile 0.2-X1.`, !cohortIntegrityPass ? target === "PREQUALIFIED" ? "Mark cohort integrity not applicable before participant screening begins." : "Provide a passing 0.2-E1 cohort-integrity manifest aligned to the target and cohort count." : !exposureIntegrityPass ? target === "PREQUALIFIED" ? "Mark exposure integrity not applicable before real deployment begins." : "Provide a passing 0.2-X1 exposure ledger whose independently attested signed boundaries reproduce the cohort hours exactly." : cohortRule),
    gate("G4", "TARGET ANALYSIS + REPRODUCTION", analysisPass, statisticsNeeded ? "W, deterministic 95% CI, robustness, diagnostics, and analysis-reproduction profile 0.2-A1 are complete." : diagnosticsNeeded ? "The non-ranking diagnostic profile is complete; primary W and ranked analysis reproduction are explicitly not applicable." : "Primary W, field diagnostics, and ranked analysis reproduction are explicitly not applicable before real exposure.", statisticsNeeded ? analysisReproductionPass ? "Provide an identifiable 10K W, enclosing 95% CI, profile 0.2-R1 bounds, influence, tail support, ≥95% valid bootstrap support, 10,000 draws, and profile 0.2-D1 diagnostics." : "Provide a passing 0.2-A1 manifest that reproduces every primary and robustness field from the bound endpoint table and upstream evidence." : diagnosticsNeeded ? "Provide profile 0.2-D1 diagnostics and mark primary W plus analysis reproduction not applicable for this non-ranking target." : "Mark primary W, longitudinal field diagnostics, and analysis reproduction not applicable with reasons."),
    gate("G5", fieldEvidenceNeeded ? "SAFETY + CRYPTOGRAPHIC TELEMETRY" : "FIELD EVIDENCE APPLICABILITY", operationsPass, fieldEvidenceNeeded ? "Safety profile 0.2-S1 and telemetry-authenticity profile 0.2-T1 pass with every Ed25519 signature verified and L4=0." : "Field safety and telemetry are correctly marked not applicable for simulation-only prequalification.", fieldEvidenceNeeded ? "Provide a passing 0.2-S1 safety case plus a bound 0.2-T1 report with every event signature and hash-chain link verified against the frozen key manifest." : "PREQUALIFIED is simulation-only; mark field safety and field telemetry not applicable rather than fabricating field results."),
    gate("G6", "REGISTERED CRYPTOGRAPHIC AUDIT", auditPass, fieldEvidenceNeeded ? "Adjudication, privacy, evidence hashes, seal 0.2-V1, and issuer-signed auditor credential 0.2-V2 are verified." : "Simulation evidence, privacy, seal 0.2-V1, and issuer-signed auditor credential 0.2-V2 are verified.", piiHits.length ? `Remove participant-level fields: ${piiHits.join(", ")}.` : auditSeal.status !== "pass" ? `Repair the audit seal: ${auditSeal.errors.join(" ")}` : auditorCredential.status !== "pass" ? `Repair the auditor credential: ${auditorCredential.errors.join(" ")}` : fieldEvidenceNeeded ? "Complete adjudication, aggregate-only privacy checks, at least 4 HTTPS evidence objects, and a registered independently signed audit package." : "Mark adjudication not applicable, include at least 2 HTTPS evidence objects, and provide a registered independently signed audit package."),
  ];
  const allPass = gates.every(item=>item.status === "pass");
  const mode = parsed.submission_mode;
  const status = allPass ? mode === "official" ? "ready" : "test" : "not_ready";
  const projection = {
    submission_id: submission.submission_id, certification: target, robot: submission.public_label,
    rankable: target === "WANTED_WILD", wanted_score: numeric(primary.wanted_score) ? primary.wanted_score : null, ci95: numeric(primary.ci95_lower) && numeric(primary.ci95_upper) ? [primary.ci95_lower, primary.ci95_upper] : null, analysis_reproduced: analysisReproductionPass && statisticsNeeded, environments: cohort.independent_environments,
    resident_hours: cohort.total_resident_hours, clock_verified_hours: numeric(exposureIntegrity.total_resident_hours) ? exposureIntegrity.total_resident_hours : null, survival_at_10000: numeric(primary.survival_at_10000) ? primary.survival_at_10000 : null,
    assistance_minutes_per_100_hours: numeric(diagnostics.assistance_minutes_per_100_hours) ? diagnostics.assistance_minutes_per_100_hours : null,
    autonomous_availability: numeric(diagnostics.autonomous_availability) ? diagnostics.autonomous_availability : null,
    human_burden_minutes_per_100_hours: numeric(diagnostics.human_burden_minutes_per_100_hours) ? diagnostics.human_burden_minutes_per_100_hours : null,
    cohort_selection_rate: numeric(cohortIntegrity.selection_rate) ? cohortIntegrity.selection_rate : null,
    mean_time_between_human_rescue: notApplicable(diagnostics) ? null : diagnostics.mean_time_between_human_rescue,
    telemetry_signatures_verified: notApplicable(telemetry) ? null : telemetry.verified_signatures, audit_seal_verified: auditSeal.status === "pass", audit_manifest_sha256: auditSeal.manifestSha256, auditor_credential_verified: auditorCredential.status === "pass", auditor_credential_sha256: auditorCredential.credentialSha256,
    safety: notApplicable(safety) ? "not_applicable" : safety.gate_status, audit: allPass ? mode === "official" ? "ready_for_registry_review" : "synthetic_test_only" : "incomplete",
  };
  return { status, target, gates, errors, projection };
}
