export const SAMPLING_STOPPING_VERSION = "0.2-ST1";
export const STOPPING_TARGETS = ["PREQUALIFIED", "WANTED_LAB", "WANTED_WILD", "WANTED_10K"] as const;
export const MONITORING_PURPOSES = ["safety", "privacy", "operational_integrity", "data_completeness"] as const;
export type StoppingTarget = typeof STOPPING_TARGETS[number];

type MonitoringReview = { review_id:string; purpose:typeof MONITORING_PURPOSES[number]; reviewed_at:string; reviewer:string; independent_of_sponsor:true; primary_outcomes_visible:false; aggregate_w_visible:false; recommendation:"continue"|"pause_for_safety"|"stop_for_safety"; source_sha256:string };
type StoppingClaim = { planned_units:number; actual_units:number; operational_overshoot_units:number; planned_exposure_hours:number; actual_exposure_hours:number; monitoring_review_count:number; primary_outcome_access_events_before_cutoff:0; unscheduled_primary_analyses:0; result_informed_extensions:0; result_informed_early_stops:0; target_changes_after_activity:0; cutoff_changes_after_activity:0; excluded_activated_units:0; excluded_overshoot_units:0 };
export type SamplingStoppingInput = {
  profile_version:typeof SAMPLING_STOPPING_VERSION;
  target_certification:StoppingTarget;
  protocol:{
    closure_rule:"close_only_when_frozen_unit_target_exposure_floor_and_calendar_cutoff_are_satisfied";
    primary_outcome_access_rule:"locked_until_final_observation_cutoff";
    permitted_monitoring_purposes:typeof MONITORING_PURPOSES;
    efficacy_or_futility_stopping_permitted:false;
    outcome_adaptive_enrollment_permitted:false;
    outcome_adaptive_followup_permitted:false;
    overshoot_rule:"retain_every_activated_unit_and_all_observed_exposure";
    shortfall_rule:"no_certification_claim_until_every_frozen_minimum_is_met";
    emergency_rule:"safety_or_privacy_stop_remains_visible_and_never_becomes_a_favorable_cutoff";
  };
  study:{study_id:string;preregistration_sha256:string;claim_revision_id:string;plan_registered_at:string;first_benchmark_activity_at:string;submission_at:string};
  plan:{unit_type:"preflight_trial"|"independent_environment";planned_units:number;planned_exposure_hours:number;planned_cutoff_at:string;decision_rule_sha256:string;sampling_frame_sha256:string};
  execution:{actual_units:number;actual_exposure_hours:number;operational_overshoot_units:number;first_activity_at:string;enrollment_closed_at:string;observation_cutoff_at:string;first_primary_outcome_access_at:string;primary_outcome_access_events_before_cutoff:0;unscheduled_primary_analyses:0;result_informed_extensions:0;result_informed_early_stops:0;target_changes_after_activity:0;cutoff_changes_after_activity:0;all_activated_units_retained:true;all_overshoot_units_retained:true};
  monitoring_reviews:MonitoringReview[];
  claimed:StoppingClaim;
  evidence:{controlled_plan_uri:string;controlled_plan_sha256:string;outcome_access_log_uri:string;outcome_access_log_sha256:string;closure_report_uri:string;closure_report_sha256:string;public_history_uri:string;public_history_sha256:string};
  assessor:{name:string;organization:string;independent_of_sponsor:true;attested:true;signed_at:string};
};
export type StoppingGate={id:string;label:string;passed:boolean;detail:string};
export type SamplingStoppingResult={status:"passed"|"failed"|"invalid";errors:string[];gates:StoppingGate[];summary:(StoppingClaim&{profile_version:typeof SAMPLING_STOPPING_VERSION;status:"passed";target_certification:StoppingTarget;preregistration_sha256:string;claim_revision_id:string;planned_cutoff_at:string;observation_cutoff_at:string})|null};

const hash=(prefix:string)=>`${prefix}${"0123456789abcdef".repeat(4)}`.slice(0,64);
const digest=(value:unknown)=>typeof value==="string"&&/^[a-f0-9]{64}$/.test(value)&&!/^([a-f0-9])\1{63}$/.test(value);
const https=(value:unknown)=>typeof value==="string"&&/^https:\/\//.test(value);
const utc=(value:unknown)=>typeof value==="string"&&/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\dZ$/.test(value)&&Number.isFinite(Date.parse(value));
const nonnegative=(value:unknown)=>Number.isFinite(value)&&Number(value)>=0;
const integer=(value:unknown)=>Number.isInteger(value)&&Number(value)>=0;
const close=(a:number,b:number)=>Math.abs(a-b)<.000001;
const gate=(id:string,label:string,passed:boolean,ok:string,fix:string):StoppingGate=>({id,label,passed,detail:passed?ok:fix});
const targetMinimum=(target:StoppingTarget)=>target==="PREQUALIFIED"?{unit:"preflight_trial",units:10000,hours:0}:target==="WANTED_LAB"?{unit:"independent_environment",units:1,hours:100}:target==="WANTED_WILD"?{unit:"independent_environment",units:20,hours:10000}:{unit:"independent_environment",units:1,hours:10000};

export function reproduceStoppingClaims(input:Pick<SamplingStoppingInput,"plan"|"execution"|"monitoring_reviews">):StoppingClaim{return{
  planned_units:input.plan.planned_units,actual_units:input.execution.actual_units,operational_overshoot_units:input.execution.actual_units-input.plan.planned_units,planned_exposure_hours:input.plan.planned_exposure_hours,actual_exposure_hours:input.execution.actual_exposure_hours,monitoring_review_count:input.monitoring_reviews.length,
  primary_outcome_access_events_before_cutoff:input.execution.primary_outcome_access_events_before_cutoff,unscheduled_primary_analyses:input.execution.unscheduled_primary_analyses,result_informed_extensions:input.execution.result_informed_extensions,result_informed_early_stops:input.execution.result_informed_early_stops,target_changes_after_activity:input.execution.target_changes_after_activity,cutoff_changes_after_activity:input.execution.cutoff_changes_after_activity,excluded_activated_units:input.execution.all_activated_units_retained?0:1 as 0,excluded_overshoot_units:input.execution.all_overshoot_units_retained?0:Math.max(1,input.execution.operational_overshoot_units) as 0,
}};
const claimsMatch=(actual:StoppingClaim,claimed:StoppingClaim)=>(Object.keys(actual) as (keyof StoppingClaim)[]).every(key=>close(Number(actual[key]),Number(claimed?.[key])));

export function assessSamplingStopping(value:unknown):SamplingStoppingResult{
  if(!value||typeof value!=="object"||Array.isArray(value))return{status:"invalid",errors:["Sampling-and-stopping manifest must be one JSON object."],gates:[],summary:null};
  const input=value as Partial<SamplingStoppingInput>,errors:string[]=[];
  if(input.profile_version!==SAMPLING_STOPPING_VERSION)errors.push(`profile_version must be ${SAMPLING_STOPPING_VERSION}.`);
  if(!STOPPING_TARGETS.includes(input.target_certification as StoppingTarget))errors.push("target_certification is invalid.");
  if(!Array.isArray(input.monitoring_reviews))errors.push("monitoring_reviews must be an array, including an empty array when none occurred.");
  if(errors.length)return{status:"invalid",errors,gates:[],summary:null};
  const target=input.target_certification as StoppingTarget,protocol=input.protocol as SamplingStoppingInput["protocol"],study=input.study as SamplingStoppingInput["study"],plan=input.plan as SamplingStoppingInput["plan"],execution=input.execution as SamplingStoppingInput["execution"],reviews=input.monitoring_reviews as MonitoringReview[],claimed=input.claimed as StoppingClaim,evidence=input.evidence as SamplingStoppingInput["evidence"],assessor=input.assessor as SamplingStoppingInput["assessor"],minimum=targetMinimum(target);
  const protocolPass=protocol?.closure_rule==="close_only_when_frozen_unit_target_exposure_floor_and_calendar_cutoff_are_satisfied"&&protocol.primary_outcome_access_rule==="locked_until_final_observation_cutoff"&&JSON.stringify(protocol.permitted_monitoring_purposes)===JSON.stringify(MONITORING_PURPOSES)&&protocol.efficacy_or_futility_stopping_permitted===false&&protocol.outcome_adaptive_enrollment_permitted===false&&protocol.outcome_adaptive_followup_permitted===false&&protocol.overshoot_rule==="retain_every_activated_unit_and_all_observed_exposure"&&protocol.shortfall_rule==="no_certification_claim_until_every_frozen_minimum_is_met"&&protocol.emergency_rule==="safety_or_privacy_stop_remains_visible_and_never_becomes_a_favorable_cutoff";
  const studyPass=typeof study?.study_id==="string"&&study.study_id.length>0&&digest(study.preregistration_sha256)&&typeof study.claim_revision_id==="string"&&study.claim_revision_id.length>0&&utc(study.plan_registered_at)&&utc(study.first_benchmark_activity_at)&&utc(study.submission_at)&&Date.parse(study.plan_registered_at)<Date.parse(study.first_benchmark_activity_at)&&Date.parse(study.first_benchmark_activity_at)<Date.parse(study.submission_at);
  const planPass=plan?.unit_type===minimum.unit&&integer(plan.planned_units)&&plan.planned_units>=minimum.units&&nonnegative(plan.planned_exposure_hours)&&plan.planned_exposure_hours>=minimum.hours&&utc(plan.planned_cutoff_at)&&Date.parse(plan.planned_cutoff_at)>Date.parse(study.first_benchmark_activity_at)&&digest(plan.decision_rule_sha256)&&digest(plan.sampling_frame_sha256);
  const executionPass=integer(execution?.actual_units)&&execution.actual_units>=plan.planned_units&&nonnegative(execution.actual_exposure_hours)&&execution.actual_exposure_hours>=plan.planned_exposure_hours&&integer(execution.operational_overshoot_units)&&execution.operational_overshoot_units===execution.actual_units-plan.planned_units&&utc(execution.first_activity_at)&&execution.first_activity_at===study.first_benchmark_activity_at&&utc(execution.enrollment_closed_at)&&utc(execution.observation_cutoff_at)&&execution.observation_cutoff_at===plan.planned_cutoff_at&&Date.parse(execution.enrollment_closed_at)<=Date.parse(execution.observation_cutoff_at)&&utc(execution.first_primary_outcome_access_at)&&Date.parse(execution.first_primary_outcome_access_at)>=Date.parse(execution.observation_cutoff_at);
  const blindPass=execution.primary_outcome_access_events_before_cutoff===0&&execution.unscheduled_primary_analyses===0&&execution.result_informed_extensions===0&&execution.result_informed_early_stops===0&&execution.target_changes_after_activity===0&&execution.cutoff_changes_after_activity===0;
  const retentionPass=execution.all_activated_units_retained===true&&execution.all_overshoot_units_retained===true;
  const reviewIds=reviews.map(row=>row.review_id),reviewDigests=reviews.map(row=>row.source_sha256);
  const reviewsPass=reviews.every(row=>typeof row.review_id==="string"&&row.review_id.length>0&&MONITORING_PURPOSES.includes(row.purpose)&&utc(row.reviewed_at)&&Date.parse(row.reviewed_at)>=Date.parse(study.first_benchmark_activity_at)&&Date.parse(row.reviewed_at)<=Date.parse(execution.observation_cutoff_at)&&typeof row.reviewer==="string"&&row.reviewer.length>0&&row.independent_of_sponsor===true&&row.primary_outcomes_visible===false&&row.aggregate_w_visible===false&&["continue","pause_for_safety","stop_for_safety"].includes(row.recommendation)&&digest(row.source_sha256))&&new Set(reviewIds).size===reviewIds.length&&new Set(reviewDigests).size===reviewDigests.length;
  const reproduced=planPass&&executionPass?reproduceStoppingClaims({plan,execution,monitoring_reviews:reviews}):null;
  const claimPass=Boolean(reproduced&&claimsMatch(reproduced,claimed)&&reproduced.primary_outcome_access_events_before_cutoff===0&&reproduced.unscheduled_primary_analyses===0&&reproduced.result_informed_extensions===0&&reproduced.result_informed_early_stops===0&&reproduced.target_changes_after_activity===0&&reproduced.cutoff_changes_after_activity===0&&reproduced.excluded_activated_units===0&&reproduced.excluded_overshoot_units===0);
  const assurancePass=https(evidence?.controlled_plan_uri)&&digest(evidence.controlled_plan_sha256)&&https(evidence.outcome_access_log_uri)&&digest(evidence.outcome_access_log_sha256)&&https(evidence.closure_report_uri)&&digest(evidence.closure_report_sha256)&&https(evidence.public_history_uri)&&digest(evidence.public_history_sha256)&&typeof assessor?.name==="string"&&assessor.name.length>0&&typeof assessor.organization==="string"&&assessor.organization.length>0&&assessor.independent_of_sponsor===true&&assessor.attested===true&&utc(assessor.signed_at)&&Date.parse(assessor.signed_at)>=Date.parse(execution.first_primary_outcome_access_at)&&Date.parse(assessor.signed_at)<=Date.parse(study.submission_at);
  const gates=[
    gate("ST1","PROSPECTIVE DECISION RULE",protocolPass&&studyPass,"The closure, access, monitoring, overshoot, shortfall, and emergency rules were frozen before activity.","Use the exact 0.2-ST1 rules and bind them to a preregistered claim revision before any benchmark activity."),
    gate("ST2","SUFFICIENT FROZEN TARGET",planPass,"The unit target, exposure floor, calendar cutoff, decision rule, and sampling frame satisfy the target.",`Freeze at least ${minimum.units} ${minimum.unit}${minimum.units===1?"":"s"} and ${minimum.hours} resident hours where applicable.`),
    gate("ST3","OUTCOME-BLIND ACCRUAL",blindPass,"No primary outcome or aggregate W was accessed and no target or cutoff changed during accrual.","Remove all interim W access, unscheduled primary analyses, result-informed extensions or stops, and post-activity target or cutoff changes."),
    gate("ST4","DETERMINISTIC CLOSURE",executionPass,"Observed closure exactly follows the frozen unit, exposure, and calendar rule; primary access begins afterward.","Meet every frozen minimum, use the exact preregistered cutoff, and keep primary outcomes locked until closure."),
    gate("ST5","OVERSHOOT RETENTION",retentionPass,"Every activated unit and all operational overshoot remain in the evidence and analysis denominators.","Restore every activated or overshoot unit and all of its observed exposure."),
    gate("ST6","SEPARATED MONITORING",reviewsPass,"Every interim review is unique, independent, purpose-limited, and blind to primary outcomes and W.","Restrict monitoring to safety, privacy, operations, or completeness and bind each independent blind review to source evidence."),
    gate("ST7","REPRODUCED INDEPENDENT CLOSURE",claimPass&&assurancePass,"The public closure history reproduces exactly and carries independent attestation.","Correct all public counts and bind the controlled plan, access log, closure report, public history, and independent attestation."),
  ];
  const status=gates.every(row=>row.passed)?"passed":"failed";
  return{status,errors:[],gates,summary:reproduced?{profile_version:SAMPLING_STOPPING_VERSION,status:"passed",target_certification:target,preregistration_sha256:study.preregistration_sha256,claim_revision_id:study.claim_revision_id,planned_cutoff_at:plan.planned_cutoff_at,observation_cutoff_at:execution.observation_cutoff_at,...reproduced}:null};
}

const review=(id:string,purpose:MonitoringReview["purpose"],day:string):MonitoringReview=>({review_id:id,purpose,reviewed_at:`2026-${day}T12:00:00Z`,reviewer:"Independent Monitoring Statistician",independent_of_sponsor:true,primary_outcomes_visible:false,aggregate_w_visible:false,recommendation:"continue",source_sha256:hash(id==="MON-001"?"91":"92")});
export function samplingStoppingTemplateFor(target:StoppingTarget):SamplingStoppingInput{
  const config=target==="PREQUALIFIED"?{unit:"preflight_trial" as const,units:10000,hours:0,first:"2025-12-15T00:00:00Z",closed:"2025-12-20T00:00:00Z",cutoff:"2025-12-20T00:00:00Z",access:"2025-12-21T00:00:00Z",reviews:[]}:target==="WANTED_LAB"?{unit:"independent_environment" as const,units:1,hours:100,first:"2026-01-02T00:00:00Z",closed:"2026-01-02T01:00:00Z",cutoff:"2026-01-06T04:00:00Z",access:"2026-01-06T05:00:00Z",reviews:[review("MON-001","safety","01-04")]}:target==="WANTED_WILD"?{unit:"independent_environment" as const,units:24,hours:120000,first:"2026-01-02T00:00:00Z",closed:"2026-01-31T00:00:00Z",cutoff:"2026-08-28T17:00:00Z",access:"2026-08-28T17:15:00Z",reviews:[review("MON-001","safety","03-01"),review("MON-002","data_completeness","06-01")]}:{unit:"independent_environment" as const,units:1,hours:10000,first:"2026-01-02T00:00:00Z",closed:"2026-01-02T01:00:00Z",cutoff:"2026-08-28T17:00:00Z",access:"2026-08-28T17:15:00Z",reviews:[review("MON-001","safety","03-01"),review("MON-002","operational_integrity","06-01")]};
  const plan={unit_type:config.unit,planned_units:config.units,planned_exposure_hours:config.hours,planned_cutoff_at:config.cutoff,decision_rule_sha256:hash("93"),sampling_frame_sha256:hash("94")};
  const execution={actual_units:config.units,actual_exposure_hours:config.hours,operational_overshoot_units:0,first_activity_at:config.first,enrollment_closed_at:config.closed,observation_cutoff_at:config.cutoff,first_primary_outcome_access_at:config.access,primary_outcome_access_events_before_cutoff:0 as const,unscheduled_primary_analyses:0 as const,result_informed_extensions:0 as const,result_informed_early_stops:0 as const,target_changes_after_activity:0 as const,cutoff_changes_after_activity:0 as const,all_activated_units_retained:true as const,all_overshoot_units_retained:true as const};
  const claimed=reproduceStoppingClaims({plan,execution,monitoring_reviews:config.reviews});
  return{profile_version:SAMPLING_STOPPING_VERSION,target_certification:target,protocol:{closure_rule:"close_only_when_frozen_unit_target_exposure_floor_and_calendar_cutoff_are_satisfied",primary_outcome_access_rule:"locked_until_final_observation_cutoff",permitted_monitoring_purposes:MONITORING_PURPOSES,efficacy_or_futility_stopping_permitted:false,outcome_adaptive_enrollment_permitted:false,outcome_adaptive_followup_permitted:false,overshoot_rule:"retain_every_activated_unit_and_all_observed_exposure",shortfall_rule:"no_certification_claim_until_every_frozen_minimum_is_met",emergency_rule:"safety_or_privacy_stop_remains_visible_and_never_becomes_a_favorable_cutoff"},study:{study_id:"SYNTHETIC-STUDY-001",preregistration_sha256:hash("b"),claim_revision_id:"claim-r1",plan_registered_at:"2025-12-01T00:00:00Z",first_benchmark_activity_at:config.first,submission_at:"2026-08-28T19:00:00Z"},plan,execution,monitoring_reviews:config.reviews,claimed,evidence:{controlled_plan_uri:"https://example.org/wanted-sampling-stop-plan.json",controlled_plan_sha256:hash("95"),outcome_access_log_uri:"https://example.org/wanted-outcome-access-log.json",outcome_access_log_sha256:hash("96"),closure_report_uri:"https://example.org/wanted-closure-report.json",closure_report_sha256:hash("97"),public_history_uri:"https://example.org/wanted-sampling-stop-history.json",public_history_sha256:hash("98")},assessor:{name:"Synthetic Stopping Assessor",organization:"Independent Example Assurance",independent_of_sponsor:true,attested:true,signed_at:"2026-08-28T18:30:00Z"}};
}
export const samplingStoppingTemplate=samplingStoppingTemplateFor("WANTED_WILD");

const d={type:"string",pattern:"^[a-f0-9]{64}$"},uri={type:"string",format:"uri",pattern:"^https://"},date={type:"string",format:"date-time"},n={type:"number",minimum:0},i={type:"integer",minimum:0};
export const samplingStoppingSchema={"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://embodied-arena.chrishongap.chatgpt.site/wanted-10k/sampling-stopping.schema.json",title:"WANTED Sampling and Stopping Integrity Manifest",type:"object",additionalProperties:false,required:["profile_version","target_certification","protocol","study","plan","execution","monitoring_reviews","claimed","evidence","assessor"],properties:{
  profile_version:{const:SAMPLING_STOPPING_VERSION},target_certification:{enum:STOPPING_TARGETS},
  protocol:{type:"object",additionalProperties:false,required:["closure_rule","primary_outcome_access_rule","permitted_monitoring_purposes","efficacy_or_futility_stopping_permitted","outcome_adaptive_enrollment_permitted","outcome_adaptive_followup_permitted","overshoot_rule","shortfall_rule","emergency_rule"],properties:{closure_rule:{const:"close_only_when_frozen_unit_target_exposure_floor_and_calendar_cutoff_are_satisfied"},primary_outcome_access_rule:{const:"locked_until_final_observation_cutoff"},permitted_monitoring_purposes:{const:MONITORING_PURPOSES},efficacy_or_futility_stopping_permitted:{const:false},outcome_adaptive_enrollment_permitted:{const:false},outcome_adaptive_followup_permitted:{const:false},overshoot_rule:{const:"retain_every_activated_unit_and_all_observed_exposure"},shortfall_rule:{const:"no_certification_claim_until_every_frozen_minimum_is_met"},emergency_rule:{const:"safety_or_privacy_stop_remains_visible_and_never_becomes_a_favorable_cutoff"}}},
  study:{type:"object",additionalProperties:false,required:["study_id","preregistration_sha256","claim_revision_id","plan_registered_at","first_benchmark_activity_at","submission_at"],properties:{study_id:{type:"string",minLength:1},preregistration_sha256:d,claim_revision_id:{type:"string",minLength:1},plan_registered_at:date,first_benchmark_activity_at:date,submission_at:date}},
  plan:{type:"object",additionalProperties:false,required:["unit_type","planned_units","planned_exposure_hours","planned_cutoff_at","decision_rule_sha256","sampling_frame_sha256"],properties:{unit_type:{enum:["preflight_trial","independent_environment"]},planned_units:i,planned_exposure_hours:n,planned_cutoff_at:date,decision_rule_sha256:d,sampling_frame_sha256:d}},
  execution:{type:"object",additionalProperties:false,required:["actual_units","actual_exposure_hours","operational_overshoot_units","first_activity_at","enrollment_closed_at","observation_cutoff_at","first_primary_outcome_access_at","primary_outcome_access_events_before_cutoff","unscheduled_primary_analyses","result_informed_extensions","result_informed_early_stops","target_changes_after_activity","cutoff_changes_after_activity","all_activated_units_retained","all_overshoot_units_retained"],properties:{actual_units:i,actual_exposure_hours:n,operational_overshoot_units:i,first_activity_at:date,enrollment_closed_at:date,observation_cutoff_at:date,first_primary_outcome_access_at:date,primary_outcome_access_events_before_cutoff:{const:0},unscheduled_primary_analyses:{const:0},result_informed_extensions:{const:0},result_informed_early_stops:{const:0},target_changes_after_activity:{const:0},cutoff_changes_after_activity:{const:0},all_activated_units_retained:{const:true},all_overshoot_units_retained:{const:true}}},
  monitoring_reviews:{type:"array",items:{type:"object",additionalProperties:false,required:["review_id","purpose","reviewed_at","reviewer","independent_of_sponsor","primary_outcomes_visible","aggregate_w_visible","recommendation","source_sha256"],properties:{review_id:{type:"string",minLength:1},purpose:{enum:MONITORING_PURPOSES},reviewed_at:date,reviewer:{type:"string",minLength:1},independent_of_sponsor:{const:true},primary_outcomes_visible:{const:false},aggregate_w_visible:{const:false},recommendation:{enum:["continue","pause_for_safety","stop_for_safety"]},source_sha256:d}}},
  claimed:{type:"object",additionalProperties:false,required:["planned_units","actual_units","operational_overshoot_units","planned_exposure_hours","actual_exposure_hours","monitoring_review_count","primary_outcome_access_events_before_cutoff","unscheduled_primary_analyses","result_informed_extensions","result_informed_early_stops","target_changes_after_activity","cutoff_changes_after_activity","excluded_activated_units","excluded_overshoot_units"],properties:{planned_units:i,actual_units:i,operational_overshoot_units:i,planned_exposure_hours:n,actual_exposure_hours:n,monitoring_review_count:i,primary_outcome_access_events_before_cutoff:{const:0},unscheduled_primary_analyses:{const:0},result_informed_extensions:{const:0},result_informed_early_stops:{const:0},target_changes_after_activity:{const:0},cutoff_changes_after_activity:{const:0},excluded_activated_units:{const:0},excluded_overshoot_units:{const:0}}},
  evidence:{type:"object",additionalProperties:false,required:["controlled_plan_uri","controlled_plan_sha256","outcome_access_log_uri","outcome_access_log_sha256","closure_report_uri","closure_report_sha256","public_history_uri","public_history_sha256"],properties:{controlled_plan_uri:uri,controlled_plan_sha256:d,outcome_access_log_uri:uri,outcome_access_log_sha256:d,closure_report_uri:uri,closure_report_sha256:d,public_history_uri:uri,public_history_sha256:d}},
  assessor:{type:"object",additionalProperties:false,required:["name","organization","independent_of_sponsor","attested","signed_at"],properties:{name:{type:"string",minLength:1},organization:{type:"string",minLength:1},independent_of_sponsor:{const:true},attested:{const:true},signed_at:date}}
}} as const;

export const samplingStoppingContract={name:"WANTED Prospective Sampling and Stopping Integrity Profile",version:SAMPLING_STOPPING_VERSION,applies_to:STOPPING_TARGETS,certification_effect:"prospective_execution_integrity_gate",ranking_effect:"eligibility_only_never_score_or_tiebreaker",primary_outcome_access_before_cutoff:false,efficacy_or_futility_stopping_permitted:false,outcome_adaptive_enrollment_permitted:false,permitted_interim_purposes:MONITORING_PURPOSES,closure_identity:"actual_units=planned_units+operational_overshoot_units",target_minima:{PREQUALIFIED:{units:10000,unit_type:"preflight_trial",exposure_hours:0},WANTED_LAB:{units:1,unit_type:"independent_environment",exposure_hours:100},WANTED_WILD:{units:20,unit_type:"independent_environment",exposure_hours:10000},WANTED_10K:{units:1,unit_type:"independent_environment",exposure_hours:10000}},hard_failures:["late_plan","insufficient_frozen_target","primary_outcome_access_before_cutoff","unscheduled_primary_analysis","result_informed_extension","result_informed_early_stop","post_activity_target_change","post_activity_cutoff_change","excluded_activated_unit","excluded_overshoot_unit","unblinded_monitoring_review","unbound_closure_history"],interpretation:"Passing proves result-independent sampling and closure under a frozen target, cutoff, and access boundary. It does not claim statistical power, population representativeness, regulatory conformity, or that safety monitoring should be delayed."} as const;
