import type { Metadata } from "next";
import { CompanyPage, CompanyEmail } from "../components/CompanyPage";

export const metadata: Metadata = { title: "Privacy Policy — Robot Router", description: "How hfxaa llc handles information on Robot Router and Embodied Arena, including browser tools, analytics, and contact requests.", alternates: { canonical: "/privacy" } };

export default function PrivacyPage() {
  return <CompanyPage title="Privacy Policy" intro="This policy explains how hfxaa llc handles information when you use Robot Router and Embodied Arena at getrobotrouter.com." updated>
    <div className="companyCallout"><h2>Benchmark Studio</h2><p>You can edit and export a benchmark in your browser without saving it to the server. When you choose to save, we store your benchmark titles, descriptions, methodology, metric definitions, results, chart settings, record versions, and timestamps in a private workspace. Benchmarks are not automatically published. API keys you create let your agents manage that workspace’s benchmarks.</p><p>Workspaces use a recovery key, a seven-day browser session cookie named rr_workspace, and separately revocable agent keys. The server stores cryptographic hashes of these keys. We also keep agent-key labels and creation times and short-lived request counters to limit abuse. We do not ask for your name or email to create a workspace. Studio and its API are excluded from first-party usage analytics.</p><p>Saved benchmarks remain until you delete them or the service is discontinued. You can export individual records, delete saved benchmarks, revoke agent keys, or delete the whole workspace in Studio. Deletion removes active workspace records and credentials; hosting-provider backups may retain earlier copies according to their backup schedule. Clearing browser cookies does not delete saved benchmarks. Keep your recovery key safe: losing it can prevent access, and anyone who holds it can open the workspace. Do not include sensitive personal information in benchmark records.</p></div>
    <h2>1. Who operates this website</h2><p>hfxaa llc operates Robot Router and its Embodied Arena experience. For privacy questions or requests, email <CompanyEmail />. This policy covers this website; third-party websites and services have their own policies.</p>
    <h2>2. Information handled by the website</h2><h3>Information you provide</h3><p>If you email us, we receive your email address, message, and any information you choose to include. We use that information to respond, investigate issues, and maintain relevant correspondence.</p><p>Where the optional contact-profile feature is available, sign-in supplies an account identifier and email. Saving a profile records those details, an optional phone number, and consent and save timestamps. See the <a href="/account/privacy">contact-data notice</a> for feature-specific details. The current DigitalOcean deployment does not provide the hosted sign-in and profile database required to save these profiles.</p><h3>Connection and security information</h3><p>Delivering the website requires connection information such as your IP address, requested URL, browser information, and request time. Hosting, content-delivery, and security providers may process this information and use cookies to deliver the site, prevent abuse, and maintain service logs.</p><h3>Usage information and browser storage</h3><p>The site can send first-party usage events such as page views, heartbeats, filter changes, and tool interactions with a randomly generated session identifier. This identifier is not your name or email. Browser storage can also hold preferences, analytics choices, and experiment assignments. The current DigitalOcean deployment has no application analytics database: its analytics endpoint reports storage as unavailable. Infrastructure logs may still be maintained separately.</p>
    <h2>3. Files and local tools</h2><p>The URDF scanner and tools explicitly marked as local process selected files in your browser. Their file contents are not uploaded by those tools. A tool may send an interaction event, such as a scan starting or finishing, unless analytics is disabled. Downloaded reports and browser-stored preferences remain under your control.</p><p>Use only files you are authorized to analyze. A feature that sends information elsewhere should be assessed separately from the local tools.</p>
    <h2>4. How information is used and disclosed</h2><p>Information is used to operate and secure the site, provide requested features, respond to messages, troubleshoot problems, and understand usage where analytics storage is enabled. Service providers may process information for hosting, security, account functionality where available, and email delivery. The current website does not include advertising pixels or a feature that sells contact-profile information.</p><p>Information may also be disclosed when reasonably necessary to comply with applicable law, respond to valid legal process, or protect the rights, safety, and security of people and the service. Public benchmark material you choose to submit should contain only information you are authorized to share.</p>
    <h2>5. Your choices</h2><p>You can use the <a href="/experiments">analytics privacy control</a> to disable the site’s first-party analytics for the current browser. The analytics code also honors Global Privacy Control and Do Not Track signals. This does not disable the connection processing necessary to deliver and secure the website.</p><p>You can clear cookies and site storage in your browser. Doing so removes saved preferences and may reset your analytics choice. Where contact profiles are supported, you can edit or delete your profile through <a href="/account">your account</a>.</p>
    <h2>6. Retention and security</h2><p>We retain correspondence as needed to respond to requests, operate the service, resolve disputes, and meet applicable obligations. The DigitalOcean version does not retain events in an application analytics database. On deployments where the analytics database is enabled, application code applies a rolling 35-day raw-event retention window. Provider logs and backups follow their own retention settings.</p><p>We use available access controls and encrypted website connections. No internet service can guarantee absolute security. Please do not send sensitive participant records, passwords, or private keys by email.</p>
    <h2>7. Privacy requests</h2><p>Depending on your location and the law that applies, you may have rights to access, correct, delete, or obtain a copy of personal information, or to object to or limit certain processing. Email <CompanyEmail /> to make a request. We may ask for information reasonably needed to verify the request and locate the relevant records. Applicable exceptions and verification requirements may limit what we can provide.</p><p>Where applicable, you may also raise a concern with your local privacy authority. Service providers may process information outside your country.</p>
    <h2>8. Children</h2><p>This site is intended for a general professional and research audience and is not directed to children under 13. If you believe a child has sent us personal information, contact <CompanyEmail /> so we can review and address it.</p>
    <h2>9. Policy changes</h2><p>We may update this policy as the service changes. The effective date above identifies this version. Where required, we will provide additional notice or obtain consent before materially changing how personal information is used.</p>
  </CompanyPage>;
}
