import type { Metadata } from "next";
import { SiteNav } from "../../components/SiteNav";
import { DiagnosticLab } from "./DiagnosticLab";

export const metadata: Metadata = { title: "Longitudinal Diagnostics — WANTED-10K", description: "Canonical non-ranking measures for robot burden, reliability, safety response, learning, initiative, and generalization.", alternates: { canonical: "/wanted-10k/diagnostics" } };

const principles = [
  ["DENOMINATORS STAY VISIBLE", "Every rate travels with exposure, trials, events, labels, and missingness."],
  ["ZERO IS NOT INFINITY", "No rescue or failure produces a right-censored lower bound: at least the observed exposure."],
  ["TAILS MATTER", "Stop and privacy response report N, P50, P95, P99, and maximum—not only an average."],
  ["NO SECOND SCORE", "Diagnostics explain retention. They are never combined into a weighted index or used to offset safety."],
];

export default function DiagnosticsPage() {
  return <main className="diagnosticsPage"><SiteNav />
    <section className="diagHero shell"><span className="eyebrow"><i className="liveDot"/> LONGITUDINAL DIAGNOSTIC PROFILE · 0.2-D1</span><h1>Explain the score.<br/><em>Never dilute it.</em></h1><p>W says how long people voluntarily retain the robot. This profile shows what life with it cost: hidden assistance, owner labor, failures, recovery, interruptions, learning, privacy response, and whether proactive behavior was actually welcome.</p><div className="diagActions"><a className="primary" href="#lab">Calculate a profile <span>↓</span></a><a className="secondary" href="/wanted-10k/diagnostics.json">Open contract</a><a className="secondary" href="/wanted-10k/audit">Prepare audit pack</a></div></section>
    <section className="diagPrinciples"><div className="shell"><div className="sectionHead wantedHead"><div><span className="kicker">01 / REPORTING RULES</span><h2>One retention score.<br/><em>Many honest explanations.</em></h2></div><p>A diagnostic is only useful when teams cannot improve it by hiding downtime, dropping unresolved labels, or redefining the denominator after seeing results.</p></div><div className="principleGrid">{principles.map(([title,copy],index)=><article key={title}><span>0{index+1}</span><b>{title}</b><p>{copy}</p></article>)}</div></div></section>
    <section className="formulaSection"><div className="shell"><div className="sectionHead wantedHead"><div><span className="kicker">02 / CANONICAL FORMULAS</span><h2>Operational burden.<br/><em>Behavioral adaptation.</em></h2></div><p>Each formula is computed per environment first. Official cohort uncertainty resamples independent environments, not individual robot actions.</p></div><div className="formulaGrid"><article><span>I<sub>100</sub></span><b>100 × assistance minutes / resident hours</b><p>All remote guidance, teleoperation, rescue, and research assistance.</p></article><article><span>H<sub>100</sub></span><b>100 × owner-labor minutes / resident hours</b><p>Configuration, teaching, maintenance, cleanup, and rescue imposed on the user.</p></article><article><span>MTBHR</span><b>resident hours / human rescues</b><p>With zero rescues, report “≥ observed resident hours,” never infinity.</p></article><article><span>SER</span><b>rejected proactive actions / all proactive actions</b><p>Unresolved actions stay in the denominator and label coverage is published.</p></article><article><span>ΔL</span><b>late matched performance − early matched performance</b><p>Windows and task-matching rules are frozen before hour one.</p></article><article><span>G</span><b>novel success rate / familiar success rate</b><p>Publish both components; suppress the ratio if familiar performance is zero.</p></article></div></div></section>
    <section id="lab" className="diagLabSection"><div className="shell"><div className="sectionHead wantedHead"><div><span className="kicker">03 / LOCAL PROFILE LAB</span><h2>Paste counters.<br/><em>Export evidence.</em></h2></div><p>The synthetic example demonstrates the aggregate input format. Calculations remain in the browser and contain no participant-level records.</p></div><DiagnosticLab /></div></section>
    <section className="diagBoundary"><div className="shell"><div className="sectionHead wantedHead"><div><span className="kicker">04 / INTERPRETATION BOUNDARY</span><h2>Context travels<br/><em>with every metric.</em></h2></div><p>Task mix, embodiment, population, environment, support model, and robot version affect every diagnostic. WANTED requires disclosure instead of pretending those differences disappear.</p></div><div className="boundaryRows"><div><b>PRIMARY</b><span>W + 95% CI + S(10K)</span><p>Only voluntary retention determines rank.</p></div><div><b>CONSTRAINT</b><span>Safety gates + L0–L4 register</span><p>Safety cannot be traded for usefulness.</p></div><div><b>DIAGNOSTIC</b><span>Burden · reliability · behavior · learning</span><p>Always contextual and non-ranking.</p></div></div></div></section>
    <footer className="wantedFooter"><div className="shell"><div className="brand"><span className="brandMark">EA</span><span>EMBODIED <b>ARENA</b> / DIAGNOSTICS</span></div><p>The canonical explanation layer beneath a WANTED Score.</p><a href="/wanted-10k">BACK TO BENCHMARK →</a></div></footer>
  </main>;
}
