import type { Metadata } from "next";
import { CompanyPage, CompanyEmail } from "../components/CompanyPage";

export const metadata: Metadata = { title: "Terms and Conditions — Robot Router", description: "Terms for using Robot Router and Embodied Arena, operated by hfxaa llc.", alternates: { canonical: "/terms" } };

export default function TermsPage() {
  return <CompanyPage title="Terms and Conditions" intro="These terms govern your use of Robot Router and Embodied Arena at getrobotrouter.com, operated by hfxaa llc." updated>
    <h2>1. Using the website</h2><p>By using this website, you agree to these terms to the extent permitted by applicable law. If you do not agree, stop using it. You may use the website for lawful research, comparison, and evaluation, subject to these terms and any separate license displayed with a resource.</p>
    <h2>2. Information and example results</h2><p>The site provides robotics information, evaluation protocols, local tools, model profiles, and research explainers. Content may be incomplete or change. Scores labeled illustrative, synthetic, sample, or example are demonstrations, not measured benchmark results.</p><p>A listing does not establish independent verification, endorsement, safety certification, or suitability for a deployment. Comparisons may involve different hardware, training data, tasks, and evaluation methods. Independently audited results are subject to the separate rules of the relevant registry.</p>
    <h2>3. Robot operation and safety</h2><p>You are responsible for assessing any model, hardware, software, or method before using it. Website results and URDF reports do not replace engineering review, manufacturer instructions, safety testing, or compliance with applicable requirements. The website does not operate your robots or authorize physical actions.</p>
    <h2>4. Acceptable use</h2><p>Do not interfere with the service, access accounts or data without authorization, distribute malicious code, evade access restrictions, misrepresent evidence, or submit content that infringes another person’s rights. Use APIs and downloadable tools within their documented limits. You are responsible for having permission to analyze files and share information.</p>
    <h2>5. Accounts and submissions</h2><p>Account features, where available, are optional. Provide accurate information and protect your credentials. Do not submit passwords, private keys, confidential telemetry, or identifiable participant records through public submission channels.</p><p>You retain your rights in material you provide. By sending material for review or publication, you permit hfxaa llc to process it for that stated purpose. Any public dataset or code contribution may have additional license terms presented with its submission workflow. Submission does not guarantee publication, ranking, certification, or acceptance.</p>
    <h2>6. Intellectual property and third-party resources</h2><p>Site content belongs to hfxaa llc or its respective owners. Third-party names and trademarks identify their owners and do not imply an affiliation. Open-source software, datasets, and downloadable resources remain subject to their stated licenses. Preserve attribution and license notices when required.</p><p>Links to third-party resources are provided for reference. Their content, availability, services, and privacy practices are governed by those providers.</p>
    <h2>7. Availability and limitations</h2><p>To the extent permitted by law, the website and its materials are provided “as is” and “as available,” without warranties of accuracy, uninterrupted availability, fitness for a particular purpose, or freedom from errors. We may update, suspend, or remove features, including to address security or misuse.</p><p>To the extent permitted by applicable law, hfxaa llc is not liable for indirect or consequential loss arising from use of or inability to use the site, including loss of profits or data. Nothing in these terms excludes liability or consumer rights that cannot legally be excluded.</p>
    <h2>8. Privacy</h2><p>Our <a href="/privacy">Privacy Policy</a> explains information handling and privacy choices. Feature-specific notices may supplement it.</p>
    <h2>9. Changes and contact</h2><p>We may update these terms. Changes will be posted here with an updated effective date and additional notice where required. Changes apply prospectively, subject to applicable law. If any provision is unenforceable, the remaining provisions continue to apply to the extent permitted by law.</p><p>For questions or concerns about these terms, contact hfxaa llc at <CompanyEmail />.</p>
  </CompanyPage>;
}
