"use client";
import { useState } from "react";
import { assessHumanMeasures, humanMeasuresTemplateFor, type HumanMeasureResult } from "./profile.ts";

const example=humanMeasuresTemplateFor("WANTED_10K");
const initial:HumanMeasureResult={status:"invalid",errors:[],gates:[],summary:null};
const metric=(value:number|null,digits=1)=>value===null?"NOT OBSERVED":value.toFixed(digits);

export function HumanMeasuresLab(){
  const [input,setInput]=useState(JSON.stringify(example,null,2));
  const [result,setResult]=useState<HumanMeasureResult>(initial);
  const run=()=>{try{setResult(assessHumanMeasures(JSON.parse(input)))}catch(error){setResult({status:"invalid",errors:[error instanceof Error?error.message:"Invalid JSON."],gates:[],summary:null})}};
  const load=()=>{setInput(JSON.stringify(example,null,2));setResult(assessHumanMeasures(example))};
  return <div className="humanLab"><header><div><span>LOCAL HUMAN-MEASURES REPRODUCER</span><b>PROFILE / 0.2-H1</b></div><div><button onClick={load}>LOAD SYNTHETIC EXAMPLE</button><button className="runHuman" onClick={run}>VERIFY -&gt;</button></div></header><div className="humanWorkspace"><div className="humanEditor"><label htmlFor="human-input">SCHEDULE + CONTROLLED RESPONSE REGISTER</label><textarea id="human-input" spellCheck={false} value={input} onChange={event=>setInput(event.target.value)}/><footer><a href="/wanted-10k/human-measures.schema.json">MANIFEST SCHEMA</a><span>Runs locally. Public outputs remain aggregate-only.</span></footer></div><div className="humanOutput"><div className={`humanStatus ${result.status}`}><span>COLLECTION INTEGRITY</span><b>{result.status.toUpperCase()}</b><small>{result.errors[0]||(result.status==="passed"?"All seven human-measures gates pass.":"One or more hard gates failed.")}</small></div>{result.summary&&<><div className="humanMetrics"><article><span>COMPLETION</span><b>{(result.summary.completion_rate*100).toFixed(1)}%</b></article><article><span>KEEP</span><b>{result.summary.keep_rate===null?"N/A":`${(result.summary.keep_rate*100).toFixed(1)}%`}</b></article><article><span>VALUE MEDIAN</span><b>{metric(result.summary.value_median)}</b></article><article><span>TRUST MEDIAN</span><b>{metric(result.summary.trust_median)}</b></article></div><div className="phaseTable"><header><span>PHASE</span><span>N</span><span>KEEP</span><span>VALUE</span><span>BURDEN</span><span>TRUST</span></header>{result.summary.phase_profiles.map(phase=><div key={phase.phase}><b>{phase.phase.replace("_"," ")}</b><span>{phase.completed}/{phase.due}</span><span>{phase.keep_rate===null?"—":`${(phase.keep_rate*100).toFixed(0)}%`}</span><span>{metric(phase.value_median)}</span><span>{metric(phase.burden_median)}</span><span>{metric(phase.trust_median)}</span></div>)}</div></>}<div className="humanGates">{result.gates.map(item=><article className={item.passed?"pass":"fail"} key={item.id}><span>{item.id}</span><div><b>{item.label}</b><p>{item.detail}</p></div><i>{item.passed?"PASS":"FAIL"}</i></article>)}</div></div></div><aside><b>RESPONSE != RETENTION</b><p>These answers explain coexistence. Only permanent voluntary rejection changes W; human measures never change rank or offset safety.</p></aside></div>;
}
