"use client";
import { useState } from "react";
import { assessCohortIntegrity, cohortIntegrityTemplate, type CohortIntegrityResult } from "./profile";

const initial = assessCohortIntegrity(cohortIntegrityTemplate);
export function CohortIntegrityLab(){
  const [input,setInput]=useState(JSON.stringify(cohortIntegrityTemplate,null,2));
  const [result,setResult]=useState<CohortIntegrityResult>(initial);
  const load=()=>{const text=JSON.stringify(cohortIntegrityTemplate,null,2);setInput(text);setResult(assessCohortIntegrity(cohortIntegrityTemplate))};
  const run=()=>{try{setResult(assessCohortIntegrity(JSON.parse(input)))}catch(error){setResult({status:"invalid",errors:[error instanceof Error?error.message:"Invalid JSON."],gates:[],summary:null})}};
  const exportResult=()=>{if(!result.summary)return;const payload={benchmark:"WANTED-10K",cohort_integrity_profile_version:"0.2-E1",generated_at:new Date().toISOString(),status:result.status,gates:result.gates,...result.summary,note:"Local arithmetic and topology check only. Source linkage evidence and recruitment facts require independent verification."};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));const anchor=document.createElement("a");anchor.href=url;anchor.download="wanted-cohort-integrity-result.json";anchor.click();URL.revokeObjectURL(url)};
  return <section className="cohortLab"><header><div><span>LOCAL COHORT-INTEGRITY EVALUATOR</span><b>PROFILE / 0.2-E1</b></div><div><button onClick={load}>LOAD SYNTHETIC EXAMPLE</button><button className="runCohort" onClick={run}>ASSESS -&gt;</button></div></header><div className="cohortWorkspace"><div className="cohortEditor"><label htmlFor="cohort-input">AGGREGATE SELECTION + LINKAGE MANIFEST</label><textarea id="cohort-input" spellCheck={false} value={input} onChange={event=>setInput(event.target.value)}/><footer><a href="/wanted-10k/cohort-integrity.schema.json">MANIFEST SCHEMA</a><span>Runs locally. No participant data is uploaded.</span></footer></div><div className="cohortOutput"><div className={`cohortStatus ${result.status}`}><span>COHORT INTEGRITY</span><b>{result.status.toUpperCase()}</b><small>{result.errors[0]||(result.status==="passed"?"All seven cohort-integrity gates pass.":"One or more hard gates failed.")}</small></div>{result.summary&&<><div className="cohortMetrics"><article><span>SCREENED</span><b>{result.summary.screened}</b></article><article><span>ANALYSIS SET</span><b>{result.summary.analysis_set}</b></article><article><span>SELECTION RATE</span><b>{(result.summary.selection_rate*100).toFixed(1)}%</b></article><article><span>POST-ACTIVATION EXCLUSIONS</span><b>{result.summary.post_activation_exclusions}</b></article></div><div className="cohortGates">{result.gates.map(item=><article className={item.passed?"pass":"fail"} key={item.id}><span>{item.id}</span><div><b>{item.label}</b><p>{item.detail}</p></div><i>{item.passed?"PASS":"FAIL"}</i></article>)}</div><button className="exportCohort" onClick={exportResult}>EXPORT RESULT</button></>}</div></div><aside><b>INDEPENDENCE != REPRESENTATIVENESS</b><p>A pass proves the reported decision units are distinct and prospectively accounted for. It does not prove the recruited sample represents every household, culture, geography, disability, or use case.</p></aside></section>;
}

