"use client";
import { useState } from "react";
import { assessRootCommitmentWitness, type RootWitnessResult } from "./profile";

const empty:RootWitnessResult={status:"invalid",errors:["Paste a manifest or explicitly load the signed synthetic example."],gates:[],summary:null};
export function RootCommitmentWitnessLab(){
  const [input,setInput]=useState("");
  const [result,setResult]=useState<RootWitnessResult>(empty);
  const [busy,setBusy]=useState(false);
  const evaluate=async(text:string)=>{setBusy(true);try{const value=JSON.parse(text);setResult(await assessRootCommitmentWitness(value))}catch(error){setResult({status:"invalid",errors:[error instanceof Error?error.message:"Invalid JSON."],gates:[],summary:null})}finally{setBusy(false)}};
  const load=async()=>{setBusy(true);try{const response=await fetch("/wanted-10k/root-commitment-witness.template.json",{headers:{accept:"application/json"}});if(!response.ok)throw new Error(`Synthetic example request failed with ${response.status}.`);const value=await response.json(),text=JSON.stringify(value,null,2);setInput(text);setResult(await assessRootCommitmentWitness(value))}catch(error){setResult({status:"invalid",errors:[error instanceof Error?error.message:"Could not load the example."],gates:[],summary:null})}finally{setBusy(false)}};
  const run=()=>void evaluate(input);
  const exportResult=()=>{if(!result.summary)return;const payload={benchmark:"WANTED-10K",root_commitment_witness_profile_version:"0.2-RC1",generated_at:new Date().toISOString(),status:result.status,gates:result.gates,summary:result.summary,note:"Aggregate local verification result. The source manifest and witness receipts are not included."};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));const anchor=document.createElement("a");anchor.href=url;anchor.download="wanted-root-witness-verification.json";anchor.click();URL.revokeObjectURL(url)};
  const status=busy?"VERIFYING":result.status.toUpperCase();
  return <section className="exposureLab"><header><div><span>LOCAL ROOT-WITNESS VERIFIER</span><b>PROFILE / 0.2-RC1 · WEB CRYPTO ED25519</b></div><div><button disabled={busy} onClick={()=>void load()}>LOAD SIGNED EXAMPLE</button><button disabled={busy||!input} className="runExposure" onClick={run}>VERIFY RECEIPTS →</button></div></header><div className="exposureWorkspace"><div className="exposureEditor"><label htmlFor="root-witness-input">ROOT SERIES + WITNESS REGISTRY + SIGNED RECEIPTS</label><textarea id="root-witness-input" spellCheck={false} value={input} onChange={event=>setInput(event.target.value)} placeholder="Paste one 0.2-RC1 root-witness manifest…"/><footer><a href="/wanted-10k/root-commitment-witness.schema.json">MANIFEST SCHEMA</a><a href="/wanted-10k/wanted-root-witness-verifier.mjs">ESM + CLI</a><a href="/wanted-10k/root-witness-conformance-vectors.json">11 TEST VECTORS</a><a href="/wanted-10k/root-witness-verifier-sdk.json">SOURCE DIGEST</a><span>Pasted manifests never leave this browser.</span></footer></div><div className="exposureOutput"><div className={`exposureStatus ${result.status}`}><span>ROOT CHRONOLOGY</span><b>{status}</b><small>{busy?"Reconstructing cadence, collection digest, witness keys, signatures, and receipt timing…":result.errors[0]||(result.status==="passed"?"All eight root-witness gates pass.":"One or more hard gates failed.")}</small></div>{result.summary&&<><div className="exposureMetrics"><article><span>DEPLOYMENTS</span><b>{result.summary.deployment_count}</b></article><article><span>PERIODIC ROOTS</span><b>{result.summary.root_count}</b></article><article><span>VALIDATED RECEIPTS</span><b>{result.summary.receipt_count-result.summary.invalid_signatures}</b></article><article><span>MAX OBSERVED DELAY</span><b>{result.summary.maximum_observed_delay_hours}h</b></article></div><div className="exposureGates">{result.gates.map(item=><article className={item.passed?"pass":"fail"} key={item.id}><span>{item.id}</span><div><b>{item.label}</b><p>{item.detail}</p></div><i>{item.passed?"PASS":"FAIL"}</i></article>)}</div><button className="exportExposure" onClick={exportResult}>EXPORT AGGREGATE RESULT</button></>}</div></div><aside><b>NO RECEIPT UPLOAD</b><p>The verifier canonicalizes and checks the pasted manifest entirely in this browser using Web Crypto. Only the explicit “load signed example” action fetches a public synthetic template from this site. Exported results contain aggregate counts and gates, not source receipts.</p></aside></section>;
}
