import { canonicalize, sha256, validateStream } from "../conformance/validator.ts";

export const ROOT_ENVELOPE_VERSION="0.2-RE1";
export const ROOT_ENVELOPE_FIELDS=["profile_version","protocol_version","telemetry_authenticity_profile","deployment_id","environment_id_sha256","root_ordinal","covers_through_at","prefix_event_count","interval_event_count","genesis_event_sha256","tail_sequence","tail_event_id","tail_event_sha256","tail_occurred_at","event_stream_prefix_sha256","key_manifest_sha256","previous_root_commitment_sha256","root_commitment_sha256"] as const;
export type RootEnvelope={profile_version:typeof ROOT_ENVELOPE_VERSION;protocol_version:"0.2";telemetry_authenticity_profile:"0.2-T1";deployment_id:string;environment_id_sha256:string;root_ordinal:number;covers_through_at:string;prefix_event_count:number;interval_event_count:number;genesis_event_sha256:string;tail_sequence:number;tail_event_id:string;tail_event_sha256:string;tail_occurred_at:string;event_stream_prefix_sha256:string;key_manifest_sha256:string;previous_root_commitment_sha256:string|null;root_commitment_sha256:string};
export type RootEnvelopeResult={status:"pass"|"fail";errors:string[];root_ordinal:number|null;root_commitment_sha256:string|null;prefix_event_count:number;interval_event_count:number;tail_sequence:number|null;covers_through_at:string|null};

const object=(value:unknown):Record<string,unknown>|null=>value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:null;
const digest=(value:unknown)=>typeof value==="string"&&/^[a-f0-9]{64}$/.test(value);
const utc=(value:unknown)=>typeof value==="string"&&value.endsWith("Z")&&Number.isFinite(Date.parse(value));
const parseEvents=(input:unknown)=>{if(Array.isArray(input))return structuredClone(input) as Record<string,unknown>[];if(typeof input!=="string")throw new TypeError("events must be a JSON array or JSONL text");return input.split(/\r?\n/).map(line=>line.trim()).filter(Boolean).map(line=>JSON.parse(line)) as Record<string,unknown>[];};
const parseManifest=(input:unknown)=>{if(typeof input==="string")return JSON.parse(input) as Record<string,unknown>;const value=object(input);if(!value)throw new TypeError("key manifest must be one JSON object or JSON text");return structuredClone(value);};
const unsignedEnvelope=(value:Record<string,unknown>)=>{const result=structuredClone(value);delete result.root_commitment_sha256;return result;};
const same=(left:unknown,right:unknown)=>canonicalize(left)===canonicalize(right);

function validateEnvelopeShape(value:unknown){const envelope=object(value),errors:string[]=[];if(!envelope)return{envelope:null,errors:["Root envelope must be one JSON object."]};const keys=Object.keys(envelope).sort(),expected=[...ROOT_ENVELOPE_FIELDS].sort();if(keys.length!==expected.length||keys.some((key,index)=>key!==expected[index]))errors.push(`Root envelope must contain exactly: ${ROOT_ENVELOPE_FIELDS.join(", ")}.`);if(envelope.profile_version!==ROOT_ENVELOPE_VERSION||envelope.protocol_version!=="0.2"||envelope.telemetry_authenticity_profile!=="0.2-T1")errors.push("Envelope versions must freeze 0.2-RE1, protocol 0.2, and authenticity 0.2-T1.");if(typeof envelope.deployment_id!=="string"||!envelope.deployment_id)errors.push("deployment_id is required.");if(!digest(envelope.environment_id_sha256)||!Number.isInteger(envelope.root_ordinal)||Number(envelope.root_ordinal)<0||!utc(envelope.covers_through_at))errors.push("Environment digest, root ordinal, and coverage timestamp are invalid.");for(const field of ["prefix_event_count","interval_event_count","tail_sequence"]){if(!Number.isInteger(envelope[field])||Number(envelope[field])<0)errors.push(`${field} must be a non-negative integer.`);}for(const field of ["genesis_event_sha256","tail_event_sha256","event_stream_prefix_sha256","key_manifest_sha256","root_commitment_sha256"]){if(!digest(envelope[field]))errors.push(`${field} must be a lowercase SHA-256 digest.`);}if(envelope.previous_root_commitment_sha256!==null&&!digest(envelope.previous_root_commitment_sha256))errors.push("previous_root_commitment_sha256 must be null or a lowercase SHA-256 digest.");if(typeof envelope.tail_event_id!=="string"||!envelope.tail_event_id||!utc(envelope.tail_occurred_at))errors.push("Tail event identity and timestamp are invalid.");return{envelope,errors};}

async function validatePrevious(previous:unknown,events:Record<string,unknown>[],keyManifest:Record<string,unknown>,rootOrdinal:number,coversThroughAt:string){if(previous===null){if(rootOrdinal!==0)throw new Error("Root ordinal zero is required when no previous envelope is supplied.");return null;}const shaped=validateEnvelopeShape(previous);if(!shaped.envelope||shaped.errors.length)throw new Error(`Previous root envelope is invalid: ${shaped.errors.join(" ")}`);const prior=shaped.envelope as unknown as RootEnvelope;if(await sha256(unsignedEnvelope(prior as unknown as Record<string,unknown>))!==prior.root_commitment_sha256)throw new Error("Previous root commitment digest does not reproduce.");if(prior.root_ordinal+1!==rootOrdinal)throw new Error("Root ordinal must increment exactly from the previous envelope.");if(Date.parse(prior.covers_through_at)>=Date.parse(coversThroughAt))throw new Error("covers_through_at must advance beyond the previous envelope.");const priorPrefix=events.slice(0,prior.prefix_event_count),tail=priorPrefix.at(-1);if(priorPrefix.length!==prior.prefix_event_count||!tail)throw new Error("Previous root prefix is unavailable in the supplied telemetry stream.");const report=await validateStream(priorPrefix.map(event=>JSON.stringify(event)).join("\n"),JSON.stringify(keyManifest));if(report.status!=="pass")throw new Error("Previous root telemetry prefix no longer verifies.");if(prior.deployment_id!==String(tail.deployment_id)||prior.environment_id_sha256!==await sha256(String(tail.environment_id))||prior.genesis_event_sha256!==await sha256(priorPrefix[0])||prior.tail_sequence!==Number(tail.sequence)||prior.tail_event_id!==String(tail.event_id)||prior.tail_event_sha256!==await sha256(tail)||prior.tail_occurred_at!==String(tail.occurred_at)||prior.event_stream_prefix_sha256!==await sha256(priorPrefix)||prior.key_manifest_sha256!==await sha256(keyManifest))throw new Error("Previous root does not reproduce from the supplied telemetry prefix and key manifest.");return prior;}

export async function createRootEnvelope(input:{events:unknown;keyManifest:unknown;rootOrdinal:number;coversThroughAt:string;previousEnvelope?:unknown}):Promise<RootEnvelope>{
  const events=parseEvents(input.events),keyManifest=parseManifest(input.keyManifest),covers=input.coversThroughAt;if(!Number.isInteger(input.rootOrdinal)||input.rootOrdinal<0)throw new Error("rootOrdinal must be a non-negative integer.");if(!utc(covers))throw new Error("coversThroughAt must be a UTC timestamp.");const prefix=events.filter(event=>utc(event.occurred_at)&&Date.parse(String(event.occurred_at))<=Date.parse(covers));if(!prefix.length)throw new Error("At least one accepted event must exist at or before coversThroughAt.");const report=await validateStream(prefix.map(event=>JSON.stringify(event)).join("\n"),JSON.stringify(keyManifest));if(report.status!=="pass")throw new Error(`Telemetry prefix failed 0.2-T1 verification: ${report.errors.join(" ")}`);const previous=await validatePrevious(input.previousEnvelope??null,events,keyManifest,input.rootOrdinal,covers),priorCount=previous?.prefix_event_count??0;if(prefix.length<priorCount)throw new Error("Telemetry prefix cannot shrink below the previous root.");if(previous){const priorPrefix=prefix.slice(0,previous.prefix_event_count),priorTail=priorPrefix.at(-1);if(!priorTail||await sha256(priorTail)!==previous.tail_event_sha256||await sha256(priorPrefix)!==previous.event_stream_prefix_sha256)throw new Error("Previous root does not bind the same telemetry prefix.");}
  const first=prefix[0],tail=prefix.at(-1)!;const unsigned={profile_version:ROOT_ENVELOPE_VERSION,protocol_version:"0.2" as const,telemetry_authenticity_profile:"0.2-T1" as const,deployment_id:String(tail.deployment_id),environment_id_sha256:await sha256(String(tail.environment_id)),root_ordinal:input.rootOrdinal,covers_through_at:covers,prefix_event_count:prefix.length,interval_event_count:prefix.length-priorCount,genesis_event_sha256:await sha256(first),tail_sequence:Number(tail.sequence),tail_event_id:String(tail.event_id),tail_event_sha256:await sha256(tail),tail_occurred_at:String(tail.occurred_at),event_stream_prefix_sha256:await sha256(prefix),key_manifest_sha256:await sha256(keyManifest),previous_root_commitment_sha256:previous?.root_commitment_sha256??null};return{...unsigned,root_commitment_sha256:await sha256(unsigned)};
}

export async function verifyRootEnvelope(value:unknown,eventsInput:unknown,keyManifestInput:unknown,previousEnvelope:unknown=null,options:{allowHistoricalPrefix?:boolean}={}):Promise<RootEnvelopeResult>{
  const shaped=validateEnvelopeShape(value);if(!shaped.envelope||shaped.errors.length)return{status:"fail",errors:shaped.errors,root_ordinal:null,root_commitment_sha256:null,prefix_event_count:0,interval_event_count:0,tail_sequence:null,covers_through_at:null};const claimed=shaped.envelope as unknown as RootEnvelope;try{const events=parseEvents(eventsInput),keyManifest=parseManifest(keyManifestInput),expected=await createRootEnvelope({events,keyManifest,rootOrdinal:claimed.root_ordinal,coversThroughAt:claimed.covers_through_at,previousEnvelope});if(!same(claimed,expected))throw new Error("Root envelope does not reproduce from the signed telemetry prefix and frozen key manifest.");if(!options.allowHistoricalPrefix){const eligible=events.filter(event=>utc(event.occurred_at)&&Date.parse(String(event.occurred_at))<=Date.parse(claimed.covers_through_at));if(eligible.length!==claimed.prefix_event_count)throw new Error("Envelope omits an event at or before covers_through_at.");}return{status:"pass",errors:[],root_ordinal:claimed.root_ordinal,root_commitment_sha256:claimed.root_commitment_sha256,prefix_event_count:claimed.prefix_event_count,interval_event_count:claimed.interval_event_count,tail_sequence:claimed.tail_sequence,covers_through_at:claimed.covers_through_at};}catch(error){return{status:"fail",errors:[error instanceof Error?error.message:"Root envelope verification failed."],root_ordinal:claimed.root_ordinal,root_commitment_sha256:claimed.root_commitment_sha256,prefix_event_count:claimed.prefix_event_count,interval_event_count:claimed.interval_event_count,tail_sequence:claimed.tail_sequence,covers_through_at:claimed.covers_through_at};}
}

export async function verifyRootEnvelopeSeries(input:{envelopes:unknown;events:unknown;keyManifest:unknown;activationAt:string;observationEndAt:string;intervalHours?:number}){const errors:string[]=[],results:RootEnvelopeResult[]=[];if(!Array.isArray(input.envelopes)||!input.envelopes.length)return{status:"fail",errors:["Provide at least one root envelope."],root_count:0,final_prefix_event_count:0,results};if(!utc(input.activationAt)||!utc(input.observationEndAt)||Date.parse(input.observationEndAt)<=Date.parse(input.activationAt))return{status:"fail",errors:["Activation and observation-end timestamps are invalid."],root_count:input.envelopes.length,final_prefix_event_count:0,results};const interval=input.intervalHours??24;if(!Number.isInteger(interval)||interval<1||interval>24)return{status:"fail",errors:["intervalHours must be an integer from 1 to 24."],root_count:input.envelopes.length,final_prefix_event_count:0,results};const due=Math.ceil((Date.parse(input.observationEndAt)-Date.parse(input.activationAt))/(interval*3600000));if(input.envelopes.length!==due)errors.push(`Expected ${due} root envelopes, received ${input.envelopes.length}.`);let previous:null|RootEnvelope=null;for(let index=0;index<input.envelopes.length;index++){const envelope=object(input.envelopes[index]),expectedAt=new Date(Math.min(Date.parse(input.observationEndAt),Date.parse(input.activationAt)+(index+1)*interval*3600000)).toISOString();if(!envelope||envelope.root_ordinal!==index||envelope.covers_through_at!==expectedAt)errors.push(`Root ${index} does not match the exact due ordinal and timestamp.`);const result=await verifyRootEnvelope(input.envelopes[index],input.events,input.keyManifest,previous);results.push(result);if(result.status!=="pass")errors.push(`Root ${index}: ${result.errors.join(" ")}`);previous=input.envelopes[index] as RootEnvelope;}return{status:errors.length?"fail":"pass",errors,root_count:input.envelopes.length,final_prefix_event_count:previous?.prefix_event_count??0,final_root_commitment_sha256:previous?.root_commitment_sha256??null,results};}

const digestSchema={type:"string",pattern:"^[a-f0-9]{64}$"},timestamp={type:"string",format:"date-time",pattern:"Z$"};
export const rootEnvelopeSchema={"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://embodied-arena.chrishongap.chatgpt.site/wanted-10k/root-envelope.schema.json",title:"WANTED Signed Telemetry Root Envelope",type:"object",additionalProperties:false,required:ROOT_ENVELOPE_FIELDS,properties:{profile_version:{const:ROOT_ENVELOPE_VERSION},protocol_version:{const:"0.2"},telemetry_authenticity_profile:{const:"0.2-T1"},deployment_id:{type:"string",minLength:1},environment_id_sha256:digestSchema,root_ordinal:{type:"integer",minimum:0},covers_through_at:timestamp,prefix_event_count:{type:"integer",minimum:1},interval_event_count:{type:"integer",minimum:0},genesis_event_sha256:digestSchema,tail_sequence:{type:"integer",minimum:0},tail_event_id:{type:"string",minLength:1},tail_event_sha256:digestSchema,tail_occurred_at:timestamp,event_stream_prefix_sha256:digestSchema,key_manifest_sha256:digestSchema,previous_root_commitment_sha256:{oneOf:[digestSchema,{type:"null"}]},root_commitment_sha256:digestSchema}} as const;
export const rootEnvelopeContract={name:"WANTED Signed Telemetry Root Envelope Profile",version:ROOT_ENVELOPE_VERSION,protocol_version:"0.2",telemetry_authenticity_profile:"0.2-T1",root_witness_profile:"0.2-RC1",certification_effect:"hard_field_gate",ranking_effect:"eligibility_only_not_score_or_tiebreaker",applies_to:["WANTED_LAB","WANTED_WILD","WANTED_10K"],hash:"SHA-256",canonicalization:"RFC8785_JCS",root_digest_scope:"envelope_without_root_commitment_sha256",binds:["verified_signed_event_prefix","deployment_id","hashed_environment_id","root_ordinal","coverage_boundary","cumulative_and_interval_event_counts","genesis_and_tail_event_digests","tail_identity_and_time","event_stream_prefix_digest","frozen_key_manifest_digest","previous_root_commitment"],cadence:{maximum_interval_hours:24,final_root_at_observation_end:true,zero_event_intervals_permitted:true},audit_summary:{field:"root_envelope_integrity",evidence_role:"root_envelope_verification_report",root_collection_digest_must_match:["telemetry.root_commitments_sha256","root_commitment_witness.root_commitments_sha256"],all_failure_counters_zero:true},proves:"the_witnessed_digest_commits_to_one_verified_signed_telemetry_prefix_and_an_append_only_root_chain",does_not_prove:["sensor_truth","complete_capture_of_unobserved_events","witness_independence","publication_time","robot_safety","human_preference"],interpretation:"0.2-RE1 defines the root document that 0.2-RC1 witnesses timestamp; both profiles are mandatory non-ranking field-certification gates for end-to-end anti-backfill evidence."} as const;
