"use client";
import { useState } from "react";
import { assessHilo, hiloTemplate, type HiloResult } from "./profile.ts";

const initial=assessHilo(hiloTemplate);
const fmt=(value:number|null,suffix="")=>value===null?"—":`${Number(value.toFixed(2)).toLocaleString()}${suffix}`;
export function RealtimeLab(){
  const[input,setInput]=useState(JSON.stringify(hiloTemplate,null,2)),[result,setResult]=useState<HiloResult>(initial);
  const run=()=>{try{setResult(assessHilo(JSON.parse(input)))}catch(error){setResult({status:"invalid",errors:[error instanceof Error?error.message:"Invalid JSON."],gates:[],summary:null})}};
  const load=()=>{setInput(JSON.stringify(hiloTemplate,null,2));setResult(assessHilo(hiloTemplate))};
  return <div className="hiloLab"><header><div><span>LOCAL CLOSED-LOOP VERIFIER</span><b>PROFILE / 0.1-RT1</b></div><div><button onClick={load}>LOAD SYNTHETIC EXAMPLE</button><button className="runHilo" onClick={run}>VERIFY -&gt;</button></div></header><div className="hiloWorkspace"><div className="hiloEditor"><label htmlFor="hilo-input">SESSIONS + EVENTS + INTERVENTIONS + LATENCY + SAFETY</label><textarea id="hilo-input" spellCheck={false} value={input} onChange={event=>setInput(event.target.value)}/><footer><a href="/wanted-10k/realtime.schema.json">MANIFEST SCHEMA</a><span>Runs locally. No event data is uploaded.</span></footer></div><div className="hiloOutput"><div className={`hiloStatus ${result.status}`}><span>HILO EVIDENCE</span><b>{result.status.toUpperCase()}</b><small>{result.errors[0]||(result.status==="passed"?"All seven closed-loop gates pass.":"One or more hard gates failed.")}</small></div>{result.summary&&<><div className="hiloMetrics"><article><span>ELIGIBLE EXPOSURE</span><b>{fmt(result.summary.eligible_autonomous_hours,"h")}</b></article><article><span>HB100</span><b>{fmt(result.summary.human_burden_minutes_per_100_hours,"m")}</b></article><article><span>MTHI</span><b>{fmt(result.summary.mean_time_to_human_intervention_hours,"h")}</b></article><article><span>P95 LOOP LATENCY</span><b>{fmt(result.summary.latency_overall.p95_ms,"ms")}</b></article></div><div className="hiloGates">{result.gates.map(item=><article className={item.passed?"pass":"fail"} key={item.id}><span>{item.id}</span><div><b>{item.label}</b><p>{item.detail}</p></div><i>{item.passed?"PASS":"FAIL"}</i></article>)}</div></>}</div></div><aside><b>REFERENCE ≠ STANDARD</b><p>The included GPT-Realtime-2.1 manifest demonstrates one adapter. Passing depends on the event, burden, latency, survival, safety, and evidence contract—not on the provider or model name.</p></aside></div>;
}
