"use client";

import { useState, type ChangeEvent } from "react";
import { auditManifestTemplates } from "../audit/manifest";
import { emptyAuditSealResult, verifyAuditSeal, type AuditSealResult } from "./profile";

export function AuditSealLab() {
  const [input,setInput] = useState("");
  const [result,setResult] = useState<AuditSealResult>(emptyAuditSealResult);
  const [working,setWorking] = useState(false);
  const run = async (value=input) => { setWorking(true);try{const parsed=JSON.parse(value);setResult(await verifyAuditSeal(parsed));}catch(error){setResult({...emptyAuditSealResult,status:"fail",errors:[error instanceof Error?error.message:"Invalid JSON"]});}finally{setWorking(false);} };
  const loadExample = async () => { const value=JSON.stringify(auditManifestTemplates.WANTED_WILD,null,2);setInput(value);await run(value); };
  const loadFile = async (event: ChangeEvent<HTMLInputElement>) => { const file=event.target.files?.[0];if(!file)return;setInput(await file.text());setResult(emptyAuditSealResult); };
  const exportReport = () => { if(result.status==="idle")return;const payload={profile_version:"0.2-V1",generated_at:new Date().toISOString(),verification_status:result.status,manifest_sha256:result.manifestSha256,public_key_sha256:result.publicKeySha256,signature_verified:result.signatureVerified,checks:result.checks,errors:result.errors,note:"Local audit-seal verification only. Auditor identity, independence, competence, and underlying evidence still require registry review."};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));const anchor=document.createElement("a");anchor.href=url;anchor.download="wanted-audit-seal-verification.json";anchor.click();URL.revokeObjectURL(url); };
  return <section className="sealWorkspace shell"><div className="sealGrid"><div className="sealEditor"><header><div><span>SEALED AUDIT MANIFEST</span><small>AGGREGATE JSON · DATA STAYS ON-DEVICE</small></div><div><button onClick={loadExample}>LOAD SIGNED EXAMPLE</button><label>OPEN FILE<input type="file" accept=".json,application/json" onChange={loadFile}/></label></div></header><textarea aria-label="Sealed WANTED audit manifest" spellCheck={false} value={input} onChange={event=>{setInput(event.target.value);setResult(emptyAuditSealResult)}} placeholder={'{"protocol_version":"0.2","audit":{"profile_version":"0.2-V1",...}}'}/><footer><span>{input.length.toLocaleString()} CHARACTERS</span><div><button disabled={result.status==="idle"} onClick={exportReport}>EXPORT VERIFICATION ↓</button><button disabled={working} onClick={()=>run()}>{working?"VERIFYING…":"VERIFY AUDITOR SEAL →"}</button></div></footer></div><aside className={`sealReport ${result.status}`}><header><span>INDEPENDENT AUDIT SEAL</span><b>{result.status==="idle"?"READY":result.status==="pass"?"SEAL VERIFIED":"SEAL FAILED"}</b></header><div className="sealDigests"><div><span>MANIFEST SHA-256</span><code>{result.manifestSha256??"—"}</code></div><div><span>PUBLIC KEY SHA-256</span><code>{result.publicKeySha256??"—"}</code></div></div><div className="sealChecks">{result.status==="idle"&&<p>Load the signed synthetic example or open a complete aggregate audit manifest.</p>}{result.checks.map(check=><article className={check.passed?"pass":"fail"} key={check.id}><span>{check.id}</span><b>{check.label}</b><i>{check.passed?"PASS":"FAIL"}</i></article>)}{result.errors.map((error,index)=><p className="error" key={index}>{error}</p>)}</div></aside></div><div className="sealBoundary"><b>CRYPTOGRAPHIC PROOF</b><span>Manifest bytes unchanged · declared key unchanged · signer possessed the private key</span><b>REGISTRY REVIEW</b><span>Auditor identity · independence · competence · source evidence · factual truth</span></div></section>;
}
