"use client";

import { useState, type ChangeEvent } from "react";
import { auditManifestTemplates } from "../audit/manifest";
import { verifyAuditPackage } from "../auditor-credential/profile";

type PackageState = { status: "idle" | "pass" | "fail"; manifestSha256: string | null; publicKeySha256: string | null; credentialSha256: string | null; sealVerified: boolean; credentialVerified: boolean; checks: { id: string; label: string; passed: boolean }[]; errors: string[] };
const emptyPackage: PackageState = { status: "idle", manifestSha256: null, publicKeySha256: null, credentialSha256: null, sealVerified: false, credentialVerified: false, checks: [], errors: [] };

export function AuditSealLab() {
  const [input,setInput] = useState("");
  const [result,setResult] = useState<PackageState>(emptyPackage);
  const [working,setWorking] = useState(false);
  const run = async (value=input) => { setWorking(true);try{const parsed=JSON.parse(value);const verified=await verifyAuditPackage(parsed);setResult({status:verified.status,manifestSha256:verified.seal.manifestSha256,publicKeySha256:verified.seal.publicKeySha256,credentialSha256:verified.credential.credentialSha256,sealVerified:verified.seal.signatureVerified,credentialVerified:verified.credential.issuerSignatureVerified,checks:[...verified.seal.checks,...verified.credential.checks],errors:[...verified.seal.errors,...verified.credential.errors]});}catch(error){setResult({...emptyPackage,status:"fail",errors:[error instanceof Error?error.message:"Invalid JSON"]});}finally{setWorking(false);} };
  const loadExample = async () => { const value=JSON.stringify(auditManifestTemplates.WANTED_WILD,null,2);setInput(value);await run(value); };
  const loadFile = async (event: ChangeEvent<HTMLInputElement>) => { const file=event.target.files?.[0];if(!file)return;setInput(await file.text());setResult(emptyPackage); };
  const exportReport = () => { if(result.status==="idle")return;const payload={profile_versions:["0.2-V1","0.2-V2"],generated_at:new Date().toISOString(),verification_status:result.status,manifest_sha256:result.manifestSha256,auditor_public_key_sha256:result.publicKeySha256,auditor_credential_sha256:result.credentialSha256,auditor_signature_verified:result.sealVerified,registry_issuer_signature_verified:result.credentialVerified,checks:result.checks,errors:result.errors,note:"Local cryptographic verification. A credential proves a pinned registry issuer signed the auditor/key binding; legal identity, competence, independence, and underlying evidence still require registry review."};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));const anchor=document.createElement("a");anchor.href=url;anchor.download="wanted-audit-package-verification.json";anchor.click();URL.revokeObjectURL(url); };
  return <section className="sealWorkspace shell"><div className="sealGrid"><div className="sealEditor"><header><div><span>SEALED + CREDENTIALED AUDIT MANIFEST</span><small>AGGREGATE JSON · DATA STAYS ON-DEVICE</small></div><div><button onClick={loadExample}>LOAD SIGNED EXAMPLE</button><label>OPEN FILE<input type="file" accept=".json,application/json" onChange={loadFile}/></label></div></header><textarea aria-label="Credentialed WANTED audit manifest" spellCheck={false} value={input} onChange={event=>{setInput(event.target.value);setResult(emptyPackage)}} placeholder={'{"protocol_version":"0.2","audit":{"profile_version":"0.2-V1","credential":{"profile_version":"0.2-V2"},...}}'}/><footer><span>{input.length.toLocaleString()} CHARACTERS</span><div><button disabled={result.status==="idle"} onClick={exportReport}>EXPORT VERIFICATION ↓</button><button disabled={working} onClick={()=>run()}>{working?"VERIFYING…":"VERIFY AUDIT PACKAGE →"}</button></div></footer></div><aside className={`sealReport ${result.status}`}><header><span>AUDIT SEAL + REGISTRY CREDENTIAL</span><b>{result.status==="idle"?"READY":result.status==="pass"?"PACKAGE VERIFIED":"VERIFICATION FAILED"}</b></header><div className="sealDigests"><div><span>MANIFEST SHA-256</span><code>{result.manifestSha256??"—"}</code></div><div><span>AUDITOR KEY SHA-256</span><code>{result.publicKeySha256??"—"}</code></div><div><span>CREDENTIAL SHA-256</span><code>{result.credentialSha256??"—"}</code></div></div><div className="sealChecks">{result.status==="idle"&&<p>Load the credentialed synthetic example or open a complete aggregate audit manifest.</p>}{result.checks.map(check=><article className={check.passed?"pass":"fail"} key={check.id}><span>{check.id}</span><b>{check.label}</b><i>{check.passed?"PASS":"FAIL"}</i></article>)}{result.errors.map((error,index)=><p className="error" key={index}>{error}</p>)}</div></aside></div><div className="sealBoundary"><b>VERIFIED LOCALLY</b><span>Manifest integrity · auditor key possession · pinned registry issuer · target authorization · key lifecycle</span><b>STILL HUMAN REVIEW</b><span>Legal identity · competence · independence · source evidence · factual truth</span></div></section>;
}
