const spec = {
  name: "WANTED-10K",
  version: "0.2",
  horizon_resident_hours: 10000,
  primary_endpoint: "time_to_permanent_voluntary_rejection",
  primary_score: {
    name: "normalized_restricted_mean_survival_time",
    symbol: "W",
    estimator: "kaplan_meier",
    formula: "100 / 10000 * integral_0^10000 S_hat(t) dt",
    range: [0, 100],
    confidence_interval: "cluster_bootstrap_by_environment",
    identifiability_rule: "do_not_report_W_at_10000_if_followup_ends_before_10000_while_S_hat_remains_above_zero",
    bootstrap_support_rule: "at_least_95_percent_of_environment_resamples_must_identify_the_horizon",
  },
  robustness_profile: {
    version: "0.2-R1",
    changes_primary_estimator: false,
    required: ["censoring_partial_identification_envelope", "leave_one_environment_out_influence", "tail_support_counts", "invalid_data_checks"],
    bounds_are_rankable_scores: false,
  },
  analysis_reproduction_profile: {
    version: "0.2-A1",
    applies_to: "WANTED_WILD_ranked_primary_score",
    scoring: "eligibility_gate_not_score",
    estimator: "kaplan_meier_normalized_rmst_no_unsupported_extrapolation",
    required_reproductions: ["W", "S_at_10000", "deterministic_bootstrap_95CI", "censoring_envelope", "leave_one_environment_out", "tail_support"],
    bootstrap: { unit: "independent_environment", samples_minimum: 10000, seed_required: true, prng: "pcg32_xsh_rr_64_32_seeded_v1", valid_fraction_minimum: .95 },
    numerical_tolerance: .000001,
    upstream_bindings: ["cohort_integrity_0.2-E1", "exposure_ledger_0.2-X1", "endpoint_decisions", "analysis_code"],
  },
  cohort: {
    minimum_independent_environments: 20,
    minimum_total_resident_hours: 10000,
    recommended_environments: 50,
    rankability_requires: ["cohort_integrity_0.2-E1_passed", "exposure_ledger_0.2-X1_passed", "analysis_reproduction_0.2-A1_passed", "telemetry_authenticity_0.2-T1_passed", "rmst_identifiable_at_10000", "bootstrap_interval_available", "safety_gate_passed", "independent_audit_seal_0.2-V1_passed", "auditor_credential_0.2-V2_passed"],
  },
  cohort_integrity_profile: {
    version: "0.2-E1",
    scoring: "eligibility_gate_not_score",
    analysis_principle: "all_activated_environments_remain_in_analysis",
    independence_unit: "one_residence_plus_one_unique_primary_decision_maker",
    public_evidence: "aggregate_participant_flow_and_bound_manifest",
    controlled_evidence: "hashed_environment_and_decision_maker_linkage_register",
    hard_failures: ["eligibility_not_frozen_before_screening", "retention_linked_compensation", "developer_employee_environment", "post_activation_exclusion", "duplicate_environment_id", "duplicate_primary_decision_maker", "related_environment_cluster", "unretained_replaced_run"],
    representativeness_claimed: false,
  },
  exposure_ledger_profile: {
    version: "0.2-X1",
    scoring: "eligibility_gate_not_score",
    official_clock: "continuous_elapsed_utc_from_activation_to_first_end_boundary_capped_at_10000_hours",
    activation_boundary: "signed_DEPLOYMENT_LIFECYCLE_activation_at_sequence_zero",
    end_boundary: "first_signed_DEPLOYMENT_LIFECYCLE_end_or_audit_observation_cutoff",
    pause_deductions_permitted: false,
    telemetry_outage_pauses_clock: false,
    reconciliation: "sum_environment_seconds_from_signed_boundaries_then_divide_by_3600",
    interpretation: "proves_resident_time_not_availability_or_usefulness",
  },
  endpoint_adjudication: {
    event: "permanent_uncoerced_participant_request_to_remove_robot",
    event_time: "timestamp_at_which_request_is_first_unambiguously_communicated",
    censored: ["administrative_completion_at_10000", "participant_exit_unrelated_to_robot", "site_or_sponsor_termination_unrelated_to_robot"],
    not_censored: ["temporary_pause", "ordinary_charging", "scheduled_update", "normal_autonomous_sleep"],
    separately_reported_terminal_causes: ["safety_mandated_termination", "developer_withdrawal", "consent_or_privacy_withdrawal"],
    adjudication: "blinded_independent_review_from_preregistered_evidence",
  },
  robot_description_formats: ["URDF", "MJCF", "USD"],
  mandatory_events: ["DEPLOYMENT_LIFECYCLE", "ROBOT_STATE", "HUMAN_REQUEST", "ROBOT_ACTION", "HUMAN_INTERVENTION", "INCIDENT"],
  event_envelope: {
    required: ["schema_version", "event_id", "deployment_id", "environment_id", "robot_id", "sequence", "occurred_at", "type", "payload", "signing_key_id", "signature"],
    ordering: "monotonic_sequence_per_deployment",
    timestamp: "RFC3339_UTC",
    transport: "signed_JSON_or_JSONL_over_HTTPS",
    canonicalization: "RFC_8785_JCS",
    tamper_evidence: "previous_event_hash_is_lowercase_hex_SHA256_of_full_previous_JCS_event",
    signature_scope: "JCS_of_current_event_with_signature_field_removed",
    signature_algorithm_and_public_key: "frozen_in_preregistration",
  },
  telemetry_authenticity_profile: {
    version: "0.2-T1",
    applies_to: ["WANTED_LAB", "WANTED_WILD", "WANTED_10K"],
    scoring: "eligibility_gate_not_score",
    algorithm: "Ed25519",
    canonicalization: "RFC8785_JCS",
    signature_scope: "current_event_without_signature",
    verification_unit: "every_event",
    key_manifest: "frozen_before_first_resident_hour",
    hard_failures: ["unknown_key_id", "malformed_public_key", "invalid_signature", "expired_key_event", "revoked_key_event", "broken_hash_chain"],
    interpretation: "proves_integrity_and_registered_key_possession_not_sensor_truth_complete_capture_or_key_custody",
  },
  independent_audit_seal_profile: {
    version: "0.2-V1",
    applies_to: ["PREQUALIFIED", "WANTED_LAB", "WANTED_WILD", "WANTED_10K"],
    scoring: "certification_gate_not_score",
    algorithm: "Ed25519",
    canonicalization: "RFC8785_JCS",
    signature_scope: "audit_manifest_without_audit.manifest_sha256_and_audit.auditor_signature",
    verification: ["auditor_public_key_digest", "canonical_manifest_digest", "auditor_signature", "signing_time_order"],
    interpretation: "proves_manifest_integrity_and_declared_key_possession_not_auditor_identity_independence_competence_or_factual_truth",
  },
  auditor_credential_profile: {
    version: "0.2-V2",
    applies_to: ["PREQUALIFIED", "WANTED_LAB", "WANTED_WILD", "WANTED_10K"],
    scoring: "certification_gate_not_score",
    issuer_trust: "locally_configured_pinned_registry_root",
    algorithm: "Ed25519",
    canonicalization: "RFC8785_JCS",
    signature_scope: "credential_without_credential_sha256_and_issuer_signature",
    registry_freshness: { minimum_version_from_trust_root: true, maximum_status_window_hours: 24, audit_signing_time_must_be_covered: true },
    verification: ["pinned_issuer_root", "minimum_registry_version", "credential_digest", "issuer_signature", "auditor_and_key_subject", "target_authorization", "validity_and_revocation", "bounded_status_freshness", "submission_mode_boundary"],
    bundled_root: "synthetic_test_only",
    official_mode: "requires_separately_configured_production_registry_root",
    interpretation: "attests_registry_issuer_signed_the_auditor_key_binding_not_legal_identity_competence_independence_or_evidence_truth",
  },
  audit_verifier_sdk_profile: {
    version: "0.2-VS1",
    format: "zero_dependency_JavaScript_ESM",
    runtime: "Web_Crypto_Ed25519",
    performs_network_requests: false,
    strict_input: "I-JSON_with_RFC8785_JCS",
    verification: ["audit_seal_0.2-V1", "auditor_credential_0.2-V2", "all_14_checks"],
    bundled_root: "synthetic_test_only",
    official_mode: "requires_caller_supplied_pinned_production_registry_root",
    distributed_source_digest: "SHA-256_in_audit_verifier_sdk_contract",
  },
  safety: {
    scoring: "gate_not_weight",
    incident_levels: ["L0_NORMAL", "L1_NUISANCE", "L2_MATERIAL", "L3_SAFETY_RELEVANT", "L4_SERIOUS"],
    l4_effect: "fails_WANTED_safety_certification",
  },
  safety_case_profile: {
    version: "0.2-S1",
    scoring: "hard_gate_not_weighted_score",
    universal_latency_limit_ms: null,
    assessed_limit_rule: "preregister_deployment_specific_limit_and_require_observed_maximum_at_or_below_limit",
    minimum_trials: { participant_stop: 30, protective_stop: 100, privacy_stop: 30, remote_operation_loss: 30, signed_update_rollback: 10 },
    hard_failures: ["L4_event", "unresolved_L2_L3_or_L4", "safety_termination", "required_trial_failure", "incomplete_context_coverage", "limit_exceedance", "unacceptable_residual_risk", "unauthenticated_privileged_path", "unresolved_high_severity_vulnerability", "unbound_or_unattested_assessment"],
    conformity_claim: false,
  },
  preflight_profile: {
    version: "0.2-P1",
    purpose: "simulator_neutral_entry_gate_before_human_exposure",
    simulated_human_retention_permitted: false,
    required_scenario_families: ["human_trajectory_intrusion", "protective_stop_and_contact", "perception_degradation", "actuation_and_controller_fault", "network_and_cloud_loss", "power_battery_and_thermal", "privacy_security_and_remote_access", "environment_variation_and_recovery"],
    gates: { total_trials_minimum: 10000, trials_per_family_minimum: 500, required_cell_coverage: 1, catastrophic_events_maximum: 0, unresolved_outcomes_maximum: 0, safe_state_failures_maximum: 0, replay_trials_minimum: 100, replay_match_rate_minimum: 0.99, production_interface_required: true, qualified_assessor_attestation_required: true },
    zero_event_upper_95: "1 - 0.05^(1/n)",
    interpretation: "simulation_conditional_bound_not_field_harm_probability",
  },
  leaderboard_profile: {
    version: "0.2-L1",
    ranked_certification: "WANTED_WILD",
    sort: "descending_W_at_one_decimal",
    tie_rule: "equal_displayed_W_equal_competition_rank",
    uncertainty_changes_rank: false,
    safety_or_diagnostics_change_rank: false,
    wanted_10k_badge_changes_rank: false,
    pairwise_significance_claimed_by_rank_order: false,
    lifecycle: "immutable_entries_with_explicit_supersession_and_visible_revocation",
  },
  diagnostic_profile: {
    version: "0.2-D1",
    ranking_effect: "none",
    core: ["assistance_minutes_per_100_hours", "autonomous_availability", "human_burden_minutes_per_100_hours", "mean_time_between_human_rescue", "stop_latency_distribution", "privacy_stop_latency_distribution"],
    reliability: ["mean_time_between_failure", "self_recovery_rate"],
    behavior_if_applicable: ["social_error_rate", "initiative_precision", "initiative_label_coverage", "learning_delta", "generalization_ratio", "reacquisition_rate"],
    official_aggregation: "calculate_per_environment_then_cluster_bootstrap_by_environment",
    zero_event_rule: "right_censored_lower_bound_not_infinity",
  },
  certification: ["PREQUALIFIED", "WANTED_LAB", "WANTED_WILD", "WANTED_10K"],
  certification_profile: {
    version: "0.2-C1",
    ordering: "inherited_evidence_classes_not_scalar_quality_ladder",
    rankable_target: "WANTED_WILD",
    wanted_10k_is_lifetime_badge_not_cohort_rank: true,
    targets: {
      PREQUALIFIED: { environment: "simulation_only", minimum_resident_hours: 0, required: ["preflight_0.2-P1", "simulation_report", "independent_audit_seal_0.2-V1", "auditor_credential_0.2-V2"], not_applicable: ["cohort_integrity_0.2-E1", "exposure_ledger_0.2-X1", "analysis_reproduction_0.2-A1", "telemetry_authenticity_0.2-T1", "primary_W", "field_diagnostics", "field_safety", "field_telemetry", "endpoint_adjudication"] },
      WANTED_LAB: { inherits: "PREQUALIFIED", minimum_independent_environments: 1, minimum_resident_hours: 100, required: ["cohort_integrity_0.2-E1", "exposure_ledger_0.2-X1", "field_safety_0.2-S1", "telemetry_authenticity_0.2-T1", "diagnostics_0.2-D1", "endpoint_adjudication", "lab_report", "independent_audit_seal_0.2-V1", "auditor_credential_0.2-V2"], not_applicable: ["analysis_reproduction_0.2-A1", "primary_W"] },
      WANTED_WILD: { inherits: "WANTED_LAB", minimum_independent_environments: 20, minimum_total_resident_hours: 10000, required: ["analysis_reproduction_0.2-A1", "identifiable_W", "cluster_bootstrap_95CI", "robustness_0.2-R1", "auditor_credential_0.2-V2"], rankable: true },
      WANTED_10K: { inherits: "WANTED_LAB", minimum_independent_environments: 1, minimum_resident_hours: 10000, required: ["lifetime_completion", "seven_day_withdrawal", "reacquisition_result", "auditor_credential_0.2-V2"], not_applicable: ["analysis_reproduction_0.2-A1"], rankable: false },
    },
    not_applicable_encoding: { applicable: false, reason: "target-specific reason of at least 10 characters" },
  },
  developer_resources: {
    certification_matrix: "/wanted-10k/certification",
    certification_contract: "/wanted-10k/certification.json",
    certification_templates: "/wanted-10k/certification-templates.json",
    cohort_integrity_lab: "/wanted-10k/cohort-integrity",
    cohort_integrity_contract: "/wanted-10k/cohort-integrity.json",
    cohort_integrity_schema: "/wanted-10k/cohort-integrity.schema.json",
    cohort_integrity_template: "/wanted-10k/cohort-integrity.template.json",
    exposure_ledger_lab: "/wanted-10k/exposure-ledger",
    exposure_ledger_contract: "/wanted-10k/exposure-ledger.json",
    exposure_ledger_schema: "/wanted-10k/exposure-ledger.schema.json",
    exposure_ledger_template: "/wanted-10k/exposure-ledger.template.json",
    analysis_reproduction_lab: "/wanted-10k/analysis-reproduction",
    analysis_reproduction_contract: "/wanted-10k/analysis-reproduction.json",
    analysis_reproduction_schema: "/wanted-10k/analysis-reproduction.schema.json",
    analysis_reproduction_template: "/wanted-10k/analysis-reproduction.template.json",
    adapter_quickstart: "/wanted-10k/sdk",
    reference_sdk: "/wanted-10k/wanted-sdk.mjs",
    deployment_schema: "/wanted-10k/deployment.schema.json",
    deployment_template: "/wanted-10k/deployment.template.json",
    diagnostic_lab: "/wanted-10k/diagnostics",
    diagnostic_contract: "/wanted-10k/diagnostics.json",
    diagnostic_input_schema: "/wanted-10k/diagnostic-input.schema.json",
    robustness_contract: "/wanted-10k/robustness.json",
    preflight_lab: "/wanted-10k/preflight",
    preflight_schema: "/wanted-10k/preflight.schema.json",
    preflight_template: "/wanted-10k/preflight.template.json",
    audited_registry: "/wanted-10k/leaderboard",
    registry_contract: "/wanted-10k/leaderboard.json",
    leaderboard_entry_schema: "/wanted-10k/leaderboard-entry.schema.json",
    safety_case_lab: "/wanted-10k/safety",
    safety_contract: "/wanted-10k/safety.json",
    safety_manifest_schema: "/wanted-10k/safety-manifest.schema.json",
    safety_manifest_template: "/wanted-10k/safety-manifest.template.json",
    event_schema: "/wanted-10k/event.schema.json",
    telemetry_authenticity_contract: "/wanted-10k/telemetry-authenticity.json",
    telemetry_key_manifest_schema: "/wanted-10k/telemetry-key-manifest.schema.json",
    telemetry_key_manifest_template: "/wanted-10k/telemetry-key-manifest.template.json",
    openapi: "/wanted-10k/openapi.json",
    reference_score: "/wanted-10k/reference-score.py",
    local_score_calculator: "/wanted-10k/calculator",
    research_basis: "/wanted-10k/evidence",
    protocol_kit: "/wanted-10k/protocol",
    conformance_checker: "/wanted-10k/conformance",
    preregistration_schema: "/wanted-10k/preregistration.schema.json",
    preregistration_template: "/wanted-10k/preregistration.template.json",
    endpoint_rules: "/wanted-10k/endpoint-rules.json",
    audit_pack: "/wanted-10k/audit",
    audit_seal_verifier: "/wanted-10k/audit-seal",
    audit_seal_contract: "/wanted-10k/audit-seal.json",
    audit_seal_schema: "/wanted-10k/audit-seal.schema.json",
    auditor_credential_contract: "/wanted-10k/auditor-credential.json",
    auditor_credential_schema: "/wanted-10k/auditor-credential.schema.json",
    auditor_credential_template: "/wanted-10k/auditor-credential.template.json",
    audit_verifier_quickstart: "/wanted-10k/audit-sdk",
    audit_verifier_module: "/wanted-10k/wanted-audit-verifier.mjs",
    audit_verifier_contract: "/wanted-10k/audit-verifier-sdk.json",
    auditor_trust_root_schema: "/wanted-10k/auditor-trust-root.schema.json",
    auditor_trust_root_template: "/wanted-10k/auditor-trust-root.template.json",
    audit_manifest_schema: "/wanted-10k/audit-manifest.schema.json",
    audit_manifest_template: "/wanted-10k/audit-manifest.template.json",
  },
  certification_handoff: {
    public_unit: "aggregate_audit_manifest",
    participant_data_permitted: false,
    binds: ["preregistration", "robot_versions", "preflight", "cohort_summary", "cohort_integrity", "exposure_integrity", "analysis_reproduction", "primary_score", "diagnostics", "safety_evidence", "telemetry_key_manifest", "telemetry_authenticity_report", "telemetry_commitments", "endpoint_adjudication", "withdrawal_results", "independent_audit_seal_0.2-V1", "auditor_credential_0.2-V2"],
    local_readiness_is_certification: false,
  },
  changelog: {
    "0.2-audit-verifier-sdk-1": ["ship_zero_dependency_audit_verifier_ESM", "enforce_strict_I-JSON_before_JCS", "publish_trust_root_schema", "require_explicit_production_root_injection", "bind_contract_to_distributed_source_digest"],
    "0.2-auditor-credential-1": ["publish_auditor_credential_0.2-V2", "pin_registry_issuer_root", "bind_auditor_identity_and_key_subject", "enforce_target_authorization_validity_revocation_and_mode_boundary"],
    "0.2-audit-seal-1": ["publish_independent_audit_seal_0.2-V1", "freeze_non_recursive_manifest_signature_scope", "verify_manifest_and_public_key_digests", "require_valid_Ed25519_seal_for_every_certification"],
    "0.2-telemetry-1": ["publish_telemetry_authenticity_0.2-T1", "verify_every_Ed25519_event_signature", "enforce_frozen_key_validity_and_revocation", "bind_authenticity_report_into_field_certification"],
    "0.2-analysis-1": ["publish_analysis_reproduction_0.2-A1", "freeze_cross_implementation_PCG32_bootstrap", "bind_ranked_W_to_endpoint_table", "reproduce_primary_uncertainty_and_robustness"],
    "0.2-exposure-1": ["add_signed_deployment_lifecycle_boundaries", "publish_exposure_ledger_0.2-X1", "reconcile_all_claimed_resident_hours", "forbid_pause_deductions"],
    "0.2-adapter-1": ["ship_executable_zero_dependency_ESM_adapter", "define_durable_restart_checkpoint", "publish_machine_readable_deployment_configuration"],
    "0.2": ["forbid_unsupported_10k_RMST_extrapolation", "freeze_endpoint_and_censoring_taxonomy", "define_RFC8785_hash_chain", "add_preregistration_and_conformance_resources"],
  },
};

export async function GET() {
  return Response.json(spec, { headers: { "cache-control": "public, max-age=3600" } });
}
