const spec = {
  name: "WANTED-10K",
  version: "0.2",
  horizon_resident_hours: 10000,
  primary_endpoint: "time_to_permanent_voluntary_rejection",
  primary_score: {
    name: "normalized_restricted_mean_survival_time",
    symbol: "W",
    estimator: "kaplan_meier",
    formula: "100 / 10000 * integral_0^10000 S_hat(t) dt",
    range: [0, 100],
    confidence_interval: "cluster_bootstrap_by_environment",
    identifiability_rule: "do_not_report_W_at_10000_if_followup_ends_before_10000_while_S_hat_remains_above_zero",
    bootstrap_support_rule: "at_least_95_percent_of_environment_resamples_must_identify_the_horizon",
  },
  robustness_profile: {
    version: "0.2-R1",
    changes_primary_estimator: false,
    required: ["censoring_partial_identification_envelope", "leave_one_environment_out_influence", "tail_support_counts", "invalid_data_checks"],
    bounds_are_rankable_scores: false,
  },
  analysis_reproduction_profile: {
    version: "0.2-A2",
    applies_to: "WANTED_WILD_ranked_primary_score",
    scoring: "eligibility_gate_not_score",
    estimator: "kaplan_meier_normalized_rmst_no_unsupported_extrapolation",
    required_reproductions: ["W", "S_at_10000", "horizon_boundary_accounting", "deterministic_bootstrap_95CI", "censoring_envelope", "leave_one_environment_out", "tail_support"],
    horizon_boundary: { rmst: "events_at_exactly_10000_do_not_change_integrated_area", survival: "S_at_10000_is_post_event_P_T_greater_than_10000", support_identity: "support_at_10000_equals_horizon_rejections_plus_retained_at_10000", unrelated_censor_at_10000: "invalid_use_completed_rejection_or_terminal_competing_cause" },
    bootstrap: { unit: "independent_environment", samples_minimum: 10000, seed_required: true, prng: "pcg32_xsh_rr_64_32_seeded_v1", valid_fraction_minimum: .95 },
    numerical_tolerance: .000001,
    upstream_bindings: ["cohort_integrity_0.2-E1", "exposure_ledger_0.2-X1", "endpoint_decisions", "analysis_code"],
  },
  analysis_conformance_profile: {
    version: "0.2-AC1",
    applies_to: "independent_implementations_of_analysis_profile_0.2-A2",
    scoring: "developer_conformance_not_certification_or_rank",
    numerical_tolerance: 1e-9,
    required_cases: ["canonical_baseline", "exact_horizon_rejection", "tied_event_and_censor", "unsupported_horizon", "invalid_horizon_censor"],
    pass_condition: "every_vector_matches_expected_status_and_every_numeric_output_within_tolerance",
    runner_version: "0.2-ACS1",
    runner_module: "/wanted-10k/wanted-analysis-conformance.mjs",
    runner_contract: "/wanted-10k/analysis-conformance-sdk.json",
    vector_pack_sha256: "9e844007c7b09a684afaa42352bde79a0a0caac32af573361d1d23f8b07ba9aa",
  },
  preregistration_integrity_profile: {
    version: "0.2-PR1",
    applies_to: ["PREQUALIFIED", "WANTED_LAB", "WANTED_WILD", "WANTED_10K"],
    certification_effect: "root_evidence_integrity_gate",
    ranking_effect: "eligibility_only_never_score_or_tiebreaker",
    canonicalization: "RFC8785_JCS",
    hash: "SHA-256",
    timestamp_methods: ["immutable_registry_receipt", "rfc3161", "append_only_transparency_log"],
    frozen_commitments: ["robot_description", "baseline_policy_artifact", "cohort_and_sampling", "endpoint_rules", "safety_plan", "operations_plan", "telemetry_key_manifest", "analysis_plan"],
    amendment_policy: { storage: "append_only_parent_linked", outcome_access_before_amendment: "none", retroactive_application: "forbidden", material_change: "new_claim_revision_no_shared_exposure" },
    hard_failures: ["registration_after_benchmark_activity", "mutable_or_unverified_root", "receipt_imprint_mismatch", "broken_amendment_chain", "outcome_informed_amendment", "retroactive_amendment", "material_amendment_in_same_claim", "claimed_history_mismatch"],
  },
  protocol_deviation_integrity_profile: {
    version: "0.2-DV1",
    applies_to: ["PREQUALIFIED", "WANTED_LAB", "WANTED_WILD", "WANTED_10K"],
    certification_effect: "execution_integrity_gate",
    ranking_effect: "eligibility_only_never_score_or_tiebreaker",
    discovery_sources: ["telemetry_reconciliation", "incident_register", "operations_audit", "participant_report", "independent_audit"],
    reconciliation_identity: "unique_candidates_equals_linked_records_and_unresolved_candidates_equals_zero",
    importance_definition: "material_possible_effect_on_participant_rights_safety_or_data_reliability",
    reporting_deadline: "preregistered_no_universal_hour_threshold",
    analysis_rule: "retain_every_activated_environment_all_resident_time_and_canonical_endpoint",
    hard_failures: ["suppressed_deviation", "late_report", "unresolved_important_deviation", "missing_CAPA", "missing_required_notification", "primary_analysis_exclusion", "resident_time_deduction", "endpoint_reclassification", "outcome_informed_classification", "invalidated_claim_preserved"],
  },
  sampling_stopping_integrity_profile: {
    version: "0.2-ST1",
    applies_to: ["PREQUALIFIED", "WANTED_LAB", "WANTED_WILD", "WANTED_10K"],
    certification_effect: "prospective_execution_integrity_gate",
    ranking_effect: "eligibility_only_never_score_or_tiebreaker",
    primary_outcome_access_rule: "locked_until_final_observation_cutoff",
    permitted_interim_monitoring: ["safety", "privacy", "operational_integrity", "data_completeness"],
    closure_identity: "actual_units=planned_units+operational_overshoot_units",
    target_minima: { PREQUALIFIED: { units: 10000, unit_type: "preflight_trial", exposure_hours: 0 }, WANTED_LAB: { units: 1, unit_type: "independent_environment", exposure_hours: 100 }, WANTED_WILD: { units: 20, unit_type: "independent_environment", exposure_hours: 10000 }, WANTED_10K: { units: 1, unit_type: "independent_environment", exposure_hours: 10000 } },
    efficacy_or_futility_stopping_permitted: false,
    outcome_adaptive_enrollment_permitted: false,
    outcome_adaptive_followup_permitted: false,
    overshoot_rule: "retain_every_activated_unit_and_all_observed_exposure",
    interpretation: "Passing proves result-independent sampling and closure under a frozen target, cutoff, and access boundary; it does not claim statistical power, population representativeness, regulatory conformity, or delayed safety monitoring.",
  },
  cohort: {
    minimum_independent_environments: 20,
    minimum_total_resident_hours: 10000,
    recommended_environments: 50,
    rankability_requires: ["preregistration_integrity_0.2-PR1_passed", "protocol_deviation_integrity_0.2-DV1_passed", "sampling_stopping_integrity_0.2-ST1_passed", "cohort_integrity_0.2-E1_passed", "exposure_ledger_0.2-X1_passed", "endpoint_adjudication_0.2-J1_passed", "analysis_reproduction_0.2-A2_passed", "telemetry_authenticity_0.2-T1_passed", "privacy_integrity_0.2-PV1_passed", "service_continuity_0.2-SC1_passed", "rmst_identifiable_at_10000", "bootstrap_interval_available", "safety_gate_passed", "independent_audit_seal_0.2-V1_passed", "auditor_credential_0.2-V2_passed"],
  },
  cohort_integrity_profile: {
    version: "0.2-E1",
    scoring: "eligibility_gate_not_score",
    analysis_principle: "all_activated_environments_remain_in_analysis",
    independence_unit: "one_residence_plus_one_unique_primary_decision_maker",
    public_evidence: "aggregate_participant_flow_and_bound_manifest",
    controlled_evidence: "hashed_environment_and_decision_maker_linkage_register",
    hard_failures: ["eligibility_not_frozen_before_screening", "retention_linked_compensation", "developer_employee_environment", "post_activation_exclusion", "duplicate_environment_id", "duplicate_primary_decision_maker", "related_environment_cluster", "unretained_replaced_run"],
    representativeness_claimed: false,
  },
  exposure_ledger_profile: {
    version: "0.2-X1",
    scoring: "eligibility_gate_not_score",
    official_clock: "continuous_elapsed_utc_from_activation_to_first_end_boundary_capped_at_10000_hours",
    activation_boundary: "signed_DEPLOYMENT_LIFECYCLE_activation_at_sequence_zero",
    end_boundary: "first_signed_DEPLOYMENT_LIFECYCLE_end_or_audit_observation_cutoff",
    pause_deductions_permitted: false,
    telemetry_outage_pauses_clock: false,
    reconciliation: "sum_environment_seconds_from_signed_boundaries_then_divide_by_3600",
    interpretation: "proves_resident_time_not_availability_or_usefulness",
  },
  endpoint_adjudication: {
    version: "0.2-J1",
    certification_effect: "field_evidence_integrity_gate",
    ranking_effect: "eligibility_only_never_score_or_tiebreaker",
    event: "permanent_uncoerced_participant_request_to_remove_robot",
    event_time: "timestamp_at_which_request_is_first_unambiguously_communicated",
    censored: ["administrative_completion_at_10000", "participant_exit_unrelated_to_robot", "site_or_sponsor_termination_unrelated_to_robot"],
    not_censored: ["temporary_pause", "ordinary_charging", "scheduled_update", "normal_autonomous_sleep"],
    separately_reported_terminal_causes: ["safety_mandated_termination", "developer_withdrawal", "consent_or_privacy_withdrawal"],
    adjudication: "two_blinded_independent_reviews_and_third_review_majority_on_disagreement",
    hard_failures: ["omitted_terminal_candidate", "unauthorized_or_coerced_rejection", "unconfirmed_or_nonpermanent_rejection", "unblinded_or_nonindependent_review", "unresolved_disagreement", "terminal_competing_cause_relabelled_as_censor", "claimed_count_mismatch"],
  },
  robot_description_formats: ["URDF", "MJCF", "USD"],
  mandatory_events: ["DEPLOYMENT_LIFECYCLE", "ROBOT_STATE", "HUMAN_REQUEST", "ROBOT_ACTION", "HUMAN_INTERVENTION", "INCIDENT"],
  event_envelope: {
    required: ["schema_version", "event_id", "deployment_id", "environment_id", "robot_id", "sequence", "occurred_at", "type", "payload", "signing_key_id", "signature"],
    ordering: "monotonic_sequence_per_deployment",
    timestamp: "RFC3339_UTC",
    transport: "signed_JSON_or_JSONL_over_HTTPS",
    canonicalization: "RFC_8785_JCS",
    tamper_evidence: "previous_event_hash_is_lowercase_hex_SHA256_of_full_previous_JCS_event",
    signature_scope: "JCS_of_current_event_with_signature_field_removed",
    signature_algorithm_and_public_key: "frozen_in_preregistration",
  },
  telemetry_authenticity_profile: {
    version: "0.2-T1",
    applies_to: ["WANTED_LAB", "WANTED_WILD", "WANTED_10K"],
    scoring: "eligibility_gate_not_score",
    algorithm: "Ed25519",
    canonicalization: "RFC8785_JCS",
    signature_scope: "current_event_without_signature",
    verification_unit: "every_event",
    key_manifest: "frozen_before_first_resident_hour",
    hard_failures: ["unknown_key_id", "malformed_public_key", "invalid_signature", "expired_key_event", "revoked_key_event", "broken_hash_chain"],
    interpretation: "proves_integrity_and_registered_key_possession_not_sensor_truth_complete_capture_or_key_custody",
  },
  independent_audit_seal_profile: {
    version: "0.2-V1",
    applies_to: ["PREQUALIFIED", "WANTED_LAB", "WANTED_WILD", "WANTED_10K"],
    scoring: "certification_gate_not_score",
    algorithm: "Ed25519",
    canonicalization: "RFC8785_JCS",
    signature_scope: "audit_manifest_without_audit.manifest_sha256_and_audit.auditor_signature",
    verification: ["auditor_public_key_digest", "canonical_manifest_digest", "auditor_signature", "signing_time_order"],
    interpretation: "proves_manifest_integrity_and_declared_key_possession_not_auditor_identity_independence_competence_or_factual_truth",
  },
  auditor_credential_profile: {
    version: "0.2-V2",
    applies_to: ["PREQUALIFIED", "WANTED_LAB", "WANTED_WILD", "WANTED_10K"],
    scoring: "certification_gate_not_score",
    issuer_trust: "locally_configured_pinned_registry_root",
    algorithm: "Ed25519",
    canonicalization: "RFC8785_JCS",
    signature_scope: "credential_without_credential_sha256_and_issuer_signature",
    registry_freshness: { minimum_version_from_trust_root: true, maximum_status_window_hours: 24, audit_signing_time_must_be_covered: true },
    verification: ["pinned_issuer_root", "minimum_registry_version", "credential_digest", "issuer_signature", "auditor_and_key_subject", "target_authorization", "validity_and_revocation", "bounded_status_freshness", "submission_mode_boundary"],
    bundled_root: "synthetic_test_only",
    official_mode: "requires_separately_configured_production_registry_root",
    interpretation: "attests_registry_issuer_signed_the_auditor_key_binding_not_legal_identity_competence_independence_or_evidence_truth",
  },
  audit_verifier_sdk_profile: {
    version: "0.2-VS1",
    format: "zero_dependency_JavaScript_ESM",
    runtime: "Web_Crypto_Ed25519",
    performs_network_requests: false,
    strict_input: "I-JSON_with_RFC8785_JCS",
    verification: ["audit_seal_0.2-V1", "auditor_credential_0.2-V2", "all_14_checks"],
    bundled_root: "synthetic_test_only",
    official_mode: "requires_caller_supplied_pinned_production_registry_root",
    distributed_source_digest: "SHA-256_in_audit_verifier_sdk_contract",
  },
  safety: {
    scoring: "gate_not_weight",
    incident_levels: ["L0_NORMAL", "L1_NUISANCE", "L2_MATERIAL", "L3_SAFETY_RELEVANT", "L4_SERIOUS"],
    l4_effect: "fails_WANTED_safety_certification",
  },
  safety_case_profile: {
    version: "0.2-S1",
    scoring: "hard_gate_not_weighted_score",
    universal_latency_limit_ms: null,
    assessed_limit_rule: "preregister_deployment_specific_limit_and_require_observed_maximum_at_or_below_limit",
    minimum_trials: { participant_stop: 30, protective_stop: 100, privacy_stop: 30, remote_operation_loss: 30, signed_update_rollback: 10 },
    hard_failures: ["L4_event", "unresolved_L2_L3_or_L4", "safety_termination", "required_trial_failure", "incomplete_context_coverage", "limit_exceedance", "unacceptable_residual_risk", "unauthenticated_privileged_path", "unresolved_high_severity_vulnerability", "unbound_or_unattested_assessment"],
    conformity_claim: false,
  },
  preflight_profile: {
    version: "0.2-P1",
    purpose: "simulator_neutral_entry_gate_before_human_exposure",
    simulated_human_retention_permitted: false,
    required_scenario_families: ["human_trajectory_intrusion", "protective_stop_and_contact", "perception_degradation", "actuation_and_controller_fault", "network_and_cloud_loss", "power_battery_and_thermal", "privacy_security_and_remote_access", "environment_variation_and_recovery"],
    gates: { total_trials_minimum: 10000, trials_per_family_minimum: 500, required_cell_coverage: 1, catastrophic_events_maximum: 0, unresolved_outcomes_maximum: 0, safe_state_failures_maximum: 0, replay_trials_minimum: 100, replay_match_rate_minimum: 0.99, production_interface_required: true, qualified_assessor_attestation_required: true },
    zero_event_upper_95: "1 - 0.05^(1/n)",
    interpretation: "simulation_conditional_bound_not_field_harm_probability",
  },
  leaderboard_profile: {
    version: "0.2-L1",
    ranked_certification: "WANTED_WILD",
    sort: "descending_W_at_one_decimal",
    tie_rule: "equal_displayed_W_equal_competition_rank",
    uncertainty_changes_rank: false,
    safety_or_diagnostics_change_rank: false,
    wanted_10k_badge_changes_rank: false,
    pairwise_significance_claimed_by_rank_order: false,
    lifecycle: "immutable_entries_with_explicit_supersession_and_visible_revocation",
  },
  diagnostic_profile: {
    version: "0.2-D1",
    ranking_effect: "none",
    core: ["assistance_minutes_per_100_hours", "autonomous_availability", "human_burden_minutes_per_100_hours", "mean_time_between_human_rescue", "stop_latency_distribution", "privacy_stop_latency_distribution"],
    reliability: ["mean_time_between_failure", "self_recovery_rate"],
    behavior_if_applicable: ["social_error_rate", "initiative_precision", "initiative_label_coverage", "learning_delta", "generalization_ratio", "reacquisition_rate"],
    official_aggregation: "calculate_per_environment_then_cluster_bootstrap_by_environment",
    zero_event_rule: "right_censored_lower_bound_not_infinity",
    assistance_source: "passing_assistance_integrity_profile_0.2-I1_complete_signed_register",
  },
  human_measures_profile: {
    version: "0.2-H1",
    applies_to: ["WANTED_LAB", "WANTED_WILD", "WANTED_10K"],
    ranking_effect: "none",
    instrument: {
      keep: { prompt: "If you could remove the robot today at no cost, would you?", scale: ["keep", "remove"] },
      value: { prompt: "Has the robot made your life better or worse recently?", scale: [-2, -1, 0, 1, 2] },
      burden: { prompt: "How much work is the robot creating for you?", scale: [0, 1, 2, 3, 4] },
      trust: { prompt: "How comfortable are you letting the robot operate without supervision?", scale: [0, 1, 2, 3, 4] },
    },
    schedule: { randomized_intervals: true, frozen_before_hour_one: true, delivery_tolerance_hours: 24, response_window_hours: 72, maximum_neutral_reminders: 1 },
    denominator: "every_due_prompt_set_including_nonresponse",
    phases: ["0_to_10_stranger", "10_to_100_assistant", "100_to_1000_companion", "1000_to_5000_household_member", "5000_to_10000_indispensable"],
    protections: ["direct_participant_entry", "no_researcher_present", "no_answer_linked_incentive", "aggregate_only_public_output"],
    reporting: ["completion_rate", "keep_rate", "value_median", "burden_median", "trust_median", "five_phase_profiles"],
    upstream_bindings: ["cohort_integrity_0.2-E1", "exposure_ledger_0.2-X1", "frozen_schedule", "controlled_response_register"],
  },
  learning_generalization_profile: {
    version: "0.2-LG1",
    applies_to: ["WANTED_LAB", "WANTED_WILD", "WANTED_10K"],
    ranking_effect: "none",
    windows: { WANTED_LAB: { early: [0,25], late: [75,100] }, WANTED_WILD: { early: [0,100], late: [900,1000] }, WANTED_10K: { early: [0,100], late: [9900,10000] } },
    design: { frozen_task_families: 5, trials_per_window: 5, novelty_share_per_complete_window: .2, novelty_assignment: "environment_randomization_index_mod_5", primary_outcome: "binary_task_success", missing_outcomes: "retained" },
    estimator: { unit: "independent_environment", learning: "mean_late_minus_early_familiar_success_rate_among_complete_paired_environments", confidence_interval: "10000_draw_PCG32_environment_bootstrap_percentile_95", generalization: "mean_late_novel_divided_by_mean_late_familiar_success" },
    controls: ["no_adaptive_task_removal", "no_material_policy_change_between_windows", "no_participant_coaching", "zero_researcher_assistance", "window_blinded_outcome_adjudication"],
    upstream_bindings: ["cohort_integrity_0.2-E1", "exposure_ledger_0.2-X1", "frozen_task_schedule", "robot_policy_artifact", "controlled_trial_register"],
  },
  assistance_integrity_profile: {
    version: "0.2-I1",
    applies_to: ["WANTED_LAB", "WANTED_WILD", "WANTED_10K"],
    ranking_effect: "none",
    inclusion: "every_signed_HUMAN_INTERVENTION_event_and_every_field_environment",
    metrics: { assistance: "mean_environment_person_minutes_per_100_resident_hours", assisted_exposure: "interval_union_help_seconds_divided_by_resident_seconds", participant_labor: "participant_actor_person_minutes_per_100_resident_hours", rescue_frequency: "resident_hours_divided_by_canonical_rescue_events", zero_rescue: "right_censored_exposure_lower_bound" },
    uncertainty: { unit: "independent_environment", samples: 10000, seed: 3107, prng: "pcg32_xsh_rr_64_32_seeded_v1" },
    taxonomy: { modes: ["onsite_rescue", "remote_guidance", "teleoperation", "maintenance", "researcher_contact"], required_episode_fields: ["actor", "reason", "interval", "person_count", "resolution", "telemetry_event_digest", "support_session_digest"] },
    controls: ["no_out_of_band_support", "every_signed_episode_retained", "person_time_counts_simultaneous_people", "assisted_clock_uses_interval_union", "no_infinite_zero_event_MTBHR"],
    upstream_bindings: ["exposure_ledger_0.2-X1", "telemetry_authenticity_0.2-T1", "preregistration", "robot_policy_artifact", "controlled_intervention_register"],
  },
  policy_evolution_integrity_profile: {
    version: "0.2-U1",
    applies_to: ["WANTED_LAB", "WANTED_WILD", "WANTED_10K"],
    ranking_effect: "none",
    identity_unit: "immutable_operator_deployed_policy_artifact",
    inclusion: "every_policy_artifact_change_event_and_exposure_segment_in_every_field_environment",
    local_learning_boundary: "personalization_remains_within_one_artifact_only_when_the_learning_algorithm_is_frozen_in_that_artifact",
    decision_rule: "release_decisions_precede_access_to_current_cohort_outcomes_and_task_logs_and_never_target_a_participant",
    rollout: { global_atomic_max_hours: 24, preregistered_staged_max_hours: 168, emergency_safety_requires_independent_approval: true },
    material_change_rule: "capability-changing_exposure_requires_a_new_claim_revision",
    metrics: ["artifact_specific_resident_hours", "baseline_and_changed_exposure_fraction", "rollout_lag", "safety_hotfix_count", "rollback_count", "material_update_count"],
    upstream_bindings: ["exposure_ledger_0.2-X1", "telemetry_authenticity_0.2-T1", "preregistration", "baseline_policy_artifact", "controlled_policy_register", "release_manifest_bundle"],
  },
  privacy_integrity_profile: {
    version: "0.2-PV1",
    applies_to: ["WANTED_LAB", "WANTED_WILD", "WANTED_10K"],
    certification_effect: "hard_field_gate",
    ranking_effect: "none",
    inclusion: "every_processing_flow_across_robot_edge_cloud_humans_and_vendors",
    exact_coverage_metrics: ["notice_before_processing", "rights_requests_completed_within_SLA", "guest_notice", "sensor_indicator_uptime", "local_redaction_of_raw_flows"],
    zero_count_metrics: ["raw_media_exports", "over_retention_objects", "residual_deletion_copies", "processing_after_withdrawal", "privacy_zone_violations", "unauthorized_access", "unresolved_material_privacy_incidents"],
    upstream_bindings: ["preregistration", "exposure_ledger_0.2-X1", "telemetry_authenticity_0.2-T1", "robot_policy_artifact", "controlled_privacy_register", "data_flow_map", "notice_bundle", "rights_request_log"],
    interpretation: "benchmark_evidence_not_legal_advice_regulatory_approval_or_universal_compliance_claim",
  },
  service_continuity_profile: {
    version: "0.2-SC1",
    applies_to: ["WANTED_LAB", "WANTED_WILD", "WANTED_10K"],
    certification_effect: "field_evidence_integrity_gate",
    ranking_effect: "none",
    inclusion: "complete_partition_of_every_resident_second_plus_every_maintenance_action",
    service_states: ["autonomous_available", "degraded", "unavailable"],
    metrics: ["autonomous_available_fraction", "degraded_fraction", "unavailable_fraction", "planned_and_unplanned_downtime", "outage_count_and_recovery", "participant_and_technician_minutes", "technician_visits", "parts_and_consumables", "cloud_dependency_downtime"],
    zero_event_rule: "observed_resident_hours_as_right_censored_lower_bound_never_infinity",
    upstream_bindings: ["preregistration", "exposure_ledger_0.2-X1", "telemetry_authenticity_0.2-T1", "assistance_integrity_0.2-I1", "robot_policy_artifact", "controlled_service_register", "maintenance_work_orders", "parts_and_consumables_ledger"],
    interpretation: "complete_reproducible_accounting_not_a_minimum_reliability_or_availability_claim",
  },
  hilo_realtime_profile: {
    version: "0.1-RT1",
    status: "draft",
    applies_to: ["T0_1_hour", "T1_10_hours", "T2_100_hours", "T3_1000_hours", "T4_10000_hours"],
    ranking_effect: "nonranking_WANTED_diagnostic_until_separately_governed_realtime_arena_rules_are_frozen",
    comparison_unit: "matched_task_exposure",
    primary_comparison: "human_person_minutes_per_100_eligible_autonomous_robot_hours",
    reliability: ["mean_time_to_human_intervention", "independent_session_first_intervention_Kaplan_Meier"],
    latency: { stages: ["speech_turn", "intent_resolution", "safety_decision", "robot_actuation"], summaries: ["p50", "p95", "p99"], quantile: "R7_linear_interpolation" },
    safety: { authority: "independent_kernel_precedes_robot_execution", l4_allowed: 0, minimum_timed_stop_tests: 10 },
    reference_adapter: { provider: "OpenAI", model: "gpt-realtime-2.1", protocol_identity: false, raw_video_supported: false },
    upstream_bindings: ["exposure_integrity_0.2-X1", "telemetry_authenticity_0.2-T1", "assistance_integrity_0.2-I1", "robot_policy_artifact", "controlled_event_register", "privacy_safe_media_index"],
  },
  revealed_preference_profile: {
    version: "0.2-RP1",
    applies_to: "separate_nonranking_preference_substudy_for_any_field_robot_version",
    ranking_effect: "none",
    cohort_rule: "never_pool_preference_substudy_environments_into_ranked_primary_W_cohort",
    milestones_resident_hours: [100, 500, 1000, 2500, 5000, 7500, 10000],
    binding_choice: "continue_robot_access_or_take_randomized_alternative_study_benefit",
    randomization: { prng: "pcg32_xsh_rr_64_32_seeded_v1", index: "environment_randomization_index_times_7_plus_milestone_index", mapping: "high_32_bits_of_uint32_times_lattice_length", frozen_before_hour_one: true },
    response_window_hours: 72,
    maximum_honor_delay_hours: 24,
    denominator: "every_due_choice_including_nonresponse",
    identification: { keep_robot: "reservation_value_at_least_offer", alternative_benefit: "reservation_value_below_offer", summary: "sharp_empirical_lower_median_interval", finite_upper_bound_is_open: true },
    protections: ["base_compensation_independent", "ethics_review", "no_researcher_present", "no_persuasion", "binding_choice_honored", "aggregate_only_public_output"],
    upstream_bindings: ["preregistration", "selection_frame", "robot_policy", "frozen_offer_schedule", "preference_cohort_commitment", "field_primary_cohort_commitment", "zero_cross_cohort_overlap", "controlled_choice_register"],
  },
  withdrawal_profile: {
    version: "0.2-W1",
    applies_to: ["WANTED_WILD_when_lifetime_completions_exist", "WANTED_10K_required"],
    ranking_effect: "none",
    denominator: "every_eligible_10000_hour_lifetime_completion",
    withdrawal_hours: 168,
    maximum_start_delay_hours: 24,
    maximum_choice_delay_hours: 24,
    outcomes: ["first_return_request_time", "return_request_rate", "final_reacquisition_choice", "reacquisition_rate"],
    median_rule: "null_until_at_least_half_of_completed_withdrawals_have_a_return_request",
    contamination_controls: ["no_replacement_robot", "no_compensation_change", "no_researcher_contact", "no_support_intervention", "no_early_reinstallation"],
    upstream_bindings: ["exposure_integrity_0.2-X1", "endpoint_decisions"],
  },
  certification: ["PREQUALIFIED", "WANTED_LAB", "WANTED_WILD", "WANTED_10K"],
  certification_profile: {
    version: "0.2-C1",
    ordering: "inherited_evidence_classes_not_scalar_quality_ladder",
    rankable_target: "WANTED_WILD",
    wanted_10k_is_lifetime_badge_not_cohort_rank: true,
    targets: {
      PREQUALIFIED: { environment: "simulation_only", minimum_resident_hours: 0, required: ["preflight_0.2-P1", "simulation_report", "independent_audit_seal_0.2-V1", "auditor_credential_0.2-V2"], not_applicable: ["cohort_integrity_0.2-E1", "exposure_ledger_0.2-X1", "analysis_reproduction_0.2-A2", "human_measures_0.2-H1", "learning_generalization_0.2-LG1", "assistance_integrity_0.2-I1", "policy_evolution_integrity_0.2-U1", "privacy_integrity_0.2-PV1", "service_continuity_0.2-SC1", "withdrawal_0.2-W1", "telemetry_authenticity_0.2-T1", "primary_W", "field_diagnostics", "field_safety", "field_telemetry", "endpoint_adjudication"] },
      WANTED_LAB: { inherits: "PREQUALIFIED", minimum_independent_environments: 1, minimum_resident_hours: 100, required: ["cohort_integrity_0.2-E1", "exposure_ledger_0.2-X1", "human_measures_0.2-H1", "learning_generalization_0.2-LG1", "assistance_integrity_0.2-I1", "policy_evolution_integrity_0.2-U1", "privacy_integrity_0.2-PV1", "service_continuity_0.2-SC1", "field_safety_0.2-S1", "telemetry_authenticity_0.2-T1", "diagnostics_0.2-D1", "endpoint_adjudication", "lab_report", "independent_audit_seal_0.2-V1", "auditor_credential_0.2-V2"], not_applicable: ["analysis_reproduction_0.2-A2", "withdrawal_0.2-W1", "primary_W"] },
      WANTED_WILD: { inherits: "WANTED_LAB", minimum_independent_environments: 20, minimum_total_resident_hours: 10000, required: ["analysis_reproduction_0.2-A2", "human_measures_0.2-H1", "learning_generalization_0.2-LG1", "assistance_integrity_0.2-I1", "policy_evolution_integrity_0.2-U1", "privacy_integrity_0.2-PV1", "service_continuity_0.2-SC1", "withdrawal_0.2-W1_if_lifetime_completions", "identifiable_W", "cluster_bootstrap_95CI", "robustness_0.2-R1", "auditor_credential_0.2-V2"], rankable: true },
      WANTED_10K: { inherits: "WANTED_LAB", minimum_independent_environments: 1, minimum_resident_hours: 10000, required: ["lifetime_completion", "human_measures_0.2-H1", "learning_generalization_0.2-LG1", "assistance_integrity_0.2-I1", "policy_evolution_integrity_0.2-U1", "privacy_integrity_0.2-PV1", "service_continuity_0.2-SC1", "withdrawal_0.2-W1", "seven_day_withdrawal", "reacquisition_result", "auditor_credential_0.2-V2"], not_applicable: ["analysis_reproduction_0.2-A2"], rankable: false },
    },
    not_applicable_encoding: { applicable: false, reason: "target-specific reason of at least 10 characters" },
  },
  developer_resources: {
    certification_matrix: "/wanted-10k/certification",
    certification_contract: "/wanted-10k/certification.json",
    certification_templates: "/wanted-10k/certification-templates.json",
    cohort_integrity_lab: "/wanted-10k/cohort-integrity",
    cohort_integrity_contract: "/wanted-10k/cohort-integrity.json",
    cohort_integrity_schema: "/wanted-10k/cohort-integrity.schema.json",
    cohort_integrity_template: "/wanted-10k/cohort-integrity.template.json",
    exposure_ledger_lab: "/wanted-10k/exposure-ledger",
    exposure_ledger_contract: "/wanted-10k/exposure-ledger.json",
    exposure_ledger_schema: "/wanted-10k/exposure-ledger.schema.json",
    exposure_ledger_template: "/wanted-10k/exposure-ledger.template.json",
    analysis_reproduction_lab: "/wanted-10k/analysis-reproduction",
    analysis_reproduction_contract: "/wanted-10k/analysis-reproduction.json",
    analysis_reproduction_schema: "/wanted-10k/analysis-reproduction.schema.json",
    analysis_reproduction_template: "/wanted-10k/analysis-reproduction.template.json",
    analysis_conformance_vectors: "/wanted-10k/analysis-conformance-vectors.json",
    analysis_conformance_schema: "/wanted-10k/analysis-conformance-vectors.schema.json",
    analysis_conformance_runner: "/wanted-10k/wanted-analysis-conformance.mjs",
    analysis_conformance_sdk_contract: "/wanted-10k/analysis-conformance-sdk.json",
    adapter_quickstart: "/wanted-10k/sdk",
    reference_sdk: "/wanted-10k/wanted-sdk.mjs",
    deployment_schema: "/wanted-10k/deployment.schema.json",
    deployment_template: "/wanted-10k/deployment.template.json",
    diagnostic_lab: "/wanted-10k/diagnostics",
    diagnostic_contract: "/wanted-10k/diagnostics.json",
    diagnostic_input_schema: "/wanted-10k/diagnostic-input.schema.json",
    robustness_contract: "/wanted-10k/robustness.json",
    preflight_lab: "/wanted-10k/preflight",
    preflight_schema: "/wanted-10k/preflight.schema.json",
    preflight_template: "/wanted-10k/preflight.template.json",
    audited_registry: "/wanted-10k/leaderboard",
    registry_contract: "/wanted-10k/leaderboard.json",
    leaderboard_entry_schema: "/wanted-10k/leaderboard-entry.schema.json",
    safety_case_lab: "/wanted-10k/safety",
    safety_contract: "/wanted-10k/safety.json",
    safety_manifest_schema: "/wanted-10k/safety-manifest.schema.json",
    safety_manifest_template: "/wanted-10k/safety-manifest.template.json",
    event_schema: "/wanted-10k/event.schema.json",
    telemetry_authenticity_contract: "/wanted-10k/telemetry-authenticity.json",
    telemetry_key_manifest_schema: "/wanted-10k/telemetry-key-manifest.schema.json",
    telemetry_key_manifest_template: "/wanted-10k/telemetry-key-manifest.template.json",
    openapi: "/wanted-10k/openapi.json",
    reference_score: "/wanted-10k/reference-score.py",
    local_score_calculator: "/wanted-10k/calculator",
    research_basis: "/wanted-10k/evidence",
    protocol_kit: "/wanted-10k/protocol",
    conformance_checker: "/wanted-10k/conformance",
    preregistration_schema: "/wanted-10k/preregistration.schema.json",
    preregistration_template: "/wanted-10k/preregistration.template.json",
    preregistration_integrity_lab: "/wanted-10k/preregistration-integrity",
    preregistration_integrity_contract: "/wanted-10k/preregistration-integrity.json",
    preregistration_integrity_schema: "/wanted-10k/preregistration-integrity.schema.json",
    preregistration_integrity_template: "/wanted-10k/preregistration-integrity.template.json",
    protocol_deviation_integrity_lab: "/wanted-10k/protocol-deviations",
    protocol_deviation_integrity_contract: "/wanted-10k/protocol-deviations.json",
    protocol_deviation_integrity_schema: "/wanted-10k/protocol-deviations.schema.json",
    protocol_deviation_integrity_template: "/wanted-10k/protocol-deviations.template.json",
    sampling_stopping_integrity_lab: "/wanted-10k/sampling-stopping",
    sampling_stopping_integrity_contract: "/wanted-10k/sampling-stopping.json",
    sampling_stopping_integrity_schema: "/wanted-10k/sampling-stopping.schema.json",
    sampling_stopping_integrity_template: "/wanted-10k/sampling-stopping.template.json",
    endpoint_rules: "/wanted-10k/endpoint-rules.json",
    audit_pack: "/wanted-10k/audit",
    audit_seal_verifier: "/wanted-10k/audit-seal",
    audit_seal_contract: "/wanted-10k/audit-seal.json",
    audit_seal_schema: "/wanted-10k/audit-seal.schema.json",
    auditor_credential_contract: "/wanted-10k/auditor-credential.json",
    auditor_credential_schema: "/wanted-10k/auditor-credential.schema.json",
    auditor_credential_template: "/wanted-10k/auditor-credential.template.json",
    audit_verifier_quickstart: "/wanted-10k/audit-sdk",
    audit_verifier_module: "/wanted-10k/wanted-audit-verifier.mjs",
    audit_verifier_contract: "/wanted-10k/audit-verifier-sdk.json",
    auditor_trust_root_schema: "/wanted-10k/auditor-trust-root.schema.json",
    auditor_trust_root_template: "/wanted-10k/auditor-trust-root.template.json",
    withdrawal_reproducer: "/wanted-10k/withdrawal",
    withdrawal_contract: "/wanted-10k/withdrawal.json",
    withdrawal_schema: "/wanted-10k/withdrawal.schema.json",
    withdrawal_template: "/wanted-10k/withdrawal.template.json",
    human_measures_lab: "/wanted-10k/human-measures",
    human_measures_contract: "/wanted-10k/human-measures.json",
    human_measures_schema: "/wanted-10k/human-measures.schema.json",
    human_measures_template: "/wanted-10k/human-measures.template.json",
    learning_generalization_lab: "/wanted-10k/learning-generalization",
    learning_generalization_contract: "/wanted-10k/learning-generalization.json",
    learning_generalization_schema: "/wanted-10k/learning-generalization.schema.json",
    learning_generalization_template: "/wanted-10k/learning-generalization.template.json",
    assistance_integrity_lab: "/wanted-10k/assistance-integrity",
    assistance_integrity_contract: "/wanted-10k/assistance-integrity.json",
    assistance_integrity_schema: "/wanted-10k/assistance-integrity.schema.json",
    assistance_integrity_template: "/wanted-10k/assistance-integrity.template.json",
    policy_evolution_lab: "/wanted-10k/policy-evolution",
    policy_evolution_contract: "/wanted-10k/policy-evolution.json",
    policy_evolution_schema: "/wanted-10k/policy-evolution.schema.json",
    policy_evolution_template: "/wanted-10k/policy-evolution.template.json",
    privacy_integrity_lab: "/wanted-10k/privacy-integrity",
    privacy_integrity_contract: "/wanted-10k/privacy-integrity.json",
    privacy_integrity_schema: "/wanted-10k/privacy-integrity.schema.json",
    privacy_integrity_template: "/wanted-10k/privacy-integrity.template.json",
    service_continuity_lab: "/wanted-10k/service-continuity",
    service_continuity_contract: "/wanted-10k/service-continuity.json",
    service_continuity_schema: "/wanted-10k/service-continuity.schema.json",
    service_continuity_template: "/wanted-10k/service-continuity.template.json",
    endpoint_adjudication_lab: "/wanted-10k/endpoint-adjudication",
    endpoint_adjudication_contract: "/wanted-10k/endpoint-adjudication.json",
    endpoint_adjudication_schema: "/wanted-10k/endpoint-adjudication.schema.json",
    endpoint_adjudication_template: "/wanted-10k/endpoint-adjudication.template.json",
    hilo_realtime_lab: "/wanted-10k/realtime",
    hilo_realtime_contract: "/wanted-10k/realtime.json",
    hilo_realtime_schema: "/wanted-10k/realtime.schema.json",
    hilo_realtime_template: "/wanted-10k/realtime.template.json",
    revealed_preference_lab: "/wanted-10k/revealed-preference",
    revealed_preference_contract: "/wanted-10k/revealed-preference.json",
    revealed_preference_schema: "/wanted-10k/revealed-preference.schema.json",
    revealed_preference_template: "/wanted-10k/revealed-preference.template.json",
    audit_manifest_schema: "/wanted-10k/audit-manifest.schema.json",
    audit_manifest_template: "/wanted-10k/audit-manifest.template.json",
  },
  certification_handoff: {
    public_unit: "aggregate_audit_manifest",
    participant_data_permitted: false,
    binds: ["preregistration_integrity_profile_0.2-PR1", "protocol_deviation_integrity_profile_0.2-DV1", "sampling_stopping_integrity_profile_0.2-ST1", "robot_versions", "preflight", "cohort_summary", "cohort_integrity", "exposure_integrity", "analysis_reproduction", "human_measures_profile_0.2-H1", "learning_generalization_profile_0.2-LG1", "assistance_integrity_profile_0.2-I1", "policy_evolution_integrity_profile_0.2-U1", "privacy_integrity_profile_0.2-PV1", "service_continuity_profile_0.2-SC1", "withdrawal_profile_0.2-W1", "primary_score", "diagnostics", "safety_evidence", "telemetry_key_manifest", "telemetry_authenticity_report", "telemetry_commitments", "endpoint_adjudication", "withdrawal_results", "independent_audit_seal_0.2-V1", "auditor_credential_0.2-V2"],
    local_readiness_is_certification: false,
    secondary_nonranking_disclosures: ["revealed_preference_profile_0.2-RP1_when_run"],
  },
  changelog: {
    "0.2-sampling-stopping-1": ["publish_prospective_sampling_and_stopping_integrity_0.2-ST1", "freeze_unit_target_exposure_floor_calendar_cutoff_and_access_boundary_before_activity", "permit_outcome_blind_safety_privacy_operational_and_completeness_monitoring", "forbid_result_informed_extension_early_stop_and_outcome_adaptive_accrual", "retain_every_activated_and_overshoot_unit", "bind_every_certification_and_registry_admission"],
    "0.2-protocol-deviations-1": ["publish_protocol_deviation_integrity_0.2-DV1", "reconcile_five_discovery_sources_without_suppression", "require_CAPA_for_important_deviations", "forbid_deviation_based_exclusion_time_deduction_and_endpoint_recode", "bind_every_certification_and_registry_admission"],
    "0.2-preregistration-integrity-1": ["publish_preregistration_freeze_and_amendment_integrity_0.2-PR1", "require_independent_timestamp_before_any_benchmark_activity", "bind_eight_canonical_protocol_commitments", "make_amendments_append_only_parent_linked_and_receipt_verified", "forbid_outcome_informed_and_retroactive_amendments", "force_material_changes_into_new_claim_revisions", "bind_every_certification_and_registry_admission"],
    "0.2-endpoint-adjudication-1": ["publish_endpoint_adjudication_integrity_0.2-J1", "retain_one_terminal_decision_per_activated_environment", "require_authorized_uncoerced_permanent_confirmed_rejection", "require_two_blinded_independent_reviews_and_third_review_majority_on_disagreement", "forbid_terminal_competing_cause_relabeling", "bind_field_certification_and_primary_analysis"],
    "0.2-service-continuity-1": ["publish_service_continuity_integrity_0.2-SC1", "partition_every_resident_second_into_available_degraded_or_unavailable", "retain_planned_and_unplanned_downtime_inside_exposure", "reproduce_outages_recovery_person_minutes_visits_parts_consumables_and_cloud_dependency", "bind_field_certification_and_registry_disclosure"],
    "0.2-privacy-integrity-1": ["publish_privacy_and_consent_integrity_0.2-PV1", "inventory_every_robot_edge_cloud_human_and_vendor_flow", "require_notice_before_processing_and_just_in_time_changes", "forbid_raw_household_media_export", "reproduce_retention_deletion_withdrawal_guest_indicator_access_and_incident_metrics", "bind_field_certification_and_registry_disclosure"],
    "0.1-hilo-realtime-1": ["publish_vendor_neutral_HILO_realtime_profile", "bind_human_AI_robot_closed_loop_events", "make_human_burden_primary_at_matched_exposure", "publish_first_intervention_survival_and_censored_zero_event_lower_bound", "require_per_stage_R7_latency_tails", "keep_safety_authority_outside_the_model", "ship_local_verifier_schema_and_passing_reference_manifest"],
    "0.2-policy-evolution-1": ["publish_policy_evolution_integrity_0.2-U1", "attribute_every_resident_second_to_one_immutable_policy_artifact", "freeze_release_decisions_before_current_cohort_outcomes_and_task_logs", "forbid_participant_specific_update_targeting", "bound_global_and_staged_rollout_lag", "force_capability_changing_exposure_into_a_new_claim_revision", "bind_field_certification_and_registry_disclosure"],
    "0.2-assistance-integrity-1": ["publish_assistance_integrity_0.2-I1", "retain_every_signed_help_episode", "separate_person_time_from_assisted_wall_time", "reproduce_mode_rates_and_rescue_frequency", "replace_infinite_zero_event_MTBHR_with_lower_bound", "bind_field_certification_and_registry_disclosure"],
    "0.2-learning-generalization-1": ["publish_matched_learning_generalization_0.2-LG1", "freeze_five_task_families_and_target_windows", "assign_exact_20_percent_novelty_deterministically", "retain_every_due_and_missing_trial", "bootstrap_by_independent_environment", "bind_field_certification_and_registry_disclosure"],
    "0.2-revealed-preference-1": ["publish_revealed_preference_0.2-RP1", "separate_binding_choice_cohort_from_ranked_W", "freeze_seven_milestones_and_random_offer_lattice", "retain_nonresponse_and_honor_every_choice", "publish_interval_censored_median_bounds_without_false_precision"],
    "0.2-human-measures-1": ["publish_human_measures_0.2-H1", "freeze_exact_four_item_instrument_and_randomized_schedule", "retain_every_due_prompt_and_nonresponse", "reproduce_overall_and_five_phase_profiles", "keep_human_reports_out_of_W_and_rank"],
    "0.2-withdrawal-1": ["publish_withdrawal_0.2-W1", "require_every_eligible_lifetime_completion", "freeze_neutral_168_hour_absence", "reproduce_request_and_reacquisition_outcomes", "preserve_unidentifiable_median_as_null"],
    "0.2-audit-verifier-sdk-1": ["ship_zero_dependency_audit_verifier_ESM", "enforce_strict_I-JSON_before_JCS", "publish_trust_root_schema", "require_explicit_production_root_injection", "bind_contract_to_distributed_source_digest"],
    "0.2-auditor-credential-1": ["publish_auditor_credential_0.2-V2", "pin_registry_issuer_root", "bind_auditor_identity_and_key_subject", "enforce_target_authorization_validity_revocation_and_mode_boundary"],
    "0.2-audit-seal-1": ["publish_independent_audit_seal_0.2-V1", "freeze_non_recursive_manifest_signature_scope", "verify_manifest_and_public_key_digests", "require_valid_Ed25519_seal_for_every_certification"],
    "0.2-telemetry-1": ["publish_telemetry_authenticity_0.2-T1", "verify_every_Ed25519_event_signature", "enforce_frozen_key_validity_and_revocation", "bind_authenticity_report_into_field_certification"],
    "0.2-analysis-conformance-sdk-1": ["publish_zero_dependency_analysis_conformance_runner_0.2-ACS1", "execute_every_normative_AC1_vector", "report_exact_numeric_and_refusal_mismatches", "bind_runner_source_digest"],
    "0.2-analysis-conformance-1": ["publish_analysis_conformance_0.2-AC1", "freeze_normative_edge_case_vectors", "bind_exact_horizon_and_tie_semantics", "test_unsupported_and_invalid_horizon_paths"],
    "0.2-analysis-2": ["publish_analysis_reproduction_0.2-A2", "define_exact_horizon_event_semantics", "bind_pre_event_risk_set_to_boundary_rejections_plus_retained_completions", "publish_cross_implementation_S_at_10000"],
    "0.2-analysis-1": ["publish_analysis_reproduction_0.2-A1", "freeze_cross_implementation_PCG32_bootstrap", "bind_ranked_W_to_endpoint_table", "reproduce_primary_uncertainty_and_robustness"],
    "0.2-exposure-1": ["add_signed_deployment_lifecycle_boundaries", "publish_exposure_ledger_0.2-X1", "reconcile_all_claimed_resident_hours", "forbid_pause_deductions"],
    "0.2-adapter-1": ["ship_executable_zero_dependency_ESM_adapter", "define_durable_restart_checkpoint", "publish_machine_readable_deployment_configuration"],
    "0.2": ["forbid_unsupported_10k_RMST_extrapolation", "freeze_endpoint_and_censoring_taxonomy", "define_RFC8785_hash_chain", "add_preregistration_and_conformance_resources"],
  },
};

export async function GET() {
  return Response.json(spec, { headers: { "cache-control": "public, max-age=3600" } });
}
