import type { Metadata } from "next";
import { SiteNav } from "../../components/SiteNav";
import { SiteHeterogeneityLab } from "./SiteHeterogeneityLab";

export const metadata: Metadata = { title: "Site Heterogeneity - WANTED-10K", description: "Prevent one deployment site from dominating a pooled WANTED score and disclose site-level instability.", alternates: { canonical: "/wanted-10k/site-heterogeneity" } };
const gates = [["SH1", "FROZEN DESIGN", "Define sites before outcomes exist."], ["SH2", "MULTI-SITE SUPPORT", "At least three substantive sites."], ["SH3", "BOUND ENDPOINTS", "One opaque site per environment."], ["SH4", "POOLED IDENTITY", "Never replace or reweight W."], ["SH5", "SITE DISCLOSURE", "Report W or null by site."], ["SH6", "SITE-OUT SENSITIVITY", "Remove each site in turn."], ["SH7", "INDEPENDENT AUDIT", "Bind assignments and reproduction."]];

export default function SiteHeterogeneityPage() { return <main className="sitePage"><SiteNav/>
  <section className="siteHero shell"><span className="eyebrow"><i className="liveDot"/> SITE HETEROGENEITY - 0.2-SH1</span><h1>One score.<br/><em>More than one site.</em></h1><p>A pooled survival estimate can look stable while one field operation supplies nearly every household. WANTED WILD now requires at least three substantive sites, caps any site at half the cohort, reproduces W within each site, and removes each site in turn.</p><div className="siteActions"><a className="primary" href="#evaluator">Test a manifest <span>-&gt;</span></a><a className="secondary" href="/wanted-10k/site-heterogeneity.template.json">Download template</a><a className="secondary" href="/wanted-10k/site-heterogeneity.json">Open contract</a></div><div className="siteProof"><div><b>3+</b><span>SUBSTANTIVE SITES</span></div><div><b>≤50%</b><span>MAX SITE SHARE</span></div><div><b>3+</b><span>ENVIRONMENTS / SITE</span></div><div><b>0</b><span>RANKING WEIGHT</span></div></div></section>
  <section className="siteGateSection"><div className="shell"><div className="sectionHead wantedHead"><div><span className="kicker">01 / POOLED-SCORE DEFENSE</span><h2>Spread the evidence.<br/><em>Expose the dependence.</em></h2></div><p>Topology is a certification gate. Site-specific outcomes are public diagnostics and never become a second score or tiebreaker.</p></div><div className="siteGateGrid">{gates.map(([id, title, copy]) => <article key={id}><span>{id}</span><b>{title}</b><p>{copy}</p><i>REQUIRED</i></article>)}</div></div></section>
  <section className="siteFormula"><div className="shell"><div><span className="kicker">02 / SAME ESTIMATOR</span><h2>Partition the rows.<br/><em>Do not move the goalposts.</em></h2><p>Every site uses the same A2 event, censoring, tie, horizon, and refusal rules. Unsupported site tails remain null. The official pooled W stays the unweighted environment-level estimate.</p></div><div className="siteEquation"><span>DOMINANCE + SENSITIVITY</span><b>max<sub>s</sub> n<sub>s</sub>/N ≤ 0.50<br/>Δ<sub>site-out</sub> = max<sub>s</sub>|W<sub>-s</sub> − W|</b><p>Passing limits concentration. It does not impose a performance threshold on site-specific W or its range.</p></div></div></section>
  <section className="siteDisclosure"><div className="shell"><div className="sectionHead wantedHead"><div><span className="kicker">03 / PUBLIC TRACE</span><h2>Show where<br/><em>the score moves.</em></h2></div><p>Opaque site IDs protect participants while preserving every site count, share, identifiable estimate, unsupported tail, and site-exclusion result.</p></div><div className="siteDisclosureGrid"><article><b>TOPOLOGY</b><p>Site count, smallest N, and maximum cohort share.</p></article><article><b>WITHIN SITE</b><p>W and S(10K), or null when the tail is unsupported.</p></article><article><b>SITE EXCLUSION</b><p>Complete leave-one-site-out table and maximum absolute shift.</p></article><article><b>BOUNDARY</b><p>No geographic, dwelling, cultural, or population generalization claim.</p></article></div></div></section>
  <section id="evaluator" className="siteEvaluator"><div className="shell"><div className="sectionHead wantedHead"><div><span className="kicker">04 / LOCAL VERIFIER</span><h2>Bind every site.<br/><em>Recompute every view.</em></h2></div><p>The verifier runs locally against opaque site assignments and endpoint rows. It checks prospective design, topology, pooled identity, site results, site-exclusion sensitivity, digests, and independent attestation.</p></div><SiteHeterogeneityLab/></div></section>
  <section className="siteBoundary"><div className="shell"><b>HETEROGENEITY != RANK</b><p>W alone orders eligible WILD entries. Site range, dominance, and leave-one-site-out shift are mandatory public diagnostics and forbidden tiebreakers.</p><a href="/wanted-10k/leaderboard">OPEN LEADERBOARD -&gt;</a></div></section>
  <footer className="wantedFooter"><div className="shell"><div className="brand"><span className="brandMark">EA</span><span>EMBODIED <b>ARENA</b> / SITE HETEROGENEITY</span></div><p>The multi-site integrity layer beneath a pooled W.</p><a href="/wanted-10k">BACK TO BENCHMARK -&gt;</a></div></footer>
</main>; }
