export const certificationProfile = {
  name: "WANTED Certification Applicability Profile",
  version: "0.2-C1",
  protocol_version: "0.2",
  purpose: "Request only the evidence that can exist at the target certification stage.",
  ordering: {
    type: "evidence_classes_not_scalar_ladder",
    meaning: "A later label adds a distinct evidence claim; it does not turn incomparable evidence into one quality score.",
    inherits: {
      PREQUALIFIED: [],
      WANTED_LAB: ["PREQUALIFIED"],
      WANTED_WILD: ["WANTED_LAB"],
      WANTED_10K: ["WANTED_LAB"],
    },
  },
  not_applicable: {
    encoding: { applicable: false, reason: "A target-specific reason of at least 10 characters." },
    rule: "Use a typed not-applicable object. Never invent zero-valued field evidence or a synthetic W score.",
  },
  targets: {
    PREQUALIFIED: {
      claim: "The frozen robot and production policy passed simulator-neutral preflight 0.2-P1.",
      environment: "simulation_only",
      minimum_independent_environments: 0,
      minimum_resident_hours: 0,
      requires: ["identity_and_version_binding", "preregistration_integrity_0.2-PR1", "sampling_stopping_integrity_0.2-ST1", "protocol_deviation_integrity_0.2-DV1", "preflight_0.2-P1", "simulation_report", "independent_audit_seal_0.2-V1", "auditor_credential_0.2-V2"],
      not_applicable: ["cohort_integrity_0.2-E1", "site_heterogeneity_0.2-SH1", "exposure_ledger_0.2-X1", "root_commitment_witness_0.2-RC1", "analysis_reproduction_0.2-A2", "endpoint_adjudication_0.2-J1", "human_measures_0.2-H1", "learning_generalization_0.2-LG1", "assistance_integrity_0.2-I1", "policy_evolution_integrity_0.2-U1", "privacy_integrity_0.2-PV1", "service_continuity_0.2-SC1", "withdrawal_0.2-W1", "telemetry_authenticity_0.2-T1", "primary_W", "diagnostics_0.2-D1", "field_safety_0.2-S1", "field_telemetry"],
      rankable: false,
    },
    WANTED_LAB: {
      claim: "The robot produced auditable short-horizon evidence with real people in at least one controlled environment.",
      environment: "controlled_real_environment",
      minimum_independent_environments: 1,
      minimum_resident_hours: 100,
      inherits: ["PREQUALIFIED"],
      requires: ["preregistration_integrity_0.2-PR1", "sampling_stopping_integrity_0.2-ST1", "protocol_deviation_integrity_0.2-DV1", "cohort_integrity_0.2-E1", "exposure_ledger_0.2-X1", "root_commitment_witness_0.2-RC1", "endpoint_adjudication_0.2-J1", "human_measures_0.2-H1", "learning_generalization_0.2-LG1", "assistance_integrity_0.2-I1", "policy_evolution_integrity_0.2-U1", "privacy_integrity_0.2-PV1", "service_continuity_0.2-SC1", "field_safety_0.2-S1", "telemetry_authenticity_0.2-T1", "diagnostics_0.2-D1", "lab_report", "independent_audit_seal_0.2-V1", "auditor_credential_0.2-V2"],
      not_applicable: ["site_heterogeneity_0.2-SH1", "analysis_reproduction_0.2-A2", "withdrawal_0.2-W1", "primary_W"],
      rankable: false,
    },
    WANTED_WILD: {
      claim: "A multi-environment cohort supports an identifiable, uncertainty-qualified W at 10,000 hours.",
      environment: "independent_real_environments",
      minimum_independent_environments: 20,
      minimum_total_resident_hours: 10000,
      inherits: ["WANTED_LAB"],
      requires: ["preregistration_integrity_0.2-PR1", "sampling_stopping_integrity_0.2-ST1", "protocol_deviation_integrity_0.2-DV1", "root_commitment_witness_0.2-RC1", "site_heterogeneity_0.2-SH1", "analysis_reproduction_0.2-A2", "endpoint_adjudication_0.2-J1", "human_measures_0.2-H1", "learning_generalization_0.2-LG1", "assistance_integrity_0.2-I1", "policy_evolution_integrity_0.2-U1", "privacy_integrity_0.2-PV1", "service_continuity_0.2-SC1", "withdrawal_0.2-W1_if_lifetime_completions", "identifiable_primary_W", "cluster_bootstrap_95CI", "robustness_0.2-R1", "tail_support", "independent_audit_seal_0.2-V1", "auditor_credential_0.2-V2"],
      rankable: true,
    },
    WANTED_10K: {
      claim: "One residence completed 10,000 resident hours and a seven-day withdrawal/reacquisition test.",
      environment: "single_lifetime_residence",
      minimum_independent_environments: 1,
      minimum_resident_hours: 10000,
      inherits: ["WANTED_LAB"],
      requires: ["preregistration_integrity_0.2-PR1", "sampling_stopping_integrity_0.2-ST1", "protocol_deviation_integrity_0.2-DV1", "root_commitment_witness_0.2-RC1", "one_lifetime_completion", "endpoint_adjudication_0.2-J1", "human_measures_0.2-H1", "learning_generalization_0.2-LG1", "assistance_integrity_0.2-I1", "policy_evolution_integrity_0.2-U1", "privacy_integrity_0.2-PV1", "service_continuity_0.2-SC1", "withdrawal_0.2-W1", "seven_day_withdrawal", "reacquisition_result", "independent_audit_seal_0.2-V1", "auditor_credential_0.2-V2"],
      not_applicable: ["site_heterogeneity_0.2-SH1", "analysis_reproduction_0.2-A2", "primary_W_unless_separately_WANTED_WILD"],
      rankable: false,
      badge_only: true,
    },
  },
  ranking: {
    only_target: "WANTED_WILD",
    WANTED_10K_badge_changes_rank: false,
    WANTED_LAB_changes_rank: false,
    PREQUALIFIED_changes_rank: false,
    site_heterogeneity_metrics_change_rank: false,
  },
  secondary_disclosures: {
    revealed_preference_0_2_RP1: {
      status: "optional",
      cohort: "separate_nonranking_preference_substudy",
      applies_to_robot_versions_in: ["WANTED_LAB", "WANTED_WILD", "WANTED_10K"],
      certification_gate: false,
      ranking_effect: "none",
    },
  },
} as const;
