"use client";
import { useState } from "react";
import { SiteNav } from "../components/SiteNav";
import { track } from "../components/AnalyticsHeartbeat";
const drafts=[
{day:"MON",audience:"Robotics YouTubers",subject:"The 95% success-rate trap",asset:"Factory floor breakdown",hook:"Use the intervention-cost chart in your next video."},
{day:"MON",audience:"Warehouse operators",subject:"A robot that fails every four minutes",asset:"MTBF field guide",hook:"Benchmark autonomy in staffing hours, not demos."},
{day:"TUE",audience:"VLA researchers",subject:"What one leaderboard rank hides",asset:"π0.5 vs GR00T note",hook:"A comparison template that keeps hardware context visible."},
{day:"WED",audience:"Robot developers",subject:"Drop your URDF, get a test plan",asset:"URDF readiness scanner",hook:"Private scan; no upload and no account."},
{day:"THU",audience:"Research newsletters",subject:"Five dimensions of an embodied brain",asset:"Paper club explainer",hook:"A compact visual taxonomy for your next issue."},
{day:"FRI",audience:"Dexterity teams",subject:"Vision misses the moment of contact",asset:"Tactile benchmark brief",hook:"A short framework for evaluating tactile policies."},
{day:"FRI",audience:"Open-source maintainers",subject:"Fresh objects make honest benchmarks",asset:"Generalization checklist",hook:"A citation-ready disclosure checklist for model cards."},
];
export default function Campaigns(){const [approved,setApproved]=useState<string[]>([]);return <main><SiteNav/><section className="subHero shell"><span className="kicker">OUTREACH / WEEKLY DRAFT QUEUE</span><h1>Seven useful reasons<br/><em>to reach out.</em></h1><p>Opt-in campaign briefs tied to first-party resources. Drafts only until Lemlist and a consented audience are connected.</p></section><section className="routeSection shell"><div className="connectionBanner"><span><i/>LEMLIST NOT CONNECTED</span><p>The publishing queue is ready. An installed Lemlist connection, API credential, sender identity, and consented audience are still required before anything can be created or sent.</p><button disabled>Connect in site settings</button></div><div className="campaignList"><header><span>DAY</span><span>AUDIENCE</span><span>CAMPAIGN</span><span>ASSET</span><span>STATUS</span></header>{drafts.map((x,i)=>{const id=`${x.day}-${i}`,ok=approved.includes(id);return <article key={id}><b>{x.day}</b><span>{x.audience}</span><div><strong>{x.subject}</strong><small>{x.hook}</small></div><span>{x.asset}</span><button className={ok?"approved":""} onClick={()=>{setApproved(a=>a.includes(id)?a.filter(v=>v!==id):[...a,id]);track("campaign_reviewed","/campaigns",{campaign:i,status:!ok?'approved':'draft'})}}>{ok?'APPROVED':'DRAFT'}</button></article>})}</div><p className="complianceNote">Audience rule: send only to people who opted in or have a legitimate, documented relationship to the content. Every campaign needs sender identity, unsubscribe handling, and jurisdiction-appropriate compliance review.</p></section></main>}
