"use client";
import { useState } from "react";
import { assessPreference, preferenceTemplate, type PreferenceResult } from "./profile.ts";

const initial:PreferenceResult={status:"invalid",errors:[],gates:[],summary:null};
const interval=(lower:number|null,upper:number|null)=>lower===null?"N/A":upper===null?`[${lower}, ∞)`:`[${lower}, ${upper})`;
export function PreferenceLab(){
  const [input,setInput]=useState(JSON.stringify(preferenceTemplate,null,2));
  const [result,setResult]=useState<PreferenceResult>(initial);
  const run=()=>{try{setResult(assessPreference(JSON.parse(input)))}catch(error){setResult({status:"invalid",errors:[error instanceof Error?error.message:"Invalid JSON."],gates:[],summary:null})}};
  const load=()=>{setInput(JSON.stringify(preferenceTemplate,null,2));setResult(assessPreference(preferenceTemplate))};
  const at10k=result.summary?.milestone_profiles.find(item=>item.milestone_hour===10000);
  return <div className="preferenceLab"><header><div><span>LOCAL RESERVATION-VALUE REPRODUCER</span><b>PROFILE / 0.2-RP1</b></div><div><button onClick={load}>LOAD SYNTHETIC EXAMPLE</button><button className="runPreference" onClick={run}>VERIFY -&gt;</button></div></header><div className="preferenceWorkspace"><div className="preferenceEditor"><label htmlFor="preference-input">SEPARATE-COHORT CHOICE REGISTER</label><textarea id="preference-input" spellCheck={false} value={input} onChange={event=>setInput(event.target.value)}/><footer><a href="/wanted-10k/revealed-preference.schema.json">MANIFEST SCHEMA</a><span>Runs locally. Participant records remain controlled.</span></footer></div><div className="preferenceOutput"><div className={`preferenceStatus ${result.status}`}><span>CHOICE INTEGRITY</span><b>{result.status.toUpperCase()}</b><small>{result.errors[0]||(result.status==="passed"?"All seven preference gates pass.":"One or more hard gates failed.")}</small></div>{result.summary&&<><div className="preferenceMetrics"><article><span>ENVIRONMENTS</span><b>{result.summary.eligible_environments}</b></article><article><span>COMPLETION</span><b>{(result.summary.completion_rate*100).toFixed(1)}%</b></article><article><span>PREFERENCE EXITS</span><b>{result.summary.preference_exits}</b></article><article><span>10K MEDIAN SET</span><b>{interval(at10k?.reservation_median_lower_units??null,at10k?.reservation_median_upper_units??null)}</b><small>{result.summary.currency} × {result.summary.unit_amount}</small></article></div><div className="preferenceMilestones"><header><span>HOUR</span><span>N</span><span>KEEP</span><span>MEDIAN SET</span></header>{result.summary.milestone_profiles.map(item=><div key={item.milestone_hour}><b>{item.milestone_hour.toLocaleString()}</b><span>{item.completed}/{item.due}</span><span>{item.keep_share===null?"—":`${(item.keep_share*100).toFixed(0)}%`}</span><span>{interval(item.reservation_median_lower_units,item.reservation_median_upper_units)}</span></div>)}</div></>}<div className="preferenceGates">{result.gates.map(item=><article className={item.passed?"pass":"fail"} key={item.id}><span>{item.id}</span><div><b>{item.label}</b><p>{item.detail}</p></div><i>{item.passed?"PASS":"FAIL"}</i></article>)}</div></div></div><aside><b>PRICE != RANK</b><p>Reservation value is reported only for a separate, non-ranking substudy. It never changes W, safety status, or leaderboard order and must not be interpreted as income-neutral welfare.</p></aside></div>;
}
