"use client";
import { useState } from "react";
import { assessWithdrawal, withdrawalTemplate, type WithdrawalResult } from "./profile.ts";

const initial:WithdrawalResult={status:"invalid",errors:[],gates:[],summary:null};
export function WithdrawalLab(){
  const [input,setInput]=useState(JSON.stringify(withdrawalTemplate,null,2));
  const [result,setResult]=useState<WithdrawalResult>(initial);
  const run=()=>{try{setResult(assessWithdrawal(JSON.parse(input)))}catch(error){setResult({status:"invalid",errors:[error instanceof Error?error.message:"Invalid JSON."],gates:[],summary:null})}};
  const load=()=>{setInput(JSON.stringify(withdrawalTemplate,null,2));setResult(assessWithdrawal(withdrawalTemplate))};
  return <div className="withdrawalLab"><header><div><span>LOCAL WITHDRAWAL REPRODUCER</span><b>PROFILE / 0.2-W1</b></div><div><button onClick={load}>LOAD SYNTHETIC EXAMPLE</button><button className="runWithdrawal" onClick={run}>VERIFY -&gt;</button></div></header><div className="withdrawalWorkspace"><div className="withdrawalEditor"><label htmlFor="withdrawal-input">PARTICIPANT-LEVEL WITHDRAWAL MANIFEST</label><textarea id="withdrawal-input" spellCheck={false} value={input} onChange={event=>setInput(event.target.value)}/><footer><a href="/wanted-10k/withdrawal.schema.json">MANIFEST SCHEMA</a><span>Runs locally. Public outputs remain aggregate-only.</span></footer></div><div className="withdrawalOutput"><div className={`withdrawalStatus ${result.status}`}><span>WITHDRAWAL INTEGRITY</span><b>{result.status.toUpperCase()}</b><small>{result.errors[0]||(result.status==="passed"?"All seven withdrawal gates pass.":"One or more hard gates failed.")}</small></div>{result.summary&&<div className="withdrawalMetrics"><article><span>COMPLETED</span><b>{result.summary.completed}/{result.summary.eligible}</b></article><article><span>REQUESTED RETURN</span><b>{(result.summary.return_request_rate*100).toFixed(1)}%</b></article><article><span>REACQUIRED</span><b>{(result.summary.reacquisition_rate*100).toFixed(1)}%</b></article><article><span>MEDIAN REQUEST</span><b>{result.summary.median_identifiable?`${Number(result.summary.median_days_to_return_request).toFixed(2)}D`:"NOT REACHED"}</b></article></div>}<div className="withdrawalGates">{result.gates.map(item=><article className={item.passed?"pass":"fail"} key={item.id}><span>{item.id}</span><div><b>{item.label}</b><p>{item.detail}</p></div><i>{item.passed?"PASS":"FAIL"}</i></article>)}</div></div></div><aside><b>WITHDRAWAL != RANK</b><p>The absence test is behavioral evidence for a WANTED 10K lifetime badge and a WANTED WILD disclosure. It never changes W or leaderboard order.</p></aside></div>;
}
